using System.Collections;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;

namespace LMP.Cli.Infrastructure;

/// <summary>
/// Generates <c>Generated/{Module}.Optimized.g.cs</c> files from optimized module state.
/// The generated file contains a <c>partial void ApplyOptimizedState()</c> implementation
/// that sets predictor state using direct C# property assignments and typed object
/// initializers — no JSON, no deserialization, zero runtime overhead.
/// </summary>
internal static class CSharpArtifactWriter
{
    /// <summary>
    /// Writes a <c>.g.cs</c> file for the specified module with the optimized state
    /// as pure C# (direct field access, typed demos, string literal instructions).
    /// </summary>
    public static async Task<string> WriteAsync(
        LmpModule module,
        string outputDir,
        float score,
        string optimizerName,
        string trainPath,
        CancellationToken cancellationToken)
    {
        var moduleType = module.GetType();
        var typeName = moduleType.Name;
        var ns = moduleType.Namespace ?? "";

        // Map predictor Name → field name by reflecting on the module type
        var fieldMap = DiscoverPredictorFields(module);

        // Compute staleness hash
        var trainHash = File.Exists(trainPath)
            ? await ComputeFileHashAsync(trainPath, cancellationToken)
            : "unknown";

        // Generate the C# source
        var sb = new StringBuilder(4096);

        // Header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// LMP Auto-Optimize | Score: {score:F4} | Strategy: {optimizerName}");
        sb.AppendLine($"// Dataset: sha256:{trainHash}");
        sb.AppendLine($"// Generated: {DateTime.UtcNow:O}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ").AppendLine(typeName);
        sb.AppendLine("{");
        sb.AppendLine("    partial void ApplyOptimizedState()");
        sb.AppendLine("    {");

        // Emit typed C# for each predictor
        var predictors = module.GetPredictors();
        for (int i = 0; i < predictors.Count; i++)
        {
            var (name, predictor) = predictors[i];

            if (!fieldMap.TryGetValue(name, out var fieldName))
                fieldName = "_" + name; // fallback convention

            // Instructions
            if (!string.IsNullOrEmpty(predictor.Instructions))
            {
                EmitInstructions(sb, fieldName, predictor.Instructions);
                sb.AppendLine();
            }

            // Demos
            if (predictor.Demos.Count > 0)
            {
                var predType = predictor.GetType();
                var genArgs = predType.GetGenericArguments();

                if (genArgs.Length == 2)
                {
                    var tInput = genArgs[0];
                    var tOutput = genArgs[1];

                    foreach (var demo in predictor.Demos)
                    {
                        var demoType = demo.GetType();
                        var input = demoType.GetField("Item1")?.GetValue(demo);
                        var output = demoType.GetField("Item2")?.GetValue(demo);

                        if (input is not null && output is not null)
                        {
                            EmitAddDemo(sb, fieldName, input, tInput, output, tOutput, ns);
                            sb.AppendLine();
                        }
                    }
                }
            }

            // Config (only emit non-default values)
            EmitConfig(sb, fieldName, predictor.Config);

            // Blank line between predictors
            if (i < predictors.Count - 1)
                sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        // Write to output directory
        Directory.CreateDirectory(outputDir);
        var outputPath = Path.Combine(outputDir, $"{typeName}.Optimized.g.cs");

        // Atomic write
        var tempPath = outputPath + ".tmp";
        await File.WriteAllTextAsync(tempPath, sb.ToString(), Encoding.UTF8, cancellationToken);
        File.Move(tempPath, outputPath, overwrite: true);

        return outputPath;
    }

    /// <summary>
    /// Discovers predictor field names by reflecting on the module type.
    /// Returns a map of predictor Name → field name (e.g., "qa" → "_qa").
    /// </summary>
    private static Dictionary<string, string> DiscoverPredictorFields(LmpModule module)
    {
        var map = new Dictionary<string, string>();
        var moduleType = module.GetType();
        var fields = moduleType.GetFields(
            BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);

        foreach (var field in fields)
        {
            if (!typeof(IPredictor).IsAssignableFrom(field.FieldType))
                continue;

            if (field.GetValue(module) is IPredictor pred && !string.IsNullOrEmpty(pred.Name))
                map[pred.Name] = field.Name;
        }

        return map;
    }

    /// <summary>
    /// Emits a direct Instructions assignment using the appropriate string literal style.
    /// </summary>
    private static void EmitInstructions(StringBuilder sb, string fieldName, string instructions)
    {
        if (instructions.Contains('\n') || instructions.Contains('\r'))
        {
            // Multi-line → raw string literal
            sb.AppendLine($"        {fieldName}.Instructions = \"\"\"");
            foreach (var line in instructions.Split('\n'))
                sb.Append("            ").AppendLine(line.TrimEnd());
            sb.AppendLine("            \"\"\";");
        }
        else
        {
            // Single-line → regular string literal
            sb.AppendLine($"        {fieldName}.Instructions = {EscapeString(instructions)};");
        }
    }

    /// <summary>
    /// Emits a typed AddDemo call with object initializers for input and output.
    /// </summary>
    private static void EmitAddDemo(
        StringBuilder sb,
        string fieldName,
        object input, Type tInput,
        object output, Type tOutput,
        string moduleNamespace)
    {
        var inputInit = GenerateObjectInitializer(input, tInput, "            ", moduleNamespace);
        var outputInit = GenerateObjectInitializer(output, tOutput, "            ", moduleNamespace);

        sb.AppendLine($"        {fieldName}.AddDemo(");
        sb.AppendLine($"            input: {inputInit},");
        sb.AppendLine($"            output: {outputInit});");
    }

    /// <summary>
    /// Emits Config assignment if any properties differ from defaults.
    /// </summary>
    private static void EmitConfig(StringBuilder sb, string fieldName, Microsoft.Extensions.AI.ChatOptions config)
    {
        var parts = new List<string>();

        if (config.Temperature is not null)
            parts.Add($"Temperature = {config.Temperature.Value}f");
        if (config.MaxOutputTokens is not null)
            parts.Add($"MaxOutputTokens = {config.MaxOutputTokens.Value}");
        if (config.TopP is not null)
            parts.Add($"TopP = {config.TopP.Value}f");
        if (config.FrequencyPenalty is not null)
            parts.Add($"FrequencyPenalty = {config.FrequencyPenalty.Value}f");
        if (config.PresencePenalty is not null)
            parts.Add($"PresencePenalty = {config.PresencePenalty.Value}f");
        if (config.ModelId is not null)
            parts.Add($"ModelId = {EscapeString(config.ModelId)}");

        if (parts.Count > 0)
        {
            sb.Append($"        {fieldName}.Config = new global::Microsoft.Extensions.AI.ChatOptions {{ ");
            sb.Append(string.Join(", ", parts));
            sb.AppendLine(" };");
        }
    }

    /// <summary>
    /// Generates a C# object initializer expression from a live object via reflection.
    /// Handles both object initializer syntax (parameterless ctor) and constructor
    /// argument syntax (positional records).
    /// </summary>
    private static string GenerateObjectInitializer(
        object obj, Type type, string indent, string moduleNamespace)
    {
        var typeName = ResolveTypeName(type, moduleNamespace);
        var props = type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.CanRead)
            .ToArray();

        var hasParameterlessCtor = type.GetConstructor(Type.EmptyTypes) is not null;

        if (!hasParameterlessCtor)
        {
            // Positional record or type with required ctor params → constructor syntax
            return GenerateCtorCall(obj, type, typeName, props, indent, moduleNamespace);
        }

        // Object initializer syntax: new TypeName { Prop = value, ... }
        var settableProps = props.Where(p => p.CanWrite).ToArray();
        if (settableProps.Length == 0)
            return $"new {typeName}()";

        var assignments = new List<string>();
        foreach (var prop in settableProps)
        {
            var value = prop.GetValue(obj);
            if (value is null)
                continue;

            var literal = GenerateLiteral(value, prop.PropertyType, indent + "    ", moduleNamespace);
            if (literal is not null)
                assignments.Add($"{prop.Name} = {literal}");
        }

        if (assignments.Count == 0)
            return $"new {typeName}()";

        if (assignments.Count == 1)
            return $"new {typeName} {{ {assignments[0]} }}";

        // Multi-property: one per line
        var sb = new StringBuilder();
        sb.AppendLine($"new {typeName}");
        sb.Append(indent).AppendLine("{");
        for (int i = 0; i < assignments.Count; i++)
        {
            sb.Append(indent).Append("    ").Append(assignments[i]);
            if (i < assignments.Count - 1)
                sb.AppendLine(",");
            else
                sb.AppendLine();
        }
        sb.Append(indent).Append('}');
        return sb.ToString();
    }

    /// <summary>
    /// Generates a constructor call for types without parameterless constructors
    /// (e.g., positional records like <c>record QAInput(string Question)</c>).
    /// </summary>
    private static string GenerateCtorCall(
        object obj, Type type, string typeName,
        PropertyInfo[] props, string indent, string moduleNamespace)
    {
        var ctor = type.GetConstructors()
            .OrderByDescending(c => c.GetParameters().Length)
            .FirstOrDefault();

        if (ctor is null)
            return $"default({typeName})!";

        var parameters = ctor.GetParameters();
        var args = new List<string>();

        foreach (var param in parameters)
        {
            var prop = props.FirstOrDefault(p =>
                string.Equals(p.Name, param.Name, StringComparison.OrdinalIgnoreCase));

            if (prop is null)
            {
                args.Add("default!");
                continue;
            }

            var value = prop.GetValue(obj);
            if (value is null)
            {
                args.Add("default!");
                continue;
            }

            var literal = GenerateLiteral(value, prop.PropertyType, indent + "    ", moduleNamespace);
            args.Add(literal ?? "default!");
        }

        if (args.Count <= 2)
            return $"new {typeName}({string.Join(", ", args)})";

        // Multi-arg: one per line
        var sb = new StringBuilder();
        sb.AppendLine($"new {typeName}(");
        for (int i = 0; i < args.Count; i++)
        {
            sb.Append(indent).Append("    ").Append(args[i]);
            if (i < args.Count - 1)
                sb.AppendLine(",");
            else
                sb.Append(')');
        }
        return sb.ToString();
    }

    /// <summary>
    /// Generates a C# literal for a value. Returns null if the value cannot be represented.
    /// </summary>
    private static string? GenerateLiteral(
        object value, Type type, string indent, string moduleNamespace)
    {
        // Unwrap Nullable<T>
        var underlying = Nullable.GetUnderlyingType(type);
        if (underlying is not null)
            type = underlying;

        return value switch
        {
            string s => EscapeString(s),
            bool b => b ? "true" : "false",
            int i => i.ToString(),
            long l => $"{l}L",
            float f => $"{f}f",
            double d => d.ToString(),
            decimal m => $"{m}m",
            _ when type.IsEnum => $"{ResolveTypeName(type, moduleNamespace)}.{value}",
            _ when type.IsClass || type.IsValueType =>
                GenerateObjectInitializer(value, type, indent, moduleNamespace),
            _ => null
        };
    }

    /// <summary>
    /// Returns the shortest unambiguous type name.
    /// Types in the same namespace as the module use short names; others use global::.
    /// </summary>
    private static string ResolveTypeName(Type type, string moduleNamespace)
    {
        if (type.Namespace == moduleNamespace)
            return type.Name;

        return $"global::{type.FullName ?? type.Name}";
    }

    /// <summary>
    /// Escapes a string value as a C# string literal.
    /// </summary>
    private static string EscapeString(string value)
    {
        // Use verbatim string for strings with backslashes or many quotes
        if (value.Contains('\\') || value.Count(c => c == '"') > 2)
            return $"@\"{value.Replace("\"", "\"\"")}\"";

        return $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t")}\"";
    }

    /// <summary>
    /// Checks if an existing generated file is still fresh based on dataset hash.
    /// </summary>
    public static async Task<bool> IsUpToDateAsync(
        string generatedPath,
        string trainPath,
        CancellationToken cancellationToken)
    {
        if (!File.Exists(generatedPath) || !File.Exists(trainPath))
            return false;

        var currentHash = await ComputeFileHashAsync(trainPath, cancellationToken);

        using var reader = new StreamReader(generatedPath);
        for (int i = 0; i < 10; i++)
        {
            var line = await reader.ReadLineAsync(cancellationToken);
            if (line is null)
                break;

            if (line.StartsWith("// Dataset: sha256:"))
            {
                var existingHash = line["// Dataset: sha256:".Length..].Trim();
                return existingHash == currentHash;
            }
        }

        return false;
    }

    private static async Task<string> ComputeFileHashAsync(
        string path, CancellationToken cancellationToken)
    {
        using var stream = File.OpenRead(path);
        var hash = await SHA256.HashDataAsync(stream, cancellationToken);
        return Convert.ToHexStringLower(hash)[..16];
    }
}
