using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace LMP.Cli.Infrastructure;

/// <summary>
/// Generates <c>Generated/{Module}.Optimized.g.cs</c> files from optimized module state.
/// The generated file contains a <c>partial void ApplyOptimizedState()</c> implementation
/// that embeds the optimized instructions, demos, and config as a JSON string literal
/// and calls <c>LoadState()</c> on each predictor.
/// </summary>
internal static class CSharpArtifactWriter
{
    /// <summary>
    /// Writes a <c>.g.cs</c> file for the specified module with the optimized state.
    /// </summary>
    /// <param name="module">The optimized module.</param>
    /// <param name="outputDir">The output directory for the generated file.</param>
    /// <param name="score">The optimization score (for header comment).</param>
    /// <param name="optimizerName">The optimizer used (for header comment).</param>
    /// <param name="trainPath">Path to training data (for staleness hash).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The path to the generated file.</returns>
    public static async Task<string> WriteAsync(
        LmpModule module,
        string outputDir,
        float score,
        string optimizerName,
        string trainPath,
        CancellationToken cancellationToken)
    {
        var moduleType = module.GetType();
        var typeName = moduleType.Name;
        var ns = moduleType.Namespace ?? "";

        // Build the module state (same as SaveAsync)
        var state = new ModuleState
        {
            Version = "1.0",
            Module = typeName,
            Predictors = module.GetPredictors().ToDictionary(
                p => p.Name,
                p => p.Predictor.GetState())
        };

        // Serialize to JSON string for embedding
        var stateJson = JsonSerializer.Serialize(
            state,
            ModuleStateSerializerContext.Default.ModuleState);

        // Escape for C# raw string literal (triple-quote safe)
        // Raw string literals handle most escaping, but we need to ensure
        // no triple-quote sequences exist in the JSON
        var safeJson = stateJson.Replace("\"\"\"", "\\\"\\\"\\\"");

        // Compute staleness hashes
        var trainHash = File.Exists(trainPath)
            ? await ComputeFileHashAsync(trainPath, cancellationToken)
            : "unknown";

        // Generate the C# source
        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// LMP Auto-Optimize | Score: {score:F4} | Strategy: {optimizerName}");
        sb.AppendLine($"// Dataset: sha256:{trainHash}");
        sb.AppendLine($"// Generated: {DateTime.UtcNow:O}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ").AppendLine(typeName);
        sb.AppendLine("{");
        sb.AppendLine("    partial void ApplyOptimizedState()");
        sb.AppendLine("    {");
        sb.AppendLine("        var json = \"\"\"");
        sb.AppendLine($"            {safeJson}");
        sb.AppendLine("            \"\"\"u8;");
        sb.AppendLine();
        sb.AppendLine("        var state = System.Text.Json.JsonSerializer.Deserialize(");
        sb.AppendLine("            json,");
        sb.AppendLine("            global::LMP.ModuleStateSerializerContext.Default.ModuleState)!;");
        sb.AppendLine();
        sb.AppendLine("        foreach (var (name, predictor) in GetPredictors())");
        sb.AppendLine("        {");
        sb.AppendLine("            if (state.Predictors.TryGetValue(name, out var ps))");
        sb.AppendLine("                predictor.LoadState(ps);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        // Write to output directory
        Directory.CreateDirectory(outputDir);

        var outputPath = Path.Combine(outputDir, $"{typeName}.Optimized.g.cs");

        // Atomic write
        var tempPath = outputPath + ".tmp";
        await File.WriteAllTextAsync(tempPath, sb.ToString(), Encoding.UTF8, cancellationToken);
        File.Move(tempPath, outputPath, overwrite: true);

        return outputPath;
    }

    /// <summary>
    /// Checks if an existing generated file is still fresh based on dataset hash.
    /// Returns true if the file exists and its dataset hash matches the current training data.
    /// </summary>
    public static async Task<bool> IsUpToDateAsync(
        string generatedPath,
        string trainPath,
        CancellationToken cancellationToken)
    {
        if (!File.Exists(generatedPath) || !File.Exists(trainPath))
            return false;

        var currentHash = await ComputeFileHashAsync(trainPath, cancellationToken);

        // Read header lines to find dataset hash
        using var reader = new StreamReader(generatedPath);
        for (int i = 0; i < 10; i++)
        {
            var line = await reader.ReadLineAsync(cancellationToken);
            if (line is null)
                break;

            if (line.StartsWith("// Dataset: sha256:"))
            {
                var existingHash = line["// Dataset: sha256:".Length..].Trim();
                return existingHash == currentHash;
            }
        }

        return false;
    }

    private static async Task<string> ComputeFileHashAsync(
        string path, CancellationToken cancellationToken)
    {
        using var stream = File.OpenRead(path);
        var hash = await SHA256.HashDataAsync(stream, cancellationToken);
        return Convert.ToHexStringLower(hash)[..16]; // first 16 hex chars
    }
}
