using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace LMP.SourceGen.Tests;

/// <summary>
/// Tests for Phase 3.1 — ChainOfThought extended output emission.
/// Tests <see cref="ChainOfThoughtEmitter"/> directly and via the full generator pipeline.
/// </summary>
public class ChainOfThoughtEmitterTests
{
    #region Direct emitter tests — ChainOfThoughtEmitter.GenerateSource

    [Fact]
    public void GenerateSource_IncludesAutoGeneratedHeader()
    {
        var model = CreateModel();
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.StartsWith("// <auto-generated />", source);
        Assert.Contains("#nullable enable", source);
    }

    [Fact]
    public void GenerateSource_IncludesRequiredUsings()
    {
        var model = CreateModel();
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("using System.CodeDom.Compiler;", source);
        Assert.Contains("using System.ComponentModel;", source);
        Assert.Contains("using System.Text.Json.Serialization;", source);
    }

    [Fact]
    public void GenerateSource_IncludesNamespace()
    {
        var model = CreateModel(ns: "Demo.App");
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("namespace Demo.App;", source);
    }

    [Fact]
    public void GenerateSource_OmitsNamespace_WhenGlobal()
    {
        var model = CreateModel(ns: "");
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.DoesNotContain("namespace", source);
    }

    [Fact]
    public void GenerateSource_IncludesGeneratedCodeAttribute()
    {
        var model = CreateModel();
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]", source);
    }

    [Fact]
    public void GenerateSource_EmitsInternalPartialRecord()
    {
        var model = CreateModel(typeName: "ClassifyTicket");
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("internal partial record ClassifyTicketWithReasoning", source);
    }

    [Fact]
    public void GenerateSource_IncludesReasoningField()
    {
        var model = CreateModel();
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("public required string Reasoning { get; init; }", source);
    }

    [Fact]
    public void GenerateSource_ReasoningHasDescriptionAttribute()
    {
        var model = CreateModel();
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("[Description(\"Think step by step to work toward the answer\")]", source);
    }

    [Fact]
    public void GenerateSource_ReasoningHasJsonPropertyOrderMinusOne()
    {
        var model = CreateModel();
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("[JsonPropertyOrder(-1)]", source);
    }

    [Fact]
    public void GenerateSource_CopiesOutputFields()
    {
        var model = CreateModel();
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("public required string Category { get; init; }", source);
        Assert.Contains("public required int Urgency { get; init; }", source);
    }

    [Fact]
    public void GenerateSource_CopiesFieldDescriptions()
    {
        var model = CreateModel();
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("[Description(\"Category: billing, technical, account\")]", source);
        Assert.Contains("[Description(\"Urgency from 1 (low) to 5 (critical)\")]", source);
    }

    [Fact]
    public void GenerateSource_OmitsDescription_WhenNull()
    {
        var fields = new[]
        {
            new OutputFieldModel("Value", "string", "global::System.String", null, true, false,
                LocationInfo.From(Location.None)),
        };
        var model = new ChainOfThoughtModel("TestApp", "SimpleOutput",
            new EquatableArray<OutputFieldModel>(fields.ToImmutableArray()));

        var source = ChainOfThoughtEmitter.GenerateSource(model);

        // Only the Reasoning field should have a description
        var descriptionCount = source.Split("[Description(").Length - 1;
        Assert.Equal(1, descriptionCount); // Only Reasoning's description
    }

    [Fact]
    public void GenerateSource_EmitsJsonContext()
    {
        var model = CreateModel(typeName: "ClassifyTicket");
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("internal static class ClassifyTicketWithReasoningJsonOptions", source);
        Assert.Contains("JsonSerializerOptions Instance", source);
    }

    [Fact]
    public void GenerateSource_IncludesXmlDocComment()
    {
        var model = CreateModel();
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("/// Extended output type for ChainOfThought reasoning.", source);
    }

    [Fact]
    public void GenerateSource_EscapesDescriptionStrings()
    {
        var fields = new[]
        {
            new OutputFieldModel("Value", "string", "global::System.String",
                "Contains \"quotes\" and \\backslash", true, false,
                LocationInfo.From(Location.None)),
        };
        var model = new ChainOfThoughtModel("TestApp", "EscapeTest",
            new EquatableArray<OutputFieldModel>(fields.ToImmutableArray()));

        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("Contains \\\"quotes\\\" and \\\\backslash", source);
    }

    [Fact]
    public void GenerateSource_NonRequiredFields_OmitRequired()
    {
        var fields = new[]
        {
            new OutputFieldModel("Optional", "string", "global::System.String",
                "An optional field", false, false, LocationInfo.From(Location.None)),
        };
        var model = new ChainOfThoughtModel("TestApp", "OptionalOutput",
            new EquatableArray<OutputFieldModel>(fields.ToImmutableArray()));

        var source = ChainOfThoughtEmitter.GenerateSource(model);

        Assert.Contains("public string Optional { get; init; }", source);
        Assert.DoesNotContain("public required string Optional", source);
    }

    [Fact]
    public void GenerateSource_Snapshot_FullOutput()
    {
        var model = CreateModel(ns: "Demo", typeName: "ClassifyTicket");
        var source = ChainOfThoughtEmitter.GenerateSource(model);

        // Verify structure ordering: header → namespace → doc → record → JsonContext
        var nsIndex = source.IndexOf("namespace Demo;");
        var recordIndex = source.IndexOf("internal partial record ClassifyTicketWithReasoning");
        var reasoningIndex = source.IndexOf("public required string Reasoning");
        var categoryIndex = source.IndexOf("public required string Category");
        var urgencyIndex = source.IndexOf("public required int Urgency");
        var jsonCtxIndex = source.IndexOf("ClassifyTicketWithReasoningJsonOptions");

        Assert.True(nsIndex < recordIndex, "namespace before record");
        Assert.True(recordIndex < reasoningIndex, "record before Reasoning field");
        Assert.True(reasoningIndex < categoryIndex, "Reasoning before Category");
        Assert.True(categoryIndex < urgencyIndex, "Category before Urgency");
        Assert.True(urgencyIndex < jsonCtxIndex, "Urgency before JsonContext");
    }

    #endregion

    #region Pipeline integration tests

    [Fact]
    public void Pipeline_ChainOfThoughtUsage_EmitsExtendedOutput()
    {
        var source = GetCoTPipelineSource();
        var (diagnostics, runResult) = RunGenerator(source);

        // Should not have errors (warnings ok)
        Assert.DoesNotContain(diagnostics, d => d.Severity == DiagnosticSeverity.Error);

        var cotFile = runResult.Results[0].GeneratedSources
            .FirstOrDefault(s => s.HintName == "ClassifyTicket.ChainOfThought.g.cs");
        Assert.True(cotFile.HintName is not null,
            "Expected ClassifyTicket.ChainOfThought.g.cs to be generated");
    }

    [Fact]
    public void Pipeline_EmittedRecord_ContainsReasoningAndOutputFields()
    {
        var source = GetCoTPipelineSource();
        var (_, runResult) = RunGenerator(source);

        var cotFile = runResult.Results[0].GeneratedSources
            .First(s => s.HintName == "ClassifyTicket.ChainOfThought.g.cs");
        var generatedSource = cotFile.SourceText.ToString();

        Assert.Contains("internal partial record ClassifyTicketWithReasoning", generatedSource);
        Assert.Contains("public required string Reasoning { get; init; }", generatedSource);
        Assert.Contains("Category", generatedSource);
        Assert.Contains("Urgency", generatedSource);
    }

    [Fact]
    public void Pipeline_EmittedJsonContext_IsPresent()
    {
        var source = GetCoTPipelineSource();
        var (_, runResult) = RunGenerator(source);

        var cotFile = runResult.Results[0].GeneratedSources
            .First(s => s.HintName == "ClassifyTicket.ChainOfThought.g.cs");
        var generatedSource = cotFile.SourceText.ToString();

        Assert.Contains("ClassifyTicketWithReasoningJsonOptions", generatedSource);
        Assert.Contains("JsonSerializerOptions", generatedSource);
    }

    [Fact]
    public void Pipeline_NoChainOfThoughtUsage_NoCoTEmitted()
    {
        var source = """
            namespace LMP
            {
                public class Predictor<TInput, TOutput> where TOutput : class
                {
                    public Predictor(object client) { }
                }
            }
            namespace LMP
            {
                public class ChainOfThought<TInput, TOutput> : Predictor<TInput, TOutput> where TOutput : class
                {
                    public ChainOfThought(object client) : base(client) { }
                }
            }

            namespace TestApp
            {
                using LMP;

                // Using Predictor, not ChainOfThought
                public partial class MyModule
                {
                    private readonly Predictor<string, string> _predict = null!;
                }
            }
            """;

        var (_, runResult) = RunGenerator(source);

        Assert.DoesNotContain(runResult.Results[0].GeneratedSources,
            s => s.HintName.Contains("ChainOfThought.g.cs"));
    }

    [Fact]
    public void Pipeline_OutputWithoutLmpSignature_NoCoTEmitted()
    {
        var source = """
            namespace LMP
            {
                public class Predictor<TInput, TOutput> where TOutput : class
                {
                    public Predictor(object client) { }
                }
            }
            namespace LMP
            {
                public class ChainOfThought<TInput, TOutput> : Predictor<TInput, TOutput> where TOutput : class
                {
                    public ChainOfThought(object client) : base(client) { }
                }
            }

            namespace TestApp
            {
                using LMP;

                // No [LmpSignature] on output type
                public partial record PlainOutput
                {
                    public required string Value { get; init; }
                }

                public partial class MyModule
                {
                    private readonly ChainOfThought<string, PlainOutput> _cot = null!;
                }
            }
            """;

        var (_, runResult) = RunGenerator(source);

        Assert.DoesNotContain(runResult.Results[0].GeneratedSources,
            s => s.HintName.Contains("ChainOfThought.g.cs"));
    }

    [Fact]
    public void Pipeline_DuplicateCoTUsages_DeduplicatedByOutputType()
    {
        var source = """
            namespace LMP
            {
                [System.AttributeUsage(System.AttributeTargets.Class)]
                public sealed class LmpSignatureAttribute : System.Attribute
                {
                    public LmpSignatureAttribute(string instructions) { }
                }
                public class Predictor<TInput, TOutput> where TOutput : class
                {
                    public Predictor(object client) { }
                }
            }
            namespace LMP
            {
                public class ChainOfThought<TInput, TOutput> : Predictor<TInput, TOutput> where TOutput : class
                {
                    public ChainOfThought(object client) : base(client) { }
                }
            }

            namespace TestApp
            {
                using LMP;
                using System.ComponentModel;

                public record Input1(string Text);
                public record Input2(string Value);

                [LmpSignature("Classify")]
                public partial record ClassifyTicket
                {
                    [Description("Category")]
                    public required string Category { get; init; }
                }

                public partial class Module1
                {
                    private readonly ChainOfThought<Input1, ClassifyTicket> _cot1 = null!;
                }
                public partial class Module2
                {
                    private readonly ChainOfThought<Input2, ClassifyTicket> _cot2 = null!;
                }
            }
            """;

        var (_, runResult) = RunGenerator(source);

        var cotFiles = runResult.Results[0].GeneratedSources
            .Where(s => s.HintName.Contains("ChainOfThought.g.cs"))
            .ToList();

        // Should deduplicate — same TOut means only one file
        Assert.Single(cotFiles);
        Assert.Equal("ClassifyTicket.ChainOfThought.g.cs", cotFiles[0].HintName);
    }

    [Fact]
    public void Pipeline_HintName_FollowsConvention()
    {
        var source = GetCoTPipelineSource();
        var (_, runResult) = RunGenerator(source);

        Assert.Contains(runResult.Results[0].GeneratedSources,
            s => s.HintName == "ClassifyTicket.ChainOfThought.g.cs");
    }

    [Fact]
    public void Pipeline_GeneratedCodeIsValidCSharp()
    {
        var source = GetCoTPipelineSource();
        var (_, runResult) = RunGenerator(source);

        var cotFile = runResult.Results[0].GeneratedSources
            .First(s => s.HintName == "ClassifyTicket.ChainOfThought.g.cs");
        var generatedSource = cotFile.SourceText.ToString();

        // Parse and check for syntax errors
        var tree = CSharpSyntaxTree.ParseText(generatedSource);
        var parseDiags = tree.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error);
        Assert.Empty(parseDiags);
    }

    #endregion

    #region Model tests

    [Fact]
    public void ChainOfThoughtModel_Equality_SameFields()
    {
        var fields = new[]
        {
            new OutputFieldModel("Value", "string", "global::System.String", "desc", true, false,
                LocationInfo.From(Location.None)),
        };
        var model1 = new ChainOfThoughtModel("NS", "Type",
            new EquatableArray<OutputFieldModel>(fields.ToImmutableArray()));
        var model2 = new ChainOfThoughtModel("NS", "Type",
            new EquatableArray<OutputFieldModel>(fields.ToImmutableArray()));

        Assert.Equal(model1, model2);
    }

    [Fact]
    public void ChainOfThoughtModel_Inequality_DifferentTypeName()
    {
        var model1 = new ChainOfThoughtModel("NS", "TypeA", default);
        var model2 = new ChainOfThoughtModel("NS", "TypeB", default);

        Assert.NotEqual(model1, model2);
    }

    #endregion

    #region Helpers

    private static ChainOfThoughtModel CreateModel(
        string ns = "TestApp",
        string typeName = "ClassifyTicket")
    {
        var fields = new[]
        {
            new OutputFieldModel("Category", "string", "global::System.String",
                "Category: billing, technical, account", true, false,
                LocationInfo.From(Location.None)),
            new OutputFieldModel("Urgency", "int", "global::System.Int32",
                "Urgency from 1 (low) to 5 (critical)", true, false,
                LocationInfo.From(Location.None)),
        };

        return new ChainOfThoughtModel(
            Namespace: ns,
            OutputTypeName: typeName,
            OutputFields: new EquatableArray<OutputFieldModel>(fields.ToImmutableArray()));
    }

    private static string GetCoTPipelineSource() => """
        namespace LMP
        {
            [System.AttributeUsage(System.AttributeTargets.Class)]
            public sealed class LmpSignatureAttribute : System.Attribute
            {
                public LmpSignatureAttribute(string instructions) { }
            }
            public class Predictor<TInput, TOutput> where TOutput : class
            {
                public Predictor(object client) { }
            }
        }
        namespace LMP
        {
            public class ChainOfThought<TInput, TOutput> : Predictor<TInput, TOutput> where TOutput : class
            {
                public ChainOfThought(object client) : base(client) { }
            }
        }

        namespace TestApp
        {
            using LMP;
            using System.ComponentModel;

            public record TicketInput(string TicketText);

            [LmpSignature("Classify a support ticket")]
            public partial record ClassifyTicket
            {
                [Description("Category: billing, technical, account")]
                public required string Category { get; init; }

                [Description("Urgency from 1 (low) to 5 (critical)")]
                public required int Urgency { get; init; }
            }

            public partial class MyModule
            {
                private readonly ChainOfThought<TicketInput, ClassifyTicket> _cot;

                public MyModule(object client)
                {
                    _cot = new ChainOfThought<TicketInput, ClassifyTicket>(client);
                }
            }
        }
        """;

    private static (ImmutableArray<Diagnostic> Diagnostics, GeneratorDriverRunResult RunResult) RunGenerator(
        string source)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        var references = new[]
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(System.ComponentModel.DescriptionAttribute).Assembly.Location),
        };

        // Also need System.Runtime for fundamental types
        var runtimePath = System.IO.Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        var runtimeRef = MetadataReference.CreateFromFile(
            System.IO.Path.Combine(runtimePath, "System.Runtime.dll"));

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { syntaxTree },
            references.Append(runtimeRef),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new LmpSourceGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);

        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation, out var outputCompilation, out var diagnostics);

        var runResult = driver.GetRunResult();
        return (diagnostics, runResult);
    }

    #endregion
}
