using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace LMP.SourceGen.Tests;

/// <summary>
/// Tests for C# 14 interceptor emission — Pipeline 5.
/// Tests the <see cref="InterceptorEmitter"/> directly with constructed models
/// and the <see cref="InterceptorExtractor"/> via the full generator pipeline.
/// </summary>
public class InterceptorEmitterTests
{
    #region Direct emitter tests — InterceptorEmitter.GenerateSource

    [Fact]
    public void GenerateSource_ReturnsEmpty_WhenNoCallSites()
    {
        var result = InterceptorEmitter.GenerateSource(ImmutableArray<InterceptorCallSiteModel>.Empty);
        Assert.Empty(result);
    }

    [Fact]
    public void GenerateSource_ReturnsEmpty_WhenDefaultArray()
    {
        var result = InterceptorEmitter.GenerateSource(default);
        Assert.Empty(result);
    }

    [Fact]
    public void GenerateSource_IncludesAutoGeneratedHeader()
    {
        var sites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(sites);

        Assert.StartsWith("// <auto-generated />", source);
        Assert.Contains("#nullable enable", source);
    }

    [Fact]
    public void GenerateSource_IncludesRequiredUsings()
    {
        var sites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(sites);

        Assert.Contains("using System;", source);
        Assert.Contains("using System.Threading;", source);
        Assert.Contains("using System.Threading.Tasks;", source);
        Assert.Contains("using Microsoft.Extensions.AI;", source);
    }

    [Fact]
    public void GenerateSource_EmitsFileLocalInterceptsLocationAttribute()
    {
        var sites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(sites);

        Assert.Contains("namespace System.Runtime.CompilerServices", source);
        Assert.Contains("[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]", source);
        Assert.Contains("file sealed class InterceptsLocationAttribute(int version, string data) : Attribute;", source);
    }

    [Fact]
    public void GenerateSource_EmitsFileStaticInterceptorClass()
    {
        var sites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(sites);

        Assert.Contains("namespace LMP.Generated", source);
        Assert.Contains("file static class LmpInterceptors", source);
    }

    [Fact]
    public void GenerateSource_EmitsInterceptsLocationAttribute_WithVersionAndData()
    {
        var sites = ImmutableArray.Create(
            new InterceptorCallSiteModel(
                InputTypeFQN: "global::TestApp.TicketInput",
                OutputTypeFQN: "global::TestApp.ClassifyTicket",
                OutputTypeName: "ClassifyTicket",
                Namespace: "TestApp",
                LocationVersion: 1,
                LocationData: "abc123data",
                DisplayLocation: "test.cs(10,15)"));

        var source = InterceptorEmitter.GenerateSource(sites);

        Assert.Contains("[InterceptsLocation(1, \"abc123data\")]", source);
        Assert.Contains("// test.cs(10,15)", source);
    }

    [Fact]
    public void GenerateSource_EmitsExtensionMethod_MatchingPredictAsyncSignature()
    {
        var sites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(sites);

        Assert.Contains("public static async Task<global::TestApp.ClassifyTicket> PredictAsync_0(", source);
        Assert.Contains("this global::LMP.Predictor<global::TestApp.TicketInput, global::TestApp.ClassifyTicket> self,", source);
        Assert.Contains("global::TestApp.TicketInput input,", source);
        Assert.Contains("global::LMP.Trace? trace = null,", source);
        Assert.Contains("Action<global::TestApp.ClassifyTicket>? validate = null,", source);
        Assert.Contains("int maxRetries = 3,", source);
        Assert.Contains("CancellationToken cancellationToken = default)", source);
    }

    [Fact]
    public void GenerateSource_WiresPromptBuilder_BeforeDelegating()
    {
        var sites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(sites);

        Assert.Contains("self.SetPromptBuilder(global::TestApp.ClassifyTicketPromptBuilder.BuildMessages);", source);
        Assert.Contains("return await self.PredictAsync(input, trace, validate, maxRetries, cancellationToken).ConfigureAwait(false);", source);

        // SetPromptBuilder must come before PredictAsync delegation
        var wireIdx = source.IndexOf("SetPromptBuilder");
        var delegateIdx = source.IndexOf("return await self.PredictAsync");
        Assert.True(wireIdx < delegateIdx, "SetPromptBuilder should be called before delegating to PredictAsync");
    }

    [Fact]
    public void GenerateSource_GroupsCallSites_BySameTypeParameters()
    {
        var sites = ImmutableArray.Create(
            new InterceptorCallSiteModel(
                InputTypeFQN: "global::TestApp.TicketInput",
                OutputTypeFQN: "global::TestApp.ClassifyTicket",
                OutputTypeName: "ClassifyTicket",
                Namespace: "TestApp",
                LocationVersion: 1,
                LocationData: "site1data",
                DisplayLocation: "file1.cs(5,10)"),
            new InterceptorCallSiteModel(
                InputTypeFQN: "global::TestApp.TicketInput",
                OutputTypeFQN: "global::TestApp.ClassifyTicket",
                OutputTypeName: "ClassifyTicket",
                Namespace: "TestApp",
                LocationVersion: 1,
                LocationData: "site2data",
                DisplayLocation: "file2.cs(15,20)"));

        var source = InterceptorEmitter.GenerateSource(sites);

        // Both call sites should share one interceptor method
        Assert.Contains("[InterceptsLocation(1, \"site1data\")]", source);
        Assert.Contains("[InterceptsLocation(1, \"site2data\")]", source);

        // Only one PredictAsync method should be emitted
        var methodCount = CountOccurrences(source, "public static async Task<");
        Assert.Equal(1, methodCount);
    }

    [Fact]
    public void GenerateSource_SeparateMethodsForDifferentTypes()
    {
        var sites = ImmutableArray.Create(
            new InterceptorCallSiteModel(
                InputTypeFQN: "global::TestApp.InputA",
                OutputTypeFQN: "global::TestApp.OutputA",
                OutputTypeName: "OutputA",
                Namespace: "TestApp",
                LocationVersion: 1,
                LocationData: "siteA",
                DisplayLocation: "a.cs(1,1)"),
            new InterceptorCallSiteModel(
                InputTypeFQN: "global::TestApp.InputB",
                OutputTypeFQN: "global::TestApp.OutputB",
                OutputTypeName: "OutputB",
                Namespace: "TestApp",
                LocationVersion: 1,
                LocationData: "siteB",
                DisplayLocation: "b.cs(2,2)"));

        var source = InterceptorEmitter.GenerateSource(sites);

        Assert.Contains("PredictAsync_0(", source);
        Assert.Contains("PredictAsync_1(", source);
        Assert.Contains("global::TestApp.OutputAPromptBuilder.BuildMessages", source);
        Assert.Contains("global::TestApp.OutputBPromptBuilder.BuildMessages", source);
    }

    [Fact]
    public void GenerateSource_GlobalNamespace_UsesGlobalPrefix()
    {
        var sites = ImmutableArray.Create(
            new InterceptorCallSiteModel(
                InputTypeFQN: "global::MyInput",
                OutputTypeFQN: "global::MyOutput",
                OutputTypeName: "MyOutput",
                Namespace: "",
                LocationVersion: 1,
                LocationData: "data1",
                DisplayLocation: "test.cs(1,1)"));

        var source = InterceptorEmitter.GenerateSource(sites);

        Assert.Contains("global::MyOutputPromptBuilder.BuildMessages", source);
    }

    [Fact]
    public void GenerateSource_IncludesGeneratedCodeAttribute()
    {
        var sites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(sites);

        Assert.Contains("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]", source);
    }

    #endregion

    #region Direct extractor tests — InterceptorExtractor.IsCandidate

    [Fact]
    public void IsCandidate_ReturnsFalse_ForNonInvocation()
    {
        var tree = CSharpSyntaxTree.ParseText("class C { int x; }");
        var root = tree.GetRoot();
        foreach (var node in root.DescendantNodes())
        {
            Assert.False(InterceptorExtractor.IsCandidate(node, default));
        }
    }

    [Fact]
    public void IsCandidate_ReturnsTrue_ForPredictAsyncInvocation()
    {
        var tree = CSharpSyntaxTree.ParseText("class C { void M() { x.PredictAsync(input); } }");
        var root = tree.GetRoot();
        var invocations = root.DescendantNodes()
            .Where(n => InterceptorExtractor.IsCandidate(n, default))
            .ToList();

        Assert.Single(invocations);
    }

    [Fact]
    public void IsCandidate_ReturnsFalse_ForOtherMethodCalls()
    {
        var tree = CSharpSyntaxTree.ParseText("class C { void M() { x.SomeOther(input); } }");
        var root = tree.GetRoot();
        var candidates = root.DescendantNodes()
            .Where(n => InterceptorExtractor.IsCandidate(n, default))
            .ToList();

        Assert.Empty(candidates);
    }

    [Fact]
    public void IsCandidate_ReturnsFalse_ForStaticPredictAsyncCall()
    {
        var tree = CSharpSyntaxTree.ParseText("class C { void M() { PredictAsync(input); } }");
        var root = tree.GetRoot();
        var candidates = root.DescendantNodes()
            .Where(n => InterceptorExtractor.IsCandidate(n, default))
            .ToList();

        // Static calls without member access should not match
        Assert.Empty(candidates);
    }

    #endregion

    #region PromptBuilder 4-param overload

    [Fact]
    public void PromptBuilder_EmitsBuildMessages_4ParamOverload()
    {
        var model = CreatePromptBuilderModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("public static IList<ChatMessage> BuildMessages(", source);
        Assert.Contains("string instructions,", source);
        Assert.Contains("string? lastError)", source);
    }

    [Fact]
    public void PromptBuilder_4ParamOverload_HandlesLastError()
    {
        var model = CreatePromptBuilderModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("if (lastError is not null)", source);
        Assert.Contains("Previous attempt failed:", source);
    }

    [Fact]
    public void PromptBuilder_2ParamOverload_DelegatesTo4Param()
    {
        var model = CreatePromptBuilderModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("return BuildMessages(Instructions, input, demos, null);", source);
    }

    #endregion

    #region Helpers

    private static ImmutableArray<InterceptorCallSiteModel> CreateSingleCallSite()
    {
        return ImmutableArray.Create(
            new InterceptorCallSiteModel(
                InputTypeFQN: "global::TestApp.TicketInput",
                OutputTypeFQN: "global::TestApp.ClassifyTicket",
                OutputTypeName: "ClassifyTicket",
                Namespace: "TestApp",
                LocationVersion: 1,
                LocationData: "testlocationdata",
                DisplayLocation: "test.cs(5,20)"));
    }

    private static PromptBuilderModel CreatePromptBuilderModel()
    {
        return new PromptBuilderModel(
            Namespace: "TestApp",
            OutputTypeName: "ClassifyTicket",
            InputTypeName: "TicketInput",
            InputTypeFullyQualified: "global::TestApp.TicketInput",
            OutputTypeFullyQualified: "global::TestApp.ClassifyTicket",
            Instructions: "Classify tickets",
            InputFields: new EquatableArray<InputFieldModel>(
                ImmutableArray.Create(new InputFieldModel("Text", "string", "The text"))),
            OutputFields: new EquatableArray<OutputFieldModel>(
                ImmutableArray.Create(new OutputFieldModel(
                    "Category", "string", "global::System.String", "The category",
                    IsRequired: false, IsNonSerializable: false, Location: default))));
    }

    private static int CountOccurrences(string source, string substring)
    {
        int count = 0;
        int idx = 0;
        while ((idx = source.IndexOf(substring, idx)) != -1)
        {
            count++;
            idx += substring.Length;
        }
        return count;
    }

    #endregion
}
