using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace LMP.SourceGen.Tests;

/// <summary>
/// Tests for Phase 8 — C# 14 interceptors for zero-dispatch PredictAsync optimization.
/// Tests the <see cref="InterceptorEmitter"/> directly with manually constructed models
/// and via the full generator pipeline with PredictAsync call site discovery.
/// </summary>
public class InterceptorTests
{
    #region InterceptorEmitter — Direct emission tests

    [Fact]
    public void GenerateSource_ReturnsEmpty_WhenNoCallSites()
    {
        var source = InterceptorEmitter.GenerateSource(ImmutableArray<InterceptorCallSiteModel>.Empty);

        Assert.Equal(string.Empty, source);
    }

    [Fact]
    public void GenerateSource_ReturnsEmpty_WhenDefaultArray()
    {
        var source = InterceptorEmitter.GenerateSource(default);

        Assert.Equal(string.Empty, source);
    }

    [Fact]
    public void GenerateSource_IncludesAutoGeneratedHeader()
    {
        var callSites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.StartsWith("// <auto-generated />", source);
        Assert.Contains("#nullable enable", source);
    }

    [Fact]
    public void GenerateSource_IncludesRequiredUsings()
    {
        var callSites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("using System;", source);
        Assert.Contains("using System.Runtime.CompilerServices;", source);
        Assert.Contains("using System.Threading;", source);
        Assert.Contains("using System.Threading.Tasks;", source);
        Assert.Contains("using Microsoft.Extensions.AI;", source);
    }

    [Fact]
    public void GenerateSource_EmitsFileLocalInterceptsLocationAttribute()
    {
        var callSites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("namespace System.Runtime.CompilerServices", source);
        Assert.Contains("file sealed class InterceptsLocationAttribute(int version, string data) : Attribute;", source);
    }

    [Fact]
    public void GenerateSource_EmitsInterceptorInLmpGeneratedNamespace()
    {
        var callSites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("namespace LMP.Generated", source);
        Assert.Contains("file static class LmpInterceptors", source);
    }

    [Fact]
    public void GenerateSource_EmitsInterceptsLocationAttribute()
    {
        var callSites = CreateSingleCallSite(version: 1, data: "ABCDEF123456");
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("[InterceptsLocation(1, \"ABCDEF123456\")]", source);
    }

    [Fact]
    public void GenerateSource_EmitsDisplayLocationComment()
    {
        var callSites = CreateSingleCallSite(displayLocation: "Program.cs(10,15)");
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("// Program.cs(10,15)", source);
    }

    [Fact]
    public void GenerateSource_EmitsCorrectMethodSignature()
    {
        var callSites = CreateSingleCallSite(
            inputTypeFqn: "global::TestApp.TicketInput",
            outputTypeFqn: "global::TestApp.ClassifyTicket");
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("public static async Task<global::TestApp.ClassifyTicket> PredictAsync_0(", source);
        Assert.Contains("this global::LMP.Predictor<global::TestApp.TicketInput, global::TestApp.ClassifyTicket> self,", source);
        Assert.Contains("global::TestApp.TicketInput input,", source);
        Assert.Contains("global::LMP.Trace? trace = null,", source);
        Assert.Contains("Action<global::TestApp.ClassifyTicket>? validate = null,", source);
        Assert.Contains("int maxRetries = 3,", source);
        Assert.Contains("CancellationToken cancellationToken = default)", source);
    }

    [Fact]
    public void GenerateSource_EmitsDerivedTypeGuard()
    {
        var callSites = CreateSingleCallSite(
            inputTypeFqn: "global::TestApp.TicketInput",
            outputTypeFqn: "global::TestApp.ClassifyTicket");
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("if (self.GetType() != typeof(global::LMP.Predictor<global::TestApp.TicketInput, global::TestApp.ClassifyTicket>))", source);
        Assert.Contains("return await self.PredictAsync(input, trace, validate, maxRetries, cancellationToken).ConfigureAwait(false);", source);
    }

    [Fact]
    public void GenerateSource_EmitsPromptBuilderCall()
    {
        var callSites = CreateSingleCallSite(
            outputTypeName: "ClassifyTicket",
            ns: "TestApp");
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("global::TestApp.ClassifyTicketPromptBuilder.DefaultInstructions", source);
        Assert.Contains("global::TestApp.ClassifyTicketPromptBuilder.BuildMessages(effectiveInstructions, input, self.Demos, lastError)", source);
    }

    [Fact]
    public void GenerateSource_EmitsPromptBuilderCall_GlobalNamespace()
    {
        var callSites = CreateSingleCallSite(
            outputTypeName: "ClassifyTicket",
            ns: "");
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("global::ClassifyTicketPromptBuilder.DefaultInstructions", source);
        Assert.Contains("global::ClassifyTicketPromptBuilder.BuildMessages(effectiveInstructions, input, self.Demos, lastError)", source);
    }

    [Fact]
    public void GenerateSource_EmitsDirectClientCall()
    {
        var callSites = CreateSingleCallSite(outputTypeFqn: "global::TestApp.ClassifyTicket");
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("self.Client.GetResponseAsync<global::TestApp.ClassifyTicket>(messages, self.Config, cancellationToken: cancellationToken)", source);
    }

    [Fact]
    public void GenerateSource_EmitsTraceRecording()
    {
        var callSites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("trace?.Record(self.Name, input!, result);", source);
    }

    [Fact]
    public void GenerateSource_EmitsRetryLoop()
    {
        var callSites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("string? lastError = null;", source);
        Assert.Contains("for (int attempt = 0; attempt <= maxRetries; attempt++)", source);
        Assert.Contains("catch (global::LMP.LmpAssertionException ex)", source);
        Assert.Contains("lastError = ex.Message;", source);
        Assert.Contains("throw new global::LMP.LmpMaxRetriesExceededException(self.Name, maxRetries);", source);
    }

    [Fact]
    public void GenerateSource_EmitsNullOutputCheck()
    {
        var callSites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("response.Result", source);
        Assert.Contains("structured output returned null", source);
    }

    [Fact]
    public void GenerateSource_GroupsCallSitesByTypePair()
    {
        var callSites = ImmutableArray.Create(
            CreateCallSite("global::T.In1", "global::T.Out1", "Out1", "T", 1, "AAA", "file1.cs(1,1)"),
            CreateCallSite("global::T.In1", "global::T.Out1", "Out1", "T", 1, "BBB", "file2.cs(5,5)"),
            CreateCallSite("global::T.In2", "global::T.Out2", "Out2", "T", 1, "CCC", "file3.cs(10,1)"));
        var source = InterceptorEmitter.GenerateSource(callSites);

        // Two [InterceptsLocation] for first type pair, one for second
        Assert.Contains("[InterceptsLocation(1, \"AAA\")]", source);
        Assert.Contains("[InterceptsLocation(1, \"BBB\")]", source);
        Assert.Contains("[InterceptsLocation(1, \"CCC\")]", source);
        Assert.Contains("PredictAsync_0(", source);
        Assert.Contains("PredictAsync_1(", source);
    }

    [Fact]
    public void GenerateSource_MultipleCallSites_SingleMethod_MultipleAttributes()
    {
        var callSites = ImmutableArray.Create(
            CreateCallSite("global::T.In", "global::T.Out", "Out", "T", 1, "LOC1", "a.cs(1,1)"),
            CreateCallSite("global::T.In", "global::T.Out", "Out", "T", 1, "LOC2", "b.cs(2,2)"));
        var source = InterceptorEmitter.GenerateSource(callSites);

        // Both attributes on same method
        var methodIdx = source.IndexOf("PredictAsync_0(");
        var loc1Idx = source.IndexOf("[InterceptsLocation(1, \"LOC1\")]");
        var loc2Idx = source.IndexOf("[InterceptsLocation(1, \"LOC2\")]");

        Assert.True(loc1Idx < methodIdx, "First [InterceptsLocation] should precede method");
        Assert.True(loc2Idx < methodIdx, "Second [InterceptsLocation] should precede method");

        // Only one method emitted
        Assert.DoesNotContain("PredictAsync_1(", source);
    }

    [Fact]
    public void GenerateSource_ProducesSyntacticallyValidCSharp()
    {
        var callSites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(callSites);

        var tree = CSharpSyntaxTree.ParseText(source);
        var syntaxDiagnostics = tree.GetDiagnostics().ToArray();

        Assert.Empty(syntaxDiagnostics);
    }

    [Fact]
    public void GenerateSource_EmitsEffectiveInstructionsLogic()
    {
        var callSites = CreateSingleCallSite();
        var source = InterceptorEmitter.GenerateSource(callSites);

        Assert.Contains("string.IsNullOrEmpty(self.Instructions)", source);
        Assert.Contains("DefaultInstructions", source);
    }

    #endregion

    #region InterceptorExtractor — Syntax predicate tests

    [Fact]
    public void IsCandidate_ReturnsTrueForPredictAsyncInvocation()
    {
        var code = "var x = predictor.PredictAsync(input);";
        var tree = CSharpSyntaxTree.ParseText(code);
        var root = tree.GetRoot();
        var invocation = root.DescendantNodes()
            .OfType<Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax>()
            .First();

        Assert.True(InterceptorExtractor.IsCandidate(invocation, default));
    }

    [Fact]
    public void IsCandidate_ReturnsFalseForOtherMethods()
    {
        var code = "var x = predictor.ForwardAsync(input);";
        var tree = CSharpSyntaxTree.ParseText(code);
        var root = tree.GetRoot();
        var invocation = root.DescendantNodes()
            .OfType<Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax>()
            .First();

        Assert.False(InterceptorExtractor.IsCandidate(invocation, default));
    }

    [Fact]
    public void IsCandidate_ReturnsFalseForNonMemberAccess()
    {
        var code = "var x = PredictAsync(input);";
        var tree = CSharpSyntaxTree.ParseText(code);
        var root = tree.GetRoot();
        var invocation = root.DescendantNodes()
            .OfType<Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax>()
            .First();

        Assert.False(InterceptorExtractor.IsCandidate(invocation, default));
    }

    #endregion

    #region Pipeline integration tests

    [Fact]
    public void Pipeline_EmitsInterceptor_ForValidPredictAsyncCall()
    {
        var source = GetInterceptorPipelineSource();
        var (diagnostics, runResult) = RunGenerator(source);

        Assert.Empty(diagnostics);

        var interceptorFile = runResult.Results[0].GeneratedSources
            .FirstOrDefault(s => s.HintName == "LmpInterceptors.g.cs");

        Assert.NotNull(interceptorFile.SourceText);
        var text = interceptorFile.SourceText!.ToString();

        Assert.Contains("file static class LmpInterceptors", text);
        Assert.Contains("InterceptsLocation(", text);
        Assert.Contains("PredictAsync_0(", text);
    }

    [Fact]
    public void Pipeline_InterceptorContainsInlinedLogic()
    {
        var source = GetInterceptorPipelineSource();
        var (_, runResult) = RunGenerator(source);

        var interceptorFile = runResult.Results[0].GeneratedSources
            .First(s => s.HintName == "LmpInterceptors.g.cs");
        var text = interceptorFile.SourceText!.ToString();

        // Verify zero-dispatch inlining: PromptBuilder call, client call, retry loop
        Assert.Contains("ClassifyTicketPromptBuilder.BuildMessages(", text);
        Assert.Contains("self.Client.GetResponseAsync<", text);
        Assert.Contains("for (int attempt = 0; attempt <= maxRetries; attempt++)", text);
        Assert.Contains("LmpAssertionException", text);
        Assert.Contains("LmpMaxRetriesExceededException", text);
    }

    [Fact]
    public void Pipeline_InterceptorContainsDerivedTypeGuard()
    {
        var source = GetInterceptorPipelineSource();
        var (_, runResult) = RunGenerator(source);

        var interceptorFile = runResult.Results[0].GeneratedSources
            .First(s => s.HintName == "LmpInterceptors.g.cs");
        var text = interceptorFile.SourceText!.ToString();

        Assert.Contains("self.GetType() != typeof(global::LMP.Predictor<", text);
    }

    [Fact]
    public void Pipeline_NoPredictAsyncCall_NoInterceptor()
    {
        var source = """
            using System.ComponentModel;
            using System.Threading.Tasks;

            namespace LMP
            {
                public class Predictor<TInput, TOutput> where TOutput : class
                {
                    public Predictor(object client) { }
                    public virtual Task<TOutput> PredictAsync(TInput input) => throw null!;
                }
            }

            namespace TestApp
            {
                using LMP;

                public record TicketInput(string TicketText);

                [LmpSignature("Classify tickets")]
                public partial record ClassifyTicket
                {
                    [Description("Category")]
                    public required string Category { get; init; }
                }

                public class MyModule
                {
                    private readonly Predictor<TicketInput, ClassifyTicket> _classify = null!;
                    // No PredictAsync call — should not emit interceptor
                }
            }
            """;

        var (_, runResult) = RunGenerator(source);

        Assert.DoesNotContain(runResult.Results[0].GeneratedSources,
            s => s.HintName == "LmpInterceptors.g.cs");
    }

    [Fact]
    public void Pipeline_MultiplePredictAsyncCalls_SameType_SingleMethod()
    {
        var source = """
            using System.ComponentModel;
            using System.Threading.Tasks;

            namespace LMP
            {
                public class Predictor<TInput, TOutput> where TOutput : class
                {
                    public Predictor(object client) { }
                    public virtual Task<TOutput> PredictAsync(TInput input) => throw null!;
                    public string Instructions { get; set; } = "";
                    public string Name { get; set; } = "";
                }
                public class Trace { public void Record(string n, object i, object o) {} }
                public class LmpAssertionException : System.Exception { }
                public class LmpMaxRetriesExceededException : System.Exception
                {
                    public LmpMaxRetriesExceededException(string n, int r) { }
                }
                public interface IChatClient { }
            }

            namespace TestApp
            {
                using LMP;

                public record Input1(string Text);

                [LmpSignature("Test")]
                public partial record Output1
                {
                    [Description("Result")]
                    public required string Result { get; init; }
                }

                public class MyModule
                {
                    private readonly Predictor<Input1, Output1> _a = null!;
                    private readonly Predictor<Input1, Output1> _b = null!;

                    public async Task Run()
                    {
                        var r1 = await _a.PredictAsync(new Input1("hello"));
                        var r2 = await _b.PredictAsync(new Input1("world"));
                    }
                }
            }
            """;

        var (diagnostics, runResult) = RunGenerator(source);
        Assert.Empty(diagnostics);

        var interceptor = runResult.Results[0].GeneratedSources
            .FirstOrDefault(s => s.HintName == "LmpInterceptors.g.cs");
        Assert.NotNull(interceptor.SourceText);

        var text = interceptor.SourceText!.ToString();

        // Two [InterceptsLocation] attributes on one method
        var attrCount = CountOccurrences(text, "[InterceptsLocation(");
        Assert.Equal(2, attrCount);

        // Only one method
        Assert.Contains("PredictAsync_0(", text);
        Assert.DoesNotContain("PredictAsync_1(", text);
    }

    [Fact]
    public void Pipeline_OutputTypeWithoutLmpSignature_NoInterceptor()
    {
        var source = """
            using System.Threading.Tasks;

            namespace LMP
            {
                public class Predictor<TInput, TOutput> where TOutput : class
                {
                    public Predictor(object client) { }
                    public virtual Task<TOutput> PredictAsync(TInput input) => throw null!;
                }
            }

            namespace TestApp
            {
                using LMP;

                public record Input1(string Text);
                public record Output1 { public required string Value { get; init; } }

                public class MyModule
                {
                    private readonly Predictor<Input1, Output1> _p = null!;

                    public async Task Run()
                    {
                        await _p.PredictAsync(new Input1("test"));
                    }
                }
            }
            """;

        var (_, runResult) = RunGenerator(source);

        Assert.DoesNotContain(runResult.Results[0].GeneratedSources,
            s => s.HintName == "LmpInterceptors.g.cs");
    }

    [Fact]
    public void Pipeline_InterceptorsNotEmitted_WhenOptInMissing()
    {
        // Valid PredictAsync call but LMP_INTERCEPTORS not defined — should NOT emit interceptors
        var source = GetInterceptorPipelineSource();
        var (_, runResult) = RunGenerator(source, enableInterceptors: false);

        Assert.DoesNotContain(runResult.Results[0].GeneratedSources,
            s => s.HintName == "LmpInterceptors.g.cs");
    }

    #endregion

    #region Helpers

    private static ImmutableArray<InterceptorCallSiteModel> CreateSingleCallSite(
        string inputTypeFqn = "global::TestApp.TicketInput",
        string outputTypeFqn = "global::TestApp.ClassifyTicket",
        string outputTypeName = "ClassifyTicket",
        string ns = "TestApp",
        int version = 1,
        string data = "dGVzdGRhdGE=",
        string displayLocation = "test.cs(10,20)")
    {
        return ImmutableArray.Create(
            CreateCallSite(inputTypeFqn, outputTypeFqn, outputTypeName, ns, version, data, displayLocation));
    }

    private static InterceptorCallSiteModel CreateCallSite(
        string inputTypeFqn,
        string outputTypeFqn,
        string outputTypeName,
        string ns,
        int version,
        string data,
        string displayLocation)
    {
        return new InterceptorCallSiteModel(
            InputTypeFQN: inputTypeFqn,
            OutputTypeFQN: outputTypeFqn,
            OutputTypeName: outputTypeName,
            Namespace: ns,
            LocationVersion: version,
            LocationData: data,
            DisplayLocation: displayLocation);
    }

    private static string GetInterceptorPipelineSource() => """
        using System.ComponentModel;
        using System.Threading.Tasks;

        namespace LMP
        {
            public class Predictor<TInput, TOutput> where TOutput : class
            {
                public Predictor(object client) { }
                public virtual Task<TOutput> PredictAsync(TInput input) => throw null!;
                public string Instructions { get; set; } = "";
                public string Name { get; set; } = "";
            }
            public class Trace { public void Record(string n, object i, object o) {} }
            public class LmpAssertionException : System.Exception { }
            public class LmpMaxRetriesExceededException : System.Exception
            {
                public LmpMaxRetriesExceededException(string n, int r) { }
            }
            public interface IChatClient { }
        }

        namespace TestApp
        {
            using LMP;

            public record TicketInput(
                [Description("The raw ticket text")] string TicketText);

            [LmpSignature("Classify a support ticket")]
            public partial record ClassifyTicket
            {
                [Description("Category: billing, technical, account")]
                public required string Category { get; init; }
            }

            public class TicketModule
            {
                private readonly Predictor<TicketInput, ClassifyTicket> _classify = null!;

                public async Task<ClassifyTicket> Run(TicketInput input)
                {
                    return await _classify.PredictAsync(input);
                }
            }
        }
        """;

    private static (Diagnostic[] Diagnostics, GeneratorDriverRunResult RunResult) RunGenerator(
        string source, bool enableInterceptors = true)
    {
        var parseOptions = CSharpParseOptions.Default;
        if (enableInterceptors)
            parseOptions = parseOptions.WithPreprocessorSymbols("LMP_INTERCEPTORS");

        var compilation = CreateCompilation(source, parseOptions);

        var generator = new LmpSourceGenerator().AsSourceGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [generator],
            parseOptions: parseOptions);
        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation, out _, out var diagnostics);

        return (diagnostics.ToArray(), driver.GetRunResult());
    }

    private static CSharpCompilation CreateCompilation(string source, CSharpParseOptions? parseOptions = null)
    {
        parseOptions ??= CSharpParseOptions.Default;

        var syntaxTrees = string.IsNullOrWhiteSpace(source)
            ? System.Array.Empty<SyntaxTree>()
            : new[] { CSharpSyntaxTree.ParseText(source, parseOptions) };

        return CSharpCompilation.Create(
            "TestAssembly",
            syntaxTrees: syntaxTrees,
            references:
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(LmpSignatureAttribute).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(System.ComponentModel.DescriptionAttribute).Assembly.Location),
                .. GetNetCoreReferences(),
            ],
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static MetadataReference[] GetNetCoreReferences()
    {
        var runtimeDir = System.IO.Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        return
        [
            MetadataReference.CreateFromFile(System.IO.Path.Combine(runtimeDir, "System.Runtime.dll")),
        ];
    }

    private static int CountOccurrences(string text, string pattern)
    {
        int count = 0;
        int idx = 0;
        while ((idx = text.IndexOf(pattern, idx)) != -1)
        {
            count++;
            idx += pattern.Length;
        }
        return count;
    }

    #endregion
}
