using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace LMP.SourceGen.Tests;

/// <summary>
/// Tests for Phase 2.4 — JsonContext source code emission.
/// Tests the <see cref="JsonContextEmitter"/> directly with manually constructed models.
/// </summary>
public class JsonContextEmitterTests
{
    #region GenerateSource — null/skip cases

    [Fact]
    public void GenerateSource_ReturnsNull_WhenNotPartialRecord()
    {
        var model = CreateModel(isPartialRecord: false);
        var source = JsonContextEmitter.GenerateSource(model);
        Assert.Null(source);
    }

    #endregion

    #region Generated code structure

    [Fact]
    public void GenerateSource_IncludesAutoGeneratedHeader()
    {
        var model = CreateModel();
        var source = JsonContextEmitter.GenerateSource(model)!;

        Assert.StartsWith("// <auto-generated />", source);
        Assert.Contains("#nullable enable", source);
    }

    [Fact]
    public void GenerateSource_IncludesRequiredUsings()
    {
        var model = CreateModel();
        var source = JsonContextEmitter.GenerateSource(model)!;

        Assert.Contains("using System.CodeDom.Compiler;", source);
        Assert.Contains("using System.Text.Json;", source);
        Assert.Contains("using System.Text.Json.Serialization;", source);
    }

    [Fact]
    public void GenerateSource_IncludesNamespace()
    {
        var model = CreateModel(ns: "TestApp.Models");
        var source = JsonContextEmitter.GenerateSource(model)!;

        Assert.Contains("namespace TestApp.Models;", source);
    }

    [Fact]
    public void GenerateSource_OmitsNamespace_WhenGlobal()
    {
        var model = CreateModel(ns: "");
        var source = JsonContextEmitter.GenerateSource(model)!;

        Assert.DoesNotContain("namespace", source);
    }

    [Fact]
    public void GenerateSource_IncludesGeneratedCodeAttribute()
    {
        var model = CreateModel();
        var source = JsonContextEmitter.GenerateSource(model)!;

        Assert.Contains("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]", source);
    }

    [Fact]
    public void GenerateSource_UsesFilePartialClass()
    {
        var model = CreateModel(typeName: "ClassifyTicket");
        var source = JsonContextEmitter.GenerateSource(model)!;

        Assert.Contains("file partial class ClassifyTicketJsonContext : JsonSerializerContext;", source);
    }

    #endregion

    #region JsonSourceGenerationOptions

    [Fact]
    public void GenerateSource_IncludesJsonSourceGenerationOptions()
    {
        var model = CreateModel();
        var source = JsonContextEmitter.GenerateSource(model)!;

        Assert.Contains("[JsonSourceGenerationOptions(", source);
        Assert.Contains("PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase", source);
        Assert.Contains("DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull", source);
    }

    [Fact]
    public void GenerateSource_IncludesJsonSerializableAttribute()
    {
        var model = CreateModel(typeName: "ClassifyTicket");
        var source = JsonContextEmitter.GenerateSource(model)!;

        Assert.Contains("[JsonSerializable(typeof(ClassifyTicket))]", source);
    }

    [Fact]
    public void GenerateSource_IncludesJsonSerializableAttribute_DifferentType()
    {
        var model = CreateModel(typeName: "DraftReply");
        var source = JsonContextEmitter.GenerateSource(model)!;

        Assert.Contains("[JsonSerializable(typeof(DraftReply))]", source);
        Assert.Contains("file partial class DraftReplyJsonContext : JsonSerializerContext;", source);
    }

    #endregion

    #region Syntax validity

    [Fact]
    public void GenerateSource_ProducesSyntacticallyValidCSharp()
    {
        var model = CreateModel();
        var source = JsonContextEmitter.GenerateSource(model)!;

        var tree = CSharpSyntaxTree.ParseText(source);
        var syntaxDiagnostics = tree.GetDiagnostics().ToArray();

        Assert.Empty(syntaxDiagnostics);
    }

    [Fact]
    public void GenerateSource_ProducesSyntacticallyValidCSharp_NoNamespace()
    {
        var model = CreateModel(ns: "");
        var source = JsonContextEmitter.GenerateSource(model)!;

        var tree = CSharpSyntaxTree.ParseText(source);
        var syntaxDiagnostics = tree.GetDiagnostics().ToArray();

        Assert.Empty(syntaxDiagnostics);
    }

    #endregion

    #region Full snapshot-style verification

    [Fact]
    public void GenerateSource_FullOutput_MatchesExpectedStructure()
    {
        var model = CreateModel(ns: "Demo", typeName: "ClassifyTicket");
        var source = JsonContextEmitter.GenerateSource(model)!;

        // Verify overall structure: header → usings → namespace → attributes → class
        var headerIdx = source.IndexOf("// <auto-generated />");
        var usingIdx = source.IndexOf("using System.Text.Json.Serialization;");
        var nsIdx = source.IndexOf("namespace Demo;");
        var genCodeIdx = source.IndexOf("[GeneratedCode(");
        var optionsIdx = source.IndexOf("[JsonSourceGenerationOptions(");
        var serializableIdx = source.IndexOf("[JsonSerializable(typeof(ClassifyTicket))]");
        var classIdx = source.IndexOf("file partial class ClassifyTicketJsonContext : JsonSerializerContext;");

        Assert.True(headerIdx >= 0, "Auto-generated header not found");
        Assert.True(usingIdx > headerIdx, "Usings should follow header");
        Assert.True(nsIdx > usingIdx, "Namespace should follow usings");
        Assert.True(genCodeIdx > nsIdx, "GeneratedCode attribute should follow namespace");
        Assert.True(optionsIdx > genCodeIdx, "JsonSourceGenerationOptions should follow GeneratedCode");
        Assert.True(serializableIdx > optionsIdx, "JsonSerializable should follow options");
        Assert.True(classIdx > serializableIdx, "Class declaration should follow attributes");
    }

    [Fact]
    public void GenerateSource_FullOutput_NoNamespace_MatchesExpectedStructure()
    {
        var model = CreateModel(ns: "", typeName: "SimpleOutput");
        var source = JsonContextEmitter.GenerateSource(model)!;

        Assert.DoesNotContain("namespace", source);
        Assert.Contains("[JsonSerializable(typeof(SimpleOutput))]", source);
        Assert.Contains("file partial class SimpleOutputJsonContext : JsonSerializerContext;", source);
    }

    #endregion

    #region Helpers

    private static OutputTypeModel CreateModel(
        string ns = "TestApp",
        string typeName = "ClassifyTicket",
        string instructions = "Test instructions",
        bool isPartialRecord = true)
    {
        var outputFields = new[]
        {
            new OutputFieldModel(
                Name: "Category",
                ClrTypeName: "string",
                FullyQualifiedTypeName: "global::System.String",
                Description: "Category: billing, technical, account",
                IsRequired: true,
                IsNonSerializable: false,
                Location: default),
            new OutputFieldModel(
                Name: "Urgency",
                ClrTypeName: "int",
                FullyQualifiedTypeName: "global::System.Int32",
                Description: "Urgency from 1 (low) to 5 (critical)",
                IsRequired: true,
                IsNonSerializable: false,
                Location: default),
        };

        return new OutputTypeModel(
            Namespace: ns,
            TypeName: typeName,
            Instructions: instructions,
            InputFields: default,
            OutputFields: new EquatableArray<OutputFieldModel>(outputFields.ToImmutableArray()),
            IsPartialRecord: isPartialRecord,
            TypeKindDescription: isPartialRecord ? null : "a class",
            Location: default);
    }

    #endregion
}
