using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace LMP.SourceGen.Tests;

/// <summary>
/// Tests for Phase 2.5 — GetPredictors() emission on LmpModule subclasses.
/// Tests <see cref="ModuleEmitter"/> directly and via the full generator pipeline.
/// </summary>
public class ModuleEmitterTests
{
    #region Direct emitter tests — ModuleEmitter.GenerateSource

    [Fact]
    public void GenerateSource_IncludesAutoGeneratedHeader()
    {
        var model = CreateModuleModel();
        var source = ModuleEmitter.GenerateSource(model);

        Assert.StartsWith("// <auto-generated />", source);
        Assert.Contains("#nullable enable", source);
    }

    [Fact]
    public void GenerateSource_IncludesRequiredUsings()
    {
        var model = CreateModuleModel();
        var source = ModuleEmitter.GenerateSource(model);

        Assert.Contains("using System.CodeDom.Compiler;", source);
        Assert.Contains("using System.Collections.Generic;", source);
        Assert.Contains("using LMP;", source);
    }

    [Fact]
    public void GenerateSource_IncludesNamespace()
    {
        var model = CreateModuleModel(ns: "Demo.App");
        var source = ModuleEmitter.GenerateSource(model);

        Assert.Contains("namespace Demo.App;", source);
    }

    [Fact]
    public void GenerateSource_OmitsNamespace_WhenGlobal()
    {
        var model = CreateModuleModel(ns: "");
        var source = ModuleEmitter.GenerateSource(model);

        Assert.DoesNotContain("namespace", source);
    }

    [Fact]
    public void GenerateSource_EmitsPartialClass()
    {
        var model = CreateModuleModel(typeName: "TicketTriageModule");
        var source = ModuleEmitter.GenerateSource(model);

        Assert.Contains("partial class TicketTriageModule", source);
    }

    [Fact]
    public void GenerateSource_IncludesGeneratedCodeAttribute()
    {
        var model = CreateModuleModel();
        var source = ModuleEmitter.GenerateSource(model);

        Assert.Contains("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]", source);
    }

    [Fact]
    public void GenerateSource_EmitsGetPredictorsOverride()
    {
        var model = CreateModuleModel();
        var source = ModuleEmitter.GenerateSource(model);

        Assert.Contains(
            "public override IReadOnlyList<(string Name, IPredictor Predictor)> GetPredictors()",
            source);
    }

    [Fact]
    public void GenerateSource_ReturnsAllPredictorFields()
    {
        var model = CreateModuleModel(fields: new[]
        {
            new PredictorFieldModel("_classify", "global::TestApp.TicketInput", "global::TestApp.ClassifyTicket"),
            new PredictorFieldModel("_draft", "global::TestApp.ClassifyTicket", "global::TestApp.DraftReply"),
        });
        var source = ModuleEmitter.GenerateSource(model);

        Assert.Contains("(\"classify\", _classify),", source);
        Assert.Contains("(\"draft\", _draft),", source);
    }

    [Fact]
    public void GenerateSource_StripsUnderscorePrefix()
    {
        var model = CreateModuleModel(fields: new[]
        {
            new PredictorFieldModel("_myPredictor", "global::A", "global::B"),
        });
        var source = ModuleEmitter.GenerateSource(model);

        Assert.Contains("(\"myPredictor\", _myPredictor),", source);
    }

    [Fact]
    public void GenerateSource_KeepsFieldNameWithoutUnderscore()
    {
        var model = CreateModuleModel(fields: new[]
        {
            new PredictorFieldModel("classifier", "global::A", "global::B"),
        });
        var source = ModuleEmitter.GenerateSource(model);

        Assert.Contains("(\"classifier\", classifier),", source);
    }

    [Fact]
    public void GenerateSource_SingleField_ProducesValidOutput()
    {
        var model = CreateModuleModel(fields: new[]
        {
            new PredictorFieldModel("_predict", "global::A", "global::B"),
        });
        var source = ModuleEmitter.GenerateSource(model);

        Assert.Contains("(\"predict\", _predict),", source);
    }

    [Fact]
    public void GenerateSource_ProducesSyntacticallyValidCSharp()
    {
        var model = CreateModuleModel();
        var source = ModuleEmitter.GenerateSource(model);

        var tree = CSharpSyntaxTree.ParseText(source);
        var syntaxDiagnostics = tree.GetDiagnostics().ToArray();

        Assert.Empty(syntaxDiagnostics);
    }

    [Fact]
    public void GenerateSource_ProducesSyntacticallyValidCSharp_NoNamespace()
    {
        var model = CreateModuleModel(ns: "");
        var source = ModuleEmitter.GenerateSource(model);

        var tree = CSharpSyntaxTree.ParseText(source);
        var syntaxDiagnostics = tree.GetDiagnostics().ToArray();

        Assert.Empty(syntaxDiagnostics);
    }

    [Fact]
    public void GenerateSource_FullSnapshot_MatchesExpectedStructure()
    {
        var model = CreateModuleModel(
            ns: "Demo",
            typeName: "TicketTriageModule",
            fields: new[]
            {
                new PredictorFieldModel("_classify", "global::Demo.TicketInput", "global::Demo.ClassifyTicket"),
                new PredictorFieldModel("_draft", "global::Demo.ClassifyTicket", "global::Demo.DraftReply"),
            });

        var source = ModuleEmitter.GenerateSource(model);

        // Verify overall structure order
        var partialClassIdx = source.IndexOf("partial class TicketTriageModule");
        var getPredictorsIdx = source.IndexOf("public override IReadOnlyList<(string Name, IPredictor Predictor)> GetPredictors()");
        var classifyIdx = source.IndexOf("(\"classify\", _classify),");
        var draftIdx = source.IndexOf("(\"draft\", _draft),");

        Assert.True(partialClassIdx > 0, "partial class not found");
        Assert.True(getPredictorsIdx > partialClassIdx, "GetPredictors should be inside class");
        Assert.True(classifyIdx > getPredictorsIdx, "classify entry should follow GetPredictors");
        Assert.True(draftIdx > classifyIdx, "draft entry should follow classify");
    }

    #endregion

    #region Pipeline integration tests — full generator

    [Fact]
    public void Pipeline_EmitsGetPredictors_ForModuleWithPredictorFields()
    {
        var source = GetModulePipelineSource();
        var (diagnostics, runResult) = RunGenerator(source);

        Assert.Empty(diagnostics);

        var predictorsFile = runResult.Results[0].GeneratedSources
            .FirstOrDefault(s => s.HintName.Contains("Predictors"));
        Assert.True(predictorsFile.HintName is not null,
            "Expected a .Predictors.g.cs file to be generated");

        var generatedSource = predictorsFile.SourceText.ToString();
        Assert.Contains("partial class TicketTriageModule", generatedSource);
        Assert.Contains("GetPredictors()", generatedSource);
        Assert.Contains("(\"classify\", _classify),", generatedSource);
        Assert.Contains("(\"draft\", _draft),", generatedSource);
    }

    [Fact]
    public void Pipeline_HintName_FollowsConvention()
    {
        var source = GetModulePipelineSource();
        var (_, runResult) = RunGenerator(source);

        Assert.Contains(runResult.Results[0].GeneratedSources,
            s => s.HintName == "TicketTriageModule.Predictors.g.cs");
    }

    [Fact]
    public void Pipeline_NoModuleSubclass_NoPredictorsEmitted()
    {
        var source = """
            namespace LMP
            {
                public abstract class LmpModule
                {
                    public virtual System.Collections.Generic.IReadOnlyList<(string Name, object Predictor)> GetPredictors() => System.Array.Empty<(string, object)>();
                }
                public class Predictor<TInput, TOutput> where TOutput : class
                {
                    public Predictor(object client) { }
                }
            }

            namespace TestApp
            {
                using LMP;

                public partial class NotAModule
                {
                    private readonly Predictor<string, string> _predict = null!;
                }
            }
            """;

        var (_, runResult) = RunGenerator(source);

        Assert.DoesNotContain(runResult.Results[0].GeneratedSources,
            s => s.HintName.Contains("Predictors"));
    }

    [Fact]
    public void Pipeline_ModuleWithNoPredictorFields_NoPredictorsEmitted()
    {
        var source = """
            namespace LMP
            {
                public abstract class LmpModule
                {
                    public virtual System.Collections.Generic.IReadOnlyList<(string Name, object Predictor)> GetPredictors() => System.Array.Empty<(string, object)>();
                }
            }

            namespace TestApp
            {
                using LMP;

                public partial class EmptyModule : LmpModule
                {
                    private readonly string _notAPredictor = "";

                    public override System.Threading.Tasks.Task<object> ForwardAsync(
                        object input, System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.FromResult(input);
                }
            }
            """;

        var (_, runResult) = RunGenerator(source);

        Assert.DoesNotContain(runResult.Results[0].GeneratedSources,
            s => s.HintName.Contains("Predictors"));
    }

    [Fact]
    public void Pipeline_NonPartialModule_NoPredictorsEmitted()
    {
        var source = """
            namespace LMP
            {
                public abstract class LmpModule
                {
                    public virtual System.Collections.Generic.IReadOnlyList<(string Name, object Predictor)> GetPredictors() => System.Array.Empty<(string, object)>();
                }
                public class Predictor<TInput, TOutput> where TOutput : class
                {
                    public Predictor(object client) { }
                }
            }

            namespace TestApp
            {
                using LMP;

                public class NonPartialModule : LmpModule
                {
                    private readonly Predictor<string, string> _predict = null!;

                    public override System.Threading.Tasks.Task<object> ForwardAsync(
                        object input, System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.FromResult(input);
                }
            }
            """;

        var (_, runResult) = RunGenerator(source);

        Assert.DoesNotContain(runResult.Results[0].GeneratedSources,
            s => s.HintName.Contains("Predictors"));
    }

    [Fact]
    public void Pipeline_ModuleWithSingleField_EmitsSingleEntry()
    {
        var source = """
            namespace LMP
            {
                public abstract class LmpModule
                {
                    public virtual System.Collections.Generic.IReadOnlyList<(string Name, IPredictor Predictor)> GetPredictors() => System.Array.Empty<(string, IPredictor)>();
                }
                public interface IPredictor { }
                public class Predictor<TInput, TOutput> : IPredictor where TOutput : class
                {
                    public Predictor(object client) { }
                }
            }

            namespace TestApp
            {
                using LMP;

                public record TestInput(string Text);
                public partial record TestOutput { public required string Result { get; init; } }

                public partial class SingleModule : LmpModule
                {
                    private readonly Predictor<TestInput, TestOutput> _predict;

                    public SingleModule(object client)
                    {
                        _predict = new Predictor<TestInput, TestOutput>(client);
                    }

                    public override System.Threading.Tasks.Task<object> ForwardAsync(
                        object input, System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.FromResult<object>(null!);
                }
            }
            """;

        var (diagnostics, runResult) = RunGenerator(source);
        Assert.Empty(diagnostics);

        var predictorsFile = runResult.Results[0].GeneratedSources
            .FirstOrDefault(s => s.HintName == "SingleModule.Predictors.g.cs");
        Assert.True(predictorsFile.HintName is not null,
            "Expected SingleModule.Predictors.g.cs");

        var text = predictorsFile.SourceText.ToString();
        Assert.Contains("(\"predict\", _predict),", text);
    }

    #endregion

    #region Model tests

    [Fact]
    public void ModuleModel_Equality_SameFields()
    {
        var fields = new[]
        {
            new PredictorFieldModel("_a", "global::X", "global::Y"),
        };
        var model1 = new ModuleModel("NS", "Mod", new EquatableArray<PredictorFieldModel>(fields.ToImmutableArray()));
        var model2 = new ModuleModel("NS", "Mod", new EquatableArray<PredictorFieldModel>(fields.ToImmutableArray()));

        Assert.Equal(model1, model2);
    }

    [Fact]
    public void PredictorFieldModel_Equality()
    {
        var f1 = new PredictorFieldModel("_x", "global::A", "global::B");
        var f2 = new PredictorFieldModel("_x", "global::A", "global::B");

        Assert.Equal(f1, f2);
    }

    [Fact]
    public void PredictorFieldModel_Inequality()
    {
        var f1 = new PredictorFieldModel("_x", "global::A", "global::B");
        var f2 = new PredictorFieldModel("_y", "global::A", "global::B");

        Assert.NotEqual(f1, f2);
    }

    #endregion

    #region Helpers

    private static ModuleModel CreateModuleModel(
        string ns = "TestApp",
        string typeName = "TestModule",
        PredictorFieldModel[]? fields = null)
    {
        fields ??= new[]
        {
            new PredictorFieldModel("_classify", "global::TestApp.TicketInput", "global::TestApp.ClassifyTicket"),
            new PredictorFieldModel("_draft", "global::TestApp.ClassifyTicket", "global::TestApp.DraftReply"),
        };

        return new ModuleModel(
            Namespace: ns,
            TypeName: typeName,
            PredictorFields: new EquatableArray<PredictorFieldModel>(fields.ToImmutableArray()));
    }

    private static string GetModulePipelineSource() => """
        namespace LMP
        {
            public abstract class LmpModule
            {
                public virtual System.Collections.Generic.IReadOnlyList<(string Name, IPredictor Predictor)> GetPredictors() => System.Array.Empty<(string, IPredictor)>();
            }
            public interface IPredictor { }
            public class Predictor<TInput, TOutput> : IPredictor where TOutput : class
            {
                public Predictor(object client) { }
            }
        }

        namespace TestApp
        {
            using LMP;

            public record TicketInput(string TicketText);
            public record ClassifyTicket { public required string Category { get; init; } }
            public partial record DraftReply { public required string Text { get; init; } }

            public partial class TicketTriageModule : LmpModule
            {
                private readonly Predictor<TicketInput, ClassifyTicket> _classify;
                private readonly Predictor<ClassifyTicket, DraftReply> _draft;

                public TicketTriageModule(object client)
                {
                    _classify = new Predictor<TicketInput, ClassifyTicket>(client);
                    _draft = new Predictor<ClassifyTicket, DraftReply>(client);
                }

                public override System.Threading.Tasks.Task<object> ForwardAsync(
                    object input, System.Threading.CancellationToken ct = default)
                    => System.Threading.Tasks.Task.FromResult<object>(null!);
            }
        }
        """;

    private static (Diagnostic[] Diagnostics, GeneratorDriverRunResult RunResult) RunGenerator(string source)
    {
        var compilation = CreateCompilation(source);

        var generator = new LmpSourceGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation, out _, out var diagnostics);

        return (diagnostics.ToArray(), driver.GetRunResult());
    }

    private static CSharpCompilation CreateCompilation(string source)
    {
        var syntaxTrees = string.IsNullOrWhiteSpace(source)
            ? System.Array.Empty<Microsoft.CodeAnalysis.SyntaxTree>()
            : new[] { CSharpSyntaxTree.ParseText(source) };

        return CSharpCompilation.Create(
            "TestAssembly",
            syntaxTrees: syntaxTrees,
            references:
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(LmpSignatureAttribute).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(System.ComponentModel.DescriptionAttribute).Assembly.Location),
                .. GetNetCoreReferences(),
            ],
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static MetadataReference[] GetNetCoreReferences()
    {
        var runtimeDir = System.IO.Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        return
        [
            MetadataReference.CreateFromFile(System.IO.Path.Combine(runtimeDir, "System.Runtime.dll")),
        ];
    }

    #endregion
}
