using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace LMP.SourceGen.Tests;

/// <summary>
/// Tests for Phase 2.8 — Module-level JsonSerializerContext emission.
/// Tests <see cref="ModuleJsonContextEmitter"/> directly and via the full generator pipeline.
/// </summary>
public class ModuleJsonContextEmitterTests
{
    #region Generated code structure

    [Fact]
    public void GenerateSource_IncludesAutoGeneratedHeader()
    {
        var model = CreateModuleModel();
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.StartsWith("// <auto-generated />", source);
        Assert.Contains("#nullable enable", source);
    }

    [Fact]
    public void GenerateSource_IncludesRequiredUsings()
    {
        var model = CreateModuleModel();
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.Contains("using System.CodeDom.Compiler;", source);
        Assert.Contains("using System.Text.Json;", source);
        Assert.Contains("using System.Text.Json.Serialization;", source);
        Assert.Contains("using LMP;", source);
    }

    [Fact]
    public void GenerateSource_IncludesNamespace()
    {
        var model = CreateModuleModel(ns: "Demo.App");
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.Contains("namespace Demo.App;", source);
    }

    [Fact]
    public void GenerateSource_OmitsNamespace_WhenGlobal()
    {
        var model = CreateModuleModel(ns: "");
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.DoesNotContain("namespace", source);
    }

    [Fact]
    public void GenerateSource_IncludesGeneratedCodeAttribute()
    {
        var model = CreateModuleModel();
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.Contains("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]", source);
    }

    [Fact]
    public void GenerateSource_UsesFilePartialClass()
    {
        var model = CreateModuleModel(typeName: "TicketTriageModule");
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.Contains("file partial class TicketTriageModuleJsonContext : JsonSerializerContext;", source);
    }

    [Fact]
    public void GenerateSource_UsesModuleTypeName_InClassName()
    {
        var model = CreateModuleModel(typeName: "CustomerSupportModule");
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.Contains("file partial class CustomerSupportModuleJsonContext : JsonSerializerContext;", source);
    }

    #endregion

    #region JsonSourceGenerationOptions

    [Fact]
    public void GenerateSource_IncludesJsonSourceGenerationOptions()
    {
        var model = CreateModuleModel();
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.Contains("[JsonSourceGenerationOptions(", source);
        Assert.Contains("PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase", source);
        Assert.Contains("WriteIndented = true", source);
        Assert.Contains("DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull", source);
    }

    [Fact]
    public void GenerateSource_IncludesModuleStateSerializable()
    {
        var model = CreateModuleModel();
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.Contains("[JsonSerializable(typeof(ModuleState))]", source);
    }

    [Fact]
    public void GenerateSource_IncludesPredictorStateSerializable()
    {
        var model = CreateModuleModel();
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.Contains("[JsonSerializable(typeof(PredictorState))]", source);
    }

    [Fact]
    public void GenerateSource_IncludesDemoEntrySerializable()
    {
        var model = CreateModuleModel();
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.Contains("[JsonSerializable(typeof(DemoEntry))]", source);
    }

    #endregion

    #region Syntax validity

    [Fact]
    public void GenerateSource_ProducesSyntacticallyValidCSharp()
    {
        var model = CreateModuleModel();
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        var tree = CSharpSyntaxTree.ParseText(source);
        var syntaxDiagnostics = tree.GetDiagnostics().ToArray();

        Assert.Empty(syntaxDiagnostics);
    }

    [Fact]
    public void GenerateSource_ProducesSyntacticallyValidCSharp_NoNamespace()
    {
        var model = CreateModuleModel(ns: "");
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        var tree = CSharpSyntaxTree.ParseText(source);
        var syntaxDiagnostics = tree.GetDiagnostics().ToArray();

        Assert.Empty(syntaxDiagnostics);
    }

    #endregion

    #region Full snapshot-style verification

    [Fact]
    public void GenerateSource_FullOutput_MatchesExpectedStructure()
    {
        var model = CreateModuleModel(ns: "Demo", typeName: "TicketTriageModule");
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        // Verify overall structure: header → usings → namespace → attributes → class
        var headerIdx = source.IndexOf("// <auto-generated />");
        var usingStjIdx = source.IndexOf("using System.Text.Json.Serialization;");
        var usingLmpIdx = source.IndexOf("using LMP;");
        var nsIdx = source.IndexOf("namespace Demo;");
        var genCodeIdx = source.IndexOf("[GeneratedCode(");
        var optionsIdx = source.IndexOf("[JsonSourceGenerationOptions(");
        var moduleStateIdx = source.IndexOf("[JsonSerializable(typeof(ModuleState))]");
        var predictorStateIdx = source.IndexOf("[JsonSerializable(typeof(PredictorState))]");
        var demoEntryIdx = source.IndexOf("[JsonSerializable(typeof(DemoEntry))]");
        var classIdx = source.IndexOf("file partial class TicketTriageModuleJsonContext : JsonSerializerContext;");

        Assert.True(headerIdx >= 0, "Auto-generated header not found");
        Assert.True(usingStjIdx > headerIdx, "STJ usings should follow header");
        Assert.True(usingLmpIdx > usingStjIdx, "LMP using should follow STJ usings");
        Assert.True(nsIdx > usingLmpIdx, "Namespace should follow usings");
        Assert.True(genCodeIdx > nsIdx, "GeneratedCode attribute should follow namespace");
        Assert.True(optionsIdx > genCodeIdx, "JsonSourceGenerationOptions should follow GeneratedCode");
        Assert.True(moduleStateIdx > optionsIdx, "ModuleState serializable should follow options");
        Assert.True(predictorStateIdx > moduleStateIdx, "PredictorState serializable should follow ModuleState");
        Assert.True(demoEntryIdx > predictorStateIdx, "DemoEntry serializable should follow PredictorState");
        Assert.True(classIdx > demoEntryIdx, "Class declaration should follow attributes");
    }

    [Fact]
    public void GenerateSource_FullOutput_NoNamespace_MatchesExpectedStructure()
    {
        var model = CreateModuleModel(ns: "", typeName: "SimpleModule");
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        Assert.DoesNotContain("namespace", source);
        Assert.Contains("[JsonSerializable(typeof(ModuleState))]", source);
        Assert.Contains("[JsonSerializable(typeof(PredictorState))]", source);
        Assert.Contains("[JsonSerializable(typeof(DemoEntry))]", source);
        Assert.Contains("file partial class SimpleModuleJsonContext : JsonSerializerContext;", source);
    }

    [Fact]
    public void GenerateSource_EmitsAllThreeSerializableTypes()
    {
        var model = CreateModuleModel();
        var source = ModuleJsonContextEmitter.GenerateSource(model);

        // Count [JsonSerializable] occurrences — exactly 3
        var count = source.Split("[JsonSerializable(").Length - 1;
        Assert.Equal(3, count);
    }

    #endregion

    #region Pipeline integration tests

    [Fact]
    public void Pipeline_ModuleWithPredictors_EmitsJsonContextFile()
    {
        var source = GetModulePipelineSource();
        var (diagnostics, runResult) = RunGenerator(source);
        Assert.Empty(diagnostics);

        Assert.Contains(runResult.Results[0].GeneratedSources,
            s => s.HintName == "TicketTriageModule.JsonContext.g.cs");
    }

    [Fact]
    public void Pipeline_ModuleJsonContext_ContainsModuleState()
    {
        var source = GetModulePipelineSource();
        var (_, runResult) = RunGenerator(source);

        var jsonContextFile = runResult.Results[0].GeneratedSources
            .First(s => s.HintName == "TicketTriageModule.JsonContext.g.cs");

        var text = jsonContextFile.SourceText.ToString();
        Assert.Contains("[JsonSerializable(typeof(ModuleState))]", text);
    }

    [Fact]
    public void Pipeline_ModuleJsonContext_ContainsPredictorState()
    {
        var source = GetModulePipelineSource();
        var (_, runResult) = RunGenerator(source);

        var jsonContextFile = runResult.Results[0].GeneratedSources
            .First(s => s.HintName == "TicketTriageModule.JsonContext.g.cs");

        var text = jsonContextFile.SourceText.ToString();
        Assert.Contains("[JsonSerializable(typeof(PredictorState))]", text);
    }

    [Fact]
    public void Pipeline_ModuleJsonContext_ContainsDemoEntry()
    {
        var source = GetModulePipelineSource();
        var (_, runResult) = RunGenerator(source);

        var jsonContextFile = runResult.Results[0].GeneratedSources
            .First(s => s.HintName == "TicketTriageModule.JsonContext.g.cs");

        var text = jsonContextFile.SourceText.ToString();
        Assert.Contains("[JsonSerializable(typeof(DemoEntry))]", text);
    }

    [Fact]
    public void Pipeline_ModuleJsonContext_UsesFilePartialClass()
    {
        var source = GetModulePipelineSource();
        var (_, runResult) = RunGenerator(source);

        var jsonContextFile = runResult.Results[0].GeneratedSources
            .First(s => s.HintName == "TicketTriageModule.JsonContext.g.cs");

        var text = jsonContextFile.SourceText.ToString();
        Assert.Contains("file partial class TicketTriageModuleJsonContext : JsonSerializerContext;", text);
    }

    [Fact]
    public void Pipeline_ModuleEmitsBothPredictorsAndJsonContext()
    {
        var source = GetModulePipelineSource();
        var (diagnostics, runResult) = RunGenerator(source);
        Assert.Empty(diagnostics);

        var generatedFiles = runResult.Results[0].GeneratedSources.Select(s => s.HintName).ToArray();

        Assert.Contains("TicketTriageModule.Predictors.g.cs", generatedFiles);
        Assert.Contains("TicketTriageModule.JsonContext.g.cs", generatedFiles);
    }

    [Fact]
    public void Pipeline_MultipleModules_EmitsJsonContextForEach()
    {
        var source = """
            namespace LMP
            {
                public abstract class LmpModule
                {
                    public virtual System.Collections.Generic.IReadOnlyList<(string Name, IPredictor Predictor)> GetPredictors() => System.Array.Empty<(string, IPredictor)>();
                }
                public interface IPredictor { }
                public class Predictor<TInput, TOutput> : IPredictor where TOutput : class
                {
                    public Predictor(object client) { }
                }
            }

            namespace TestApp
            {
                using LMP;

                public record Input1(string Text);
                public partial record Output1 { public required string Value { get; init; } }
                public record Input2(string Text);
                public partial record Output2 { public required string Value { get; init; } }

                public partial class ModuleA : LmpModule
                {
                    private readonly Predictor<Input1, Output1> _predict = null!;
                    public override System.Threading.Tasks.Task<object> ForwardAsync(
                        object input, System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.FromResult<object>(null!);
                }

                public partial class ModuleB : LmpModule
                {
                    private readonly Predictor<Input2, Output2> _predict = null!;
                    public override System.Threading.Tasks.Task<object> ForwardAsync(
                        object input, System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.FromResult<object>(null!);
                }
            }
            """;

        var (diagnostics, runResult) = RunGenerator(source);
        Assert.Empty(diagnostics);

        Assert.Contains(runResult.Results[0].GeneratedSources,
            s => s.HintName == "ModuleA.JsonContext.g.cs");
        Assert.Contains(runResult.Results[0].GeneratedSources,
            s => s.HintName == "ModuleB.JsonContext.g.cs");
    }

    [Fact]
    public void Pipeline_NonPartialModule_DoesNotEmitJsonContext()
    {
        var source = """
            namespace LMP
            {
                public abstract class LmpModule
                {
                    public virtual System.Collections.Generic.IReadOnlyList<(string Name, IPredictor Predictor)> GetPredictors() => System.Array.Empty<(string, IPredictor)>();
                }
                public interface IPredictor { }
                public class Predictor<TInput, TOutput> : IPredictor where TOutput : class
                {
                    public Predictor(object client) { }
                }
            }

            namespace TestApp
            {
                using LMP;

                public class NonPartialModule : LmpModule
                {
                    private readonly Predictor<string, string> _predict = null!;

                    public override System.Threading.Tasks.Task<object> ForwardAsync(
                        object input, System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.FromResult(input);
                }
            }
            """;

        var (_, runResult) = RunGenerator(source);

        Assert.DoesNotContain(runResult.Results[0].GeneratedSources,
            s => s.HintName.Contains("JsonContext"));
    }

    [Fact]
    public void Pipeline_ModuleWithSinglePredictor_EmitsJsonContext()
    {
        var source = """
            namespace LMP
            {
                public abstract class LmpModule
                {
                    public virtual System.Collections.Generic.IReadOnlyList<(string Name, IPredictor Predictor)> GetPredictors() => System.Array.Empty<(string, IPredictor)>();
                }
                public interface IPredictor { }
                public class Predictor<TInput, TOutput> : IPredictor where TOutput : class
                {
                    public Predictor(object client) { }
                }
            }

            namespace TestApp
            {
                using LMP;

                public record TestInput(string Text);
                public partial record TestOutput { public required string Result { get; init; } }

                public partial class SingleModule : LmpModule
                {
                    private readonly Predictor<TestInput, TestOutput> _predict;

                    public SingleModule(object client)
                    {
                        _predict = new Predictor<TestInput, TestOutput>(client);
                    }

                    public override System.Threading.Tasks.Task<object> ForwardAsync(
                        object input, System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.FromResult<object>(null!);
                }
            }
            """;

        var (diagnostics, runResult) = RunGenerator(source);
        Assert.Empty(diagnostics);

        var jsonContextFile = runResult.Results[0].GeneratedSources
            .FirstOrDefault(s => s.HintName == "SingleModule.JsonContext.g.cs");
        Assert.True(jsonContextFile.HintName is not null,
            "Expected SingleModule.JsonContext.g.cs");

        var text = jsonContextFile.SourceText.ToString();
        Assert.Contains("[JsonSerializable(typeof(ModuleState))]", text);
        Assert.Contains("[JsonSerializable(typeof(PredictorState))]", text);
        Assert.Contains("[JsonSerializable(typeof(DemoEntry))]", text);
        Assert.Contains("file partial class SingleModuleJsonContext : JsonSerializerContext;", text);
    }

    #endregion

    #region Helpers

    private static ModuleModel CreateModuleModel(
        string ns = "TestApp",
        string typeName = "TestModule",
        PredictorFieldModel[]? fields = null)
    {
        fields ??=
        [
            new PredictorFieldModel("_classify", "global::TestApp.TicketInput", "global::TestApp.ClassifyTicket"),
            new PredictorFieldModel("_draft", "global::TestApp.ClassifyTicket", "global::TestApp.DraftReply"),
        ];

        return new ModuleModel(
            Namespace: ns,
            TypeName: typeName,
            PredictorFields: new EquatableArray<PredictorFieldModel>(fields.ToImmutableArray()));
    }

    private static string GetModulePipelineSource() => """
        namespace LMP
        {
            public abstract class LmpModule
            {
                public virtual System.Collections.Generic.IReadOnlyList<(string Name, IPredictor Predictor)> GetPredictors() => System.Array.Empty<(string, IPredictor)>();
            }
            public interface IPredictor { }
            public class Predictor<TInput, TOutput> : IPredictor where TOutput : class
            {
                public Predictor(object client) { }
            }
        }

        namespace TestApp
        {
            using LMP;

            public record TicketInput(string TicketText);
            public record ClassifyTicket { public required string Category { get; init; } }
            public partial record DraftReply { public required string Text { get; init; } }

            public partial class TicketTriageModule : LmpModule
            {
                private readonly Predictor<TicketInput, ClassifyTicket> _classify;
                private readonly Predictor<ClassifyTicket, DraftReply> _draft;

                public TicketTriageModule(object client)
                {
                    _classify = new Predictor<TicketInput, ClassifyTicket>(client);
                    _draft = new Predictor<ClassifyTicket, DraftReply>(client);
                }

                public override System.Threading.Tasks.Task<object> ForwardAsync(
                    object input, System.Threading.CancellationToken ct = default)
                    => System.Threading.Tasks.Task.FromResult<object>(null!);
            }
        }
        """;

    private static (Diagnostic[] Diagnostics, GeneratorDriverRunResult RunResult) RunGenerator(string source)
    {
        var compilation = CreateCompilation(source);

        var generator = new LmpSourceGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation, out _, out var diagnostics);

        return (diagnostics.ToArray(), driver.GetRunResult());
    }

    private static CSharpCompilation CreateCompilation(string source)
    {
        var syntaxTrees = string.IsNullOrWhiteSpace(source)
            ? System.Array.Empty<Microsoft.CodeAnalysis.SyntaxTree>()
            : new[] { CSharpSyntaxTree.ParseText(source) };

        return CSharpCompilation.Create(
            "TestAssembly",
            syntaxTrees: syntaxTrees,
            references:
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(LmpSignatureAttribute).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(System.ComponentModel.DescriptionAttribute).Assembly.Location),
                .. GetNetCoreReferences(),
            ],
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static MetadataReference[] GetNetCoreReferences()
    {
        var runtimeDir = System.IO.Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        return
        [
            MetadataReference.CreateFromFile(System.IO.Path.Combine(runtimeDir, "System.Runtime.dll")),
        ];
    }

    #endregion
}
