using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace LMP.SourceGen.Tests;

/// <summary>
/// Tests for Phase 2.3 — PromptBuilder source code emission.
/// Tests the <see cref="PromptBuilderEmitter"/> directly with manually constructed models
/// and via the full generator pipeline with Predictor&lt;TIn, TOut&gt; discovery.
/// </summary>
public class PromptBuilderEmitterTests
{
    #region Generated code structure

    [Fact]
    public void GenerateSource_IncludesAutoGeneratedHeader()
    {
        var model = CreateFullModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.StartsWith("// <auto-generated />", source);
        Assert.Contains("#nullable enable", source);
    }

    [Fact]
    public void GenerateSource_IncludesRequiredUsings()
    {
        var model = CreateFullModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("using System;", source);
        Assert.Contains("using System.CodeDom.Compiler;", source);
        Assert.Contains("using System.Collections.Generic;", source);
        Assert.Contains("using Microsoft.Extensions.AI;", source);
    }

    [Fact]
    public void GenerateSource_IncludesNamespace()
    {
        var model = CreateFullModel(ns: "TestApp.Models");
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("namespace TestApp.Models;", source);
    }

    [Fact]
    public void GenerateSource_OmitsNamespace_WhenGlobal()
    {
        var model = CreateFullModel(ns: "");
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.DoesNotContain("namespace", source);
    }

    [Fact]
    public void GenerateSource_UsesFileStaticClass()
    {
        var model = CreateFullModel(outputTypeName: "ClassifyTicket");
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("file static class ClassifyTicketPromptBuilder", source);
    }

    [Fact]
    public void GenerateSource_IncludesGeneratedCodeAttribute()
    {
        var model = CreateFullModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]", source);
    }

    #endregion

    #region Instructions and FieldDescriptions

    [Fact]
    public void GenerateSource_EmitsInstructionsConstant()
    {
        var model = CreateFullModel(instructions: "Classify a support ticket by category and urgency");
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("private const string Instructions =", source);
        Assert.Contains("Classify a support ticket by category and urgency", source);
    }

    [Fact]
    public void GenerateSource_EscapesSpecialCharactersInInstructions()
    {
        var model = CreateFullModel(instructions: "Use \"quotes\" and \\backslash");
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("Use \\\"quotes\\\" and \\\\backslash", source);
    }

    [Fact]
    public void GenerateSource_EmitsFieldDescriptions_WithInputAndOutputFields()
    {
        var model = CreateFullModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("private const string FieldDescriptions =", source);
        Assert.Contains("Input Fields:", source);
        Assert.Contains("- TicketText (string): The raw ticket text", source);
        Assert.Contains("- AccountTier (string): Customer plan tier", source);
        Assert.Contains("Output Fields:", source);
        Assert.Contains("- Category (string): Category: billing, technical, account", source);
        Assert.Contains("- Urgency (int): Urgency from 1 (low) to 5 (critical)", source);
    }

    [Fact]
    public void GenerateSource_EmitsFieldDescriptions_OmitsDescriptionWhenNull()
    {
        var model = CreateModel(
            inputFields: new[] { new InputFieldModel("Field1", "string", null) },
            outputFields: new[] { CreateOutputField("Field2", "int", null) });
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("- Field1 (string)", source);
        Assert.DoesNotContain("- Field1 (string):", source);
        Assert.Contains("- Field2 (int)", source);
        Assert.DoesNotContain("- Field2 (int):", source);
    }

    [Fact]
    public void GenerateSource_EmitsFieldDescriptions_WithOnlyOutputFields()
    {
        var model = CreateModel(
            inputFields: System.Array.Empty<InputFieldModel>(),
            outputFields: new[] { CreateOutputField("Result", "string", "The result") });
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.DoesNotContain("Input Fields:", source);
        Assert.Contains("Output Fields:", source);
        Assert.Contains("- Result (string): The result", source);
    }

    #endregion

    #region DefaultInstructions

    [Fact]
    public void GenerateSource_EmitsDefaultInstructionsProperty()
    {
        var model = CreateFullModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("public static string DefaultInstructions => Instructions;", source);
    }

    #endregion

    #region BuildMessages

    [Fact]
    public void GenerateSource_EmitsBuildMessages_WithCorrectSignature()
    {
        var model = CreateFullModel(inputTypeName: "TicketInput", outputTypeName: "ClassifyTicket");
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("public static IList<ChatMessage> BuildMessages(", source);
        Assert.Contains("TicketInput input,", source);
        Assert.Contains("IReadOnlyList<(TicketInput Input, ClassifyTicket Output)>? demos = null)", source);
    }

    [Fact]
    public void GenerateSource_EmitsBuildMessages_SystemMessage()
    {
        var model = CreateFullModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("ChatRole.System", source);
        Assert.Contains("Instructions + \"\\n\\n\" + FieldDescriptions", source);
    }

    [Fact]
    public void GenerateSource_EmitsBuildMessages_DemoPairs()
    {
        var model = CreateFullModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("if (demos is not null)", source);
        Assert.Contains("foreach (var (demoInput, demoOutput) in demos)", source);
        Assert.Contains("ChatRole.User, FormatInput(demoInput)", source);
        Assert.Contains("ChatRole.Assistant, FormatOutput(demoOutput)", source);
    }

    [Fact]
    public void GenerateSource_EmitsBuildMessages_CurrentInput()
    {
        var model = CreateFullModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("ChatRole.User, FormatInput(input)", source);
    }

    #endregion

    #region FormatInput

    [Fact]
    public void GenerateSource_EmitsFormatInput_MultipleFields()
    {
        var model = CreateFullModel(inputTypeName: "TicketInput");
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("private static string FormatInput(TicketInput input)", source);
        Assert.Contains("TicketText: {input.TicketText}", source);
        Assert.Contains("AccountTier: {input.AccountTier}", source);
    }

    [Fact]
    public void GenerateSource_EmitsFormatInput_SingleField()
    {
        var model = CreateModel(
            inputTypeName: "SimpleInput",
            inputFields: new[] { new InputFieldModel("Query", "string", "The query") },
            outputFields: new[] { CreateOutputField("Answer", "string", "The answer") });
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("private static string FormatInput(SimpleInput input)", source);
        Assert.Contains("Query: {input.Query}", source);
    }

    [Fact]
    public void GenerateSource_EmitsFormatInput_NoFields_FallsBackToToString()
    {
        var model = CreateModel(
            inputFields: System.Array.Empty<InputFieldModel>(),
            outputFields: new[] { CreateOutputField("Answer", "string", "The answer") });
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("input?.ToString() ?? \"\"", source);
    }

    #endregion

    #region FormatOutput

    [Fact]
    public void GenerateSource_EmitsFormatOutput_WithJsonSerialize()
    {
        var model = CreateFullModel(outputTypeName: "ClassifyTicket");
        var source = PromptBuilderEmitter.GenerateSource(model);

        Assert.Contains("private static string FormatOutput(ClassifyTicket output)", source);
        Assert.Contains("System.Text.Json.JsonSerializer.Serialize(output)", source);
    }

    #endregion

    #region Syntax validity

    [Fact]
    public void GenerateSource_ProducesSyntacticallyValidCSharp()
    {
        var model = CreateFullModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        var tree = CSharpSyntaxTree.ParseText(source);
        var syntaxDiagnostics = tree.GetDiagnostics().ToArray();

        Assert.Empty(syntaxDiagnostics);
    }

    [Fact]
    public void GenerateSource_ProducesSyntacticallyValidCSharp_NoNamespace()
    {
        var model = CreateFullModel(ns: "");
        var source = PromptBuilderEmitter.GenerateSource(model);

        var tree = CSharpSyntaxTree.ParseText(source);
        var syntaxDiagnostics = tree.GetDiagnostics().ToArray();

        Assert.Empty(syntaxDiagnostics);
    }

    [Fact]
    public void GenerateSource_ProducesSyntacticallyValidCSharp_SingleInputField()
    {
        var model = CreateModel(
            inputTypeName: "SingleInput",
            inputFields: new[] { new InputFieldModel("Value", "string", "The value") },
            outputFields: new[] { CreateOutputField("Result", "string", "The result") });
        var source = PromptBuilderEmitter.GenerateSource(model);

        var tree = CSharpSyntaxTree.ParseText(source);
        var syntaxDiagnostics = tree.GetDiagnostics().ToArray();

        Assert.Empty(syntaxDiagnostics);
    }

    [Fact]
    public void GenerateSource_ProducesSyntacticallyValidCSharp_NoInputFields()
    {
        var model = CreateModel(
            inputFields: System.Array.Empty<InputFieldModel>(),
            outputFields: new[] { CreateOutputField("Result", "string", "The result") });
        var source = PromptBuilderEmitter.GenerateSource(model);

        var tree = CSharpSyntaxTree.ParseText(source);
        var syntaxDiagnostics = tree.GetDiagnostics().ToArray();

        Assert.Empty(syntaxDiagnostics);
    }

    #endregion

    #region Full snapshot-style verification

    [Fact]
    public void GenerateSource_FullOutput_MatchesExpectedStructure()
    {
        var model = CreateFullModel();
        var source = PromptBuilderEmitter.GenerateSource(model);

        var instructionsIdx = source.IndexOf("private const string Instructions =");
        var fieldDescIdx = source.IndexOf("private const string FieldDescriptions =");
        var defaultIdx = source.IndexOf("public static string DefaultInstructions =>");
        var buildIdx = source.IndexOf("public static IList<ChatMessage> BuildMessages(");
        var formatInputIdx = source.IndexOf("private static string FormatInput(");
        var formatOutputIdx = source.IndexOf("private static string FormatOutput(");

        Assert.True(instructionsIdx > 0, "Instructions constant not found");
        Assert.True(fieldDescIdx > instructionsIdx, "FieldDescriptions should follow Instructions");
        Assert.True(defaultIdx > fieldDescIdx, "DefaultInstructions should follow FieldDescriptions");
        Assert.True(buildIdx > defaultIdx, "BuildMessages should follow DefaultInstructions");
        Assert.True(formatInputIdx > buildIdx, "FormatInput should follow BuildMessages");
        Assert.True(formatOutputIdx > formatInputIdx, "FormatOutput should follow FormatInput");
    }

    #endregion

    #region Pipeline integration — Predictor<TIn, TOut> discovery
    // These tests validate the full PredictorPairExtractor pipeline (Task 2.5).
    // They are skipped until the pipeline is fully wired and debugged.

    [Fact(Skip = "PredictorPairExtractor pipeline — Task 2.5")]
    public void Pipeline_EmitsPromptBuilder_ForValidPredictorUsage()
    {
        var source = GetPipelineTestSource();
        var (diagnostics, runResult) = RunGenerator(source);

        Assert.Empty(diagnostics);

        Assert.True(runResult.GeneratedTrees.Length >= 1,
            $"Expected at least 1 generated tree, got {runResult.GeneratedTrees.Length}");

        var promptBuilder = runResult.GeneratedTrees
            .FirstOrDefault(t => t.FilePath.Contains("PromptBuilder"));
        Assert.NotNull(promptBuilder);

        var generatedSource = promptBuilder!.GetText().ToString();
        Assert.Contains("file static class ClassifyTicketPromptBuilder", generatedSource);
        Assert.Contains("Classify a support ticket", generatedSource);
    }

    [Fact(Skip = "PredictorPairExtractor pipeline — Task 2.5")]
    public void Pipeline_HintName_FollowsConvention()
    {
        var source = GetPipelineTestSource();
        var (_, runResult) = RunGenerator(source);

        var generatorResult = runResult.Results[0];
        Assert.Contains(generatorResult.GeneratedSources,
            s => s.HintName == "ClassifyTicket.PromptBuilder.g.cs");
    }

    [Fact]
    public void Pipeline_NoPredictorUsage_NoPromptBuilder()
    {
        var source = """
            using System.ComponentModel;
            using LMP;

            namespace TestApp;

            [LmpSignature("Classify tickets")]
            public partial record ClassifyTicket
            {
                [Description("Category")]
                public required string Category { get; init; }
            }
            """;

        var (diagnostics, runResult) = RunGenerator(source);
        Assert.Empty(diagnostics);

        Assert.DoesNotContain(runResult.Results[0].GeneratedSources,
            s => s.HintName.Contains("PromptBuilder"));
    }

    [Fact]
    public void Pipeline_OutputTypeWithoutLmpSignature_NoPromptBuilder()
    {
        var source = """
            namespace LMP
            {
                public class Predictor<TInput, TOutput> where TOutput : class
                {
                    public Predictor(object client) { }
                }
            }

            namespace TestApp
            {
                using LMP;

                public record TicketInput(string TicketText);

                public partial record NotAnLmpType
                {
                    public required string Value { get; init; }
                }

                public class MyModule
                {
                    private readonly Predictor<TicketInput, NotAnLmpType> _predict = null!;
                }
            }
            """;

        var (_, runResult) = RunGenerator(source);
        Assert.DoesNotContain(runResult.Results[0].GeneratedSources,
            s => s.HintName.Contains("PromptBuilder"));
    }

    [Fact(Skip = "PredictorPairExtractor pipeline — Task 2.5")]
    public void Pipeline_DuplicatePredictorUsages_EmitsSinglePromptBuilder()
    {
        var source = """
            using System.ComponentModel;

            namespace LMP
            {
                public class Predictor<TInput, TOutput> where TOutput : class
                {
                    public Predictor(object client) { }
                }
            }

            namespace TestApp
            {
                using LMP;

                public record Input1(string Text);

                [LmpSignature("Test signature")]
                public partial record Output1
                {
                    [Description("Result")]
                    public required string Result { get; init; }
                }

                public class ModuleA
                {
                    private readonly Predictor<Input1, Output1> _a = null!;
                    private readonly Predictor<Input1, Output1> _b = null!;
                }
            }
            """;

        var (diagnostics, runResult) = RunGenerator(source);
        Assert.Empty(diagnostics);

        var promptBuilders = runResult.Results[0].GeneratedSources
            .Where(s => s.HintName.Contains("PromptBuilder"))
            .ToArray();
        Assert.Single(promptBuilders);
    }

    [Fact(Skip = "PredictorPairExtractor pipeline — Task 2.5")]
    public void Pipeline_PromptBuilder_ContainsInputFieldDescriptions()
    {
        var source = GetPipelineTestSource();
        var (_, runResult) = RunGenerator(source);

        var promptBuilder = runResult.GeneratedTrees
            .First(t => t.FilePath.Contains("PromptBuilder"));
        var text = promptBuilder.GetText().ToString();

        Assert.Contains("TicketText (string): The raw ticket text", text);
        Assert.Contains("AccountTier (string): Customer plan tier", text);
    }

    [Fact(Skip = "PredictorPairExtractor pipeline — Task 2.5")]
    public void Pipeline_PromptBuilder_ContainsOutputFieldDescriptions()
    {
        var source = GetPipelineTestSource();
        var (_, runResult) = RunGenerator(source);

        var promptBuilder = runResult.GeneratedTrees
            .First(t => t.FilePath.Contains("PromptBuilder"));
        var text = promptBuilder.GetText().ToString();

        Assert.Contains("Category (string): Category: billing, technical, account", text);
        Assert.Contains("Urgency (int): Urgency from 1 to 5", text);
    }

    #endregion

    #region Helpers

    private static PromptBuilderModel CreateFullModel(
        string ns = "TestApp",
        string outputTypeName = "ClassifyTicket",
        string inputTypeName = "TicketInput",
        string instructions = "Classify a support ticket by category and urgency")
    {
        var inputFields = new[]
        {
            new InputFieldModel("TicketText", "string", "The raw ticket text"),
            new InputFieldModel("AccountTier", "string", "Customer plan tier"),
        };

        var outputFields = new[]
        {
            CreateOutputField("Category", "string", "Category: billing, technical, account"),
            CreateOutputField("Urgency", "int", "Urgency from 1 (low) to 5 (critical)"),
        };

        return new PromptBuilderModel(
            Namespace: ns,
            OutputTypeName: outputTypeName,
            InputTypeName: inputTypeName,
            InputTypeFullyQualified: $"global::{ns}.{inputTypeName}",
            OutputTypeFullyQualified: $"global::{ns}.{outputTypeName}",
            Instructions: instructions,
            InputFields: new EquatableArray<InputFieldModel>(inputFields.ToImmutableArray()),
            OutputFields: new EquatableArray<OutputFieldModel>(outputFields.ToImmutableArray()));
    }

    private static PromptBuilderModel CreateModel(
        string inputTypeName = "TestInput",
        InputFieldModel[]? inputFields = null,
        OutputFieldModel[]? outputFields = null,
        string ns = "TestApp",
        string outputTypeName = "TestOutput",
        string instructions = "Test instructions")
    {
        return new PromptBuilderModel(
            Namespace: ns,
            OutputTypeName: outputTypeName,
            InputTypeName: inputTypeName,
            InputTypeFullyQualified: $"global::{ns}.{inputTypeName}",
            OutputTypeFullyQualified: $"global::{ns}.{outputTypeName}",
            Instructions: instructions,
            InputFields: new EquatableArray<InputFieldModel>(
                (inputFields ?? System.Array.Empty<InputFieldModel>()).ToImmutableArray()),
            OutputFields: new EquatableArray<OutputFieldModel>(
                (outputFields ?? System.Array.Empty<OutputFieldModel>()).ToImmutableArray()));
    }

    private static OutputFieldModel CreateOutputField(
        string name, string clrType, string? description, bool isRequired = false)
    {
        return new OutputFieldModel(
            Name: name,
            ClrTypeName: clrType,
            FullyQualifiedTypeName: "global::" + clrType,
            Description: description,
            IsRequired: isRequired,
            Location: default);
    }

    private static string GetPipelineTestSource() => """
        using System.ComponentModel;

        namespace LMP
        {
            public class Predictor<TInput, TOutput> where TOutput : class
            {
                public Predictor(object client) { }
            }
        }

        namespace TestApp
        {
            using LMP;

            public record TicketInput(
                [Description("The raw ticket text")] string TicketText,
                [Description("Customer plan tier")] string AccountTier);

            [LmpSignature("Classify a support ticket")]
            public partial record ClassifyTicket
            {
                [Description("Category: billing, technical, account")]
                public required string Category { get; init; }

                [Description("Urgency from 1 to 5")]
                public required int Urgency { get; init; }
            }

            public class TicketModule
            {
                private readonly Predictor<TicketInput, ClassifyTicket> _classify = null!;
            }
        }
        """;

    private static (Diagnostic[] Diagnostics, GeneratorDriverRunResult RunResult) RunGenerator(string source)
    {
        var compilation = CreateCompilation(source);

        var generator = new LmpSourceGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation, out _, out var diagnostics);

        return (diagnostics.ToArray(), driver.GetRunResult());
    }

    private static CSharpCompilation CreateCompilation(string source)
    {
        var syntaxTrees = string.IsNullOrWhiteSpace(source)
            ? []
            : new[] { CSharpSyntaxTree.ParseText(source) };

        return CSharpCompilation.Create(
            "TestAssembly",
            syntaxTrees: syntaxTrees,
            references:
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(LmpSignatureAttribute).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(System.ComponentModel.DescriptionAttribute).Assembly.Location),
                .. GetNetCoreReferences(),
            ],
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static MetadataReference[] GetNetCoreReferences()
    {
        var runtimeDir = System.IO.Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        return
        [
            MetadataReference.CreateFromFile(System.IO.Path.Combine(runtimeDir, "System.Runtime.dll")),
        ];
    }

    #endregion
}
