using System.Collections.Immutable;
using LMP.SourceGen;
using Xunit;

namespace LMP.SourceGen.Tests;

/// <summary>
/// Tests for Pipeline 8 — GetSkills() emission via SkillEmitter.
/// </summary>
public class SkillEmitterTests
{
    // ── Header / Boilerplate ─────────────────────────────────────

    [Fact]
    public void GenerateSource_IncludesAutoGeneratedHeader()
    {
        var model = CreateModel();
        var source = SkillEmitter.GenerateSource(model);
        Assert.StartsWith("// <auto-generated />", source);
        Assert.Contains("#nullable enable", source);
    }

    [Fact]
    public void GenerateSource_IncludesRequiredUsings()
    {
        var model = CreateModel();
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("using System.CodeDom.Compiler;", source);
        Assert.Contains("using System.Collections.Generic;", source);
        Assert.Contains("using LMP;", source);
    }

    [Fact]
    public void GenerateSource_IncludesGeneratedCodeAttribute()
    {
        var model = CreateModel();
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]", source);
    }

    // ── Namespace Handling ───────────────────────────────────────

    [Fact]
    public void GenerateSource_IncludesNamespace_WhenProvided()
    {
        var model = CreateModel(ns: "Demo.App");
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("namespace Demo.App;", source);
    }

    [Fact]
    public void GenerateSource_OmitsNamespaceBlock_WhenEmpty()
    {
        var model = CreateModel(ns: "");
        var source = SkillEmitter.GenerateSource(model);
        Assert.DoesNotContain("namespace", source);
    }

    // ── Class / Method Emission ──────────────────────────────────

    [Fact]
    public void GenerateSource_EmitsPartialClass()
    {
        var model = CreateModel(typeName: "MySkillModule");
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("partial class MySkillModule", source);
    }

    [Fact]
    public void GenerateSource_EmitsGetSkillsOverride()
    {
        var model = CreateModel();
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("public override", source);
        Assert.Contains("GetSkills()", source);
    }

    // ── Skill Entry Emission ─────────────────────────────────────

    [Fact]
    public void GenerateSource_EmitsPublicSkill_ByMethodName()
    {
        var model = CreateModel(methods: [PublicSkill("Search", null, null)]);
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("\"Search\"", source);
    }

    [Fact]
    public void GenerateSource_UsesNameOverride_WhenProvided()
    {
        var model = CreateModel(methods: [PublicSkill("SearchInternal", "web-search", null)]);
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("\"web-search\"", source);
        Assert.DoesNotContain("\"SearchInternal\"", source);
    }

    [Fact]
    public void GenerateSource_EmitsNullDescription_WhenAbsent()
    {
        var model = CreateModel(methods: [PublicSkill("Calculate", null, null)]);
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains(", null", source);
    }

    [Fact]
    public void GenerateSource_EmitsDescription_WhenProvided()
    {
        var model = CreateModel(methods: [PublicSkill("Calculate", null, "Evaluates math.")]);
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("\"Evaluates math.\"", source);
    }

    [Fact]
    public void GenerateSource_ExcludesNonPublicSkill()
    {
        var model = CreateModel(methods: [
            PublicSkill("PublicSkill", null, null),
            NonPublicSkill("PrivateSkill", null, null)
        ]);
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("\"PublicSkill\"", source);
        Assert.DoesNotContain("\"PrivateSkill\"", source);
    }

    [Fact]
    public void GenerateSource_EmptyList_WhenAllSkillsAreNonPublic()
    {
        var model = CreateModel(methods: [NonPublicSkill("Hidden", null, null)]);
        var source = SkillEmitter.GenerateSource(model);
        // Should emit empty collection expression
        Assert.Contains("[]", source);
        Assert.DoesNotContain("\"Hidden\"", source);
    }

    [Fact]
    public void GenerateSource_EmptyList_WhenNoMethods()
    {
        var model = CreateModel(methods: []);
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("[]", source);
    }

    [Fact]
    public void GenerateSource_MultipleSkills_AllPublicIncluded()
    {
        var model = CreateModel(methods: [
            PublicSkill("Search", null, "Searches"),
            PublicSkill("Calculate", null, "Evaluates")
        ]);
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("\"Search\"", source);
        Assert.Contains("\"Calculate\"", source);
    }

    // ── String Escaping ──────────────────────────────────────────

    [Fact]
    public void GenerateSource_EscapesSpecialCharsInDescription()
    {
        var model = CreateModel(methods: [PublicSkill("Search", null, "Searches \"the\" web.")]);
        var source = SkillEmitter.GenerateSource(model);
        Assert.Contains("\\\"the\\\"", source);
    }

    // ── Helpers ──────────────────────────────────────────────────

    private static SkillModuleModel CreateModel(
        string ns = "Demo.App",
        string typeName = "TestModule",
        SkillMethodModel[]? methods = null)
    {
        var defaultMethod = PublicSkill("DoWork", null, null);
        return new SkillModuleModel(
            ns,
            typeName,
            new EquatableArray<SkillMethodModel>((methods ?? [defaultMethod]).ToImmutableArray()));
    }

    private static SkillMethodModel PublicSkill(string name, string? nameOverride, string? description)
        => new(name, nameOverride, description, IsPublic: true, Location: default);

    private static SkillMethodModel NonPublicSkill(string name, string? nameOverride, string? description)
        => new(name, nameOverride, description, IsPublic: false, Location: default);
}
