using System.Collections.Immutable;
using LMP.SourceGen;
using Xunit;

namespace LMP.SourceGen.Tests;

/// <summary>
/// Tests for Pipeline 7 — GetTools() emission via ToolEmitter.
/// </summary>
public class ToolEmitterTests
{
    // ── Header / Boilerplate ─────────────────────────────────────

    [Fact]
    public void GenerateSource_IncludesAutoGeneratedHeader()
    {
        var model = CreateModel();
        var source = ToolEmitter.GenerateSource(model);
        Assert.StartsWith("// <auto-generated />", source);
        Assert.Contains("#nullable enable", source);
    }

    [Fact]
    public void GenerateSource_IncludesRequiredUsings()
    {
        var model = CreateModel();
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("using System.CodeDom.Compiler;", source);
        Assert.Contains("using System.Collections.Generic;", source);
    }

    [Fact]
    public void GenerateSource_IncludesGeneratedCodeAttribute()
    {
        var model = CreateModel();
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]", source);
    }

    // ── Namespace Handling ───────────────────────────────────────

    [Fact]
    public void GenerateSource_IncludesNamespace_WhenProvided()
    {
        var model = CreateModel(ns: "Demo.App");
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("namespace Demo.App;", source);
    }

    [Fact]
    public void GenerateSource_OmitsNamespaceBlock_WhenEmpty()
    {
        var model = CreateModel(ns: "");
        var source = ToolEmitter.GenerateSource(model);
        Assert.DoesNotContain("namespace", source);
    }

    // ── Class / Method Emission ──────────────────────────────────

    [Fact]
    public void GenerateSource_EmitsPartialClass()
    {
        var model = CreateModel(typeName: "MyToolModule");
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("partial class MyToolModule", source);
    }

    [Fact]
    public void GenerateSource_EmitsGetToolsOverride()
    {
        var model = CreateModel();
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("public override", source);
        Assert.Contains("GetTools()", source);
    }

    [Fact]
    public void GenerateSource_ReturnsIReadOnlyListOfAIFunction()
    {
        var model = CreateModel();
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("IReadOnlyList", source);
        Assert.Contains("AIFunction", source);
    }

    // ── AIFunctionFactory.Create Emission ────────────────────────

    [Fact]
    public void GenerateSource_EmitsAIFunctionFactory_Create()
    {
        var model = CreateModel(methods: [PublicAsyncTool("Search", null, null)]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("AIFunctionFactory.Create", source);
    }

    [Fact]
    public void GenerateSource_EmitsThisMethodReference()
    {
        var model = CreateModel(methods: [PublicAsyncTool("Search", null, null)]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("this.Search", source);
    }

    [Fact]
    public void GenerateSource_EmitsMethodNameAsToolName_WhenNoOverride()
    {
        var model = CreateModel(methods: [PublicAsyncTool("Search", null, null)]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("name: \"Search\"", source);
    }

    [Fact]
    public void GenerateSource_UsesNameOverride_WhenProvided()
    {
        var model = CreateModel(methods: [PublicAsyncTool("SearchInternal", "web-search", null)]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("name: \"web-search\"", source);
        Assert.DoesNotContain("name: \"SearchInternal\"", source);
    }

    [Fact]
    public void GenerateSource_EmitsDescriptionParam_WhenProvided()
    {
        var model = CreateModel(methods: [PublicAsyncTool("Search", null, "Searches the web.")]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("description: \"Searches the web.\"", source);
    }

    [Fact]
    public void GenerateSource_OmitsDescriptionParam_WhenAbsent()
    {
        var model = CreateModel(methods: [PublicAsyncTool("Search", null, null)]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.DoesNotContain("description:", source);
    }

    // ── Method Exclusion ─────────────────────────────────────────

    [Fact]
    public void GenerateSource_ExcludesStaticMethod()
    {
        var model = CreateModel(methods: [
            PublicAsyncTool("PublicTool", null, null),
            StaticTool("StaticTool", null, null)
        ]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("this.PublicTool", source);
        Assert.DoesNotContain("StaticTool", source);
    }

    [Fact]
    public void GenerateSource_ExcludesNonPublicMethod()
    {
        var model = CreateModel(methods: [
            PublicAsyncTool("PublicTool", null, null),
            NonPublicTool("PrivateTool", null, null)
        ]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("this.PublicTool", source);
        Assert.DoesNotContain("PrivateTool", source);
    }

    [Fact]
    public void GenerateSource_EmptyList_WhenAllMethodsExcluded()
    {
        var model = CreateModel(methods: [StaticTool("Hidden", null, null)]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("[]", source);
        Assert.DoesNotContain("Hidden", source);
    }

    [Fact]
    public void GenerateSource_EmptyList_WhenNoMethods()
    {
        var model = CreateModel(methods: []);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("[]", source);
    }

    // ── Multiple Tools ───────────────────────────────────────────

    [Fact]
    public void GenerateSource_MultipleTools_AllPublicIncluded()
    {
        var model = CreateModel(methods: [
            PublicAsyncTool("Search", null, "Searches"),
            PublicAsyncTool("Calculate", null, "Evaluates")
        ]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("this.Search", source);
        Assert.Contains("this.Calculate", source);
    }

    // ── Non-Async Tool Emission (LMP020 warning but still emitted) ──

    [Fact]
    public void GenerateSource_StillEmitsNonAsyncTool()
    {
        var model = CreateModel(methods: [NonAsyncTool("SyncTool", null, null)]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("this.SyncTool", source);
    }

    // ── String Escaping ──────────────────────────────────────────

    [Fact]
    public void GenerateSource_EscapesSpecialCharsInDescription()
    {
        var model = CreateModel(methods: [PublicAsyncTool("Search", null, "Searches \"the\" web.")]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("\\\"the\\\"", source);
    }

    [Fact]
    public void GenerateSource_EscapesSpecialCharsInNameOverride()
    {
        var model = CreateModel(methods: [PublicAsyncTool("Search", "search\\tool", null)]);
        var source = ToolEmitter.GenerateSource(model);
        Assert.Contains("search\\\\tool", source);
    }

    // ── Helpers ──────────────────────────────────────────────────

    private static ToolModuleModel CreateModel(
        string ns = "Demo.App",
        string typeName = "TestModule",
        ToolMethodModel[]? methods = null)
    {
        var defaultMethod = PublicAsyncTool("DoWork", null, null);
        return new ToolModuleModel(
            ns,
            typeName,
            new EquatableArray<ToolMethodModel>((methods ?? [defaultMethod]).ToImmutableArray()));
    }

    private static ToolMethodModel PublicAsyncTool(string name, string? nameOverride, string? description)
        => new(name, nameOverride, description,
               IsPublic: true, IsAsync: true, IsStatic: false, ParameterCount: 1, Location: default);

    private static ToolMethodModel NonPublicTool(string name, string? nameOverride, string? description)
        => new(name, nameOverride, description,
               IsPublic: false, IsAsync: true, IsStatic: false, ParameterCount: 1, Location: default);

    private static ToolMethodModel StaticTool(string name, string? nameOverride, string? description)
        => new(name, nameOverride, description,
               IsPublic: true, IsAsync: true, IsStatic: true, ParameterCount: 1, Location: default);

    private static ToolMethodModel NonAsyncTool(string name, string? nameOverride, string? description)
        => new(name, nameOverride, description,
               IsPublic: true, IsAsync: false, IsStatic: false, ParameterCount: 1, Location: default);
}
