using LMP.Cli.Infrastructure;

namespace LMP.Tests;

public class CSharpArtifactWriterTests
{
    #region IsUpToDate

    [Fact]
    public async Task IsUpToDate_MissingGeneratedFile_ReturnsFalse()
    {
        var result = await CSharpArtifactWriter.IsUpToDateAsync(
            "nonexistent.g.cs", "nonexistent.jsonl", CancellationToken.None);
        Assert.False(result);
    }

    [Fact]
    public async Task IsUpToDate_MissingTrainFile_ReturnsFalse()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"lmp-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var generatedPath = Path.Combine(tempDir, "Test.Optimized.g.cs");
            await File.WriteAllTextAsync(generatedPath, "// Dataset: sha256:abc123\n");

            var result = await CSharpArtifactWriter.IsUpToDateAsync(
                generatedPath, "nonexistent.jsonl", CancellationToken.None);
            Assert.False(result);
        }
        finally
        {
            Directory.Delete(tempDir, recursive: true);
        }
    }

    [Fact]
    public async Task IsUpToDate_MatchingHash_ReturnsTrue()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"lmp-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var trainPath = Path.Combine(tempDir, "train.jsonl");
            await File.WriteAllTextAsync(trainPath, """{"input":"test","output":"result"}""");

            // Compute expected hash (first 16 hex chars of SHA256)
            using var stream = File.OpenRead(trainPath);
            var hashBytes = await System.Security.Cryptography.SHA256.HashDataAsync(stream);
            var expectedHash = Convert.ToHexStringLower(hashBytes)[..16];

            var generatedPath = Path.Combine(tempDir, "Test.Optimized.g.cs");
            await File.WriteAllTextAsync(generatedPath, $$"""
                // <auto-generated>
                // LMP Auto-Optimize | Score: 0.9000 | Strategy: random
                // Dataset: sha256:{{expectedHash}}
                // Generated: 2025-01-01T00:00:00Z
                // </auto-generated>
                partial class TestModule { }
                """);

            var result = await CSharpArtifactWriter.IsUpToDateAsync(
                generatedPath, trainPath, CancellationToken.None);
            Assert.True(result);
        }
        finally
        {
            Directory.Delete(tempDir, recursive: true);
        }
    }

    [Fact]
    public async Task IsUpToDate_DifferentHash_ReturnsFalse()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"lmp-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var trainPath = Path.Combine(tempDir, "train.jsonl");
            await File.WriteAllTextAsync(trainPath, """{"input":"test","output":"result"}""");

            var generatedPath = Path.Combine(tempDir, "Test.Optimized.g.cs");
            await File.WriteAllTextAsync(generatedPath, """
                // <auto-generated>
                // LMP Auto-Optimize | Score: 0.9000 | Strategy: random
                // Dataset: sha256:0000000000000000
                // Generated: 2025-01-01T00:00:00Z
                // </auto-generated>
                partial class TestModule { }
                """);

            var result = await CSharpArtifactWriter.IsUpToDateAsync(
                generatedPath, trainPath, CancellationToken.None);
            Assert.False(result);
        }
        finally
        {
            Directory.Delete(tempDir, recursive: true);
        }
    }

    #endregion

    #region Header Parsing Edge Cases

    [Fact]
    public async Task IsUpToDate_NoDatasetLine_ReturnsFalse()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"lmp-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var trainPath = Path.Combine(tempDir, "train.jsonl");
            await File.WriteAllTextAsync(trainPath, "data");

            var generatedPath = Path.Combine(tempDir, "Test.Optimized.g.cs");
            await File.WriteAllTextAsync(generatedPath, """
                // <auto-generated>
                // Some comment without dataset hash
                // </auto-generated>
                partial class TestModule { }
                """);

            var result = await CSharpArtifactWriter.IsUpToDateAsync(
                generatedPath, trainPath, CancellationToken.None);
            Assert.False(result);
        }
        finally
        {
            Directory.Delete(tempDir, recursive: true);
        }
    }

    [Fact]
    public async Task IsUpToDate_EmptyFile_ReturnsFalse()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"lmp-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var trainPath = Path.Combine(tempDir, "train.jsonl");
            await File.WriteAllTextAsync(trainPath, "data");

            var generatedPath = Path.Combine(tempDir, "Test.Optimized.g.cs");
            await File.WriteAllTextAsync(generatedPath, "");

            var result = await CSharpArtifactWriter.IsUpToDateAsync(
                generatedPath, trainPath, CancellationToken.None);
            Assert.False(result);
        }
        finally
        {
            Directory.Delete(tempDir, recursive: true);
        }
    }

    #endregion
}
