using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits <c>{TypeName}WithReasoning</c> internal record and its
/// <c>JsonSerializerContext</c> for ChainOfThought extended output types.
/// </summary>
internal static class ChainOfThoughtEmitter
{
    /// <summary>
    /// Generates the full source code for the extended output record and its JsonContext.
    /// </summary>
    internal static string GenerateSource(ChainOfThoughtModel model)
    {
        var sb = new StringBuilder(1024);

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        // XML doc
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extended output type for ChainOfThought reasoning.");
        sb.AppendLine("/// The Reasoning field is sent to the LM as an additional output field");
        sb.AppendLine("/// positioned before the real output fields, encouraging step-by-step thinking.");
        sb.AppendLine("/// </summary>");

        // Record declaration
        sb.AppendLine("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.Append("internal partial record ").Append(model.OutputTypeName).AppendLine("WithReasoning");
        sb.AppendLine("{");

        // Reasoning field — first via [JsonPropertyOrder(-1)]
        sb.AppendLine("    [Description(\"Think step by step to work toward the answer\")]");
        sb.AppendLine("    [JsonPropertyOrder(-1)]");
        sb.AppendLine("    public required string Reasoning { get; init; }");

        // Copy all original output fields with their descriptions
        foreach (var field in model.OutputFields)
        {
            sb.AppendLine();
            if (!string.IsNullOrEmpty(field.Description))
            {
                sb.Append("    [Description(\"")
                  .Append(EscapeStringLiteral(field.Description!))
                  .AppendLine("\")]");
            }
            sb.Append("    public ");
            if (field.IsRequired)
                sb.Append("required ");
            sb.Append(field.ClrTypeName).Append(' ').Append(field.Name).AppendLine(" { get; init; }");
        }

        // Close record
        sb.AppendLine("}");
        sb.AppendLine();

        // JsonSerializerOptions for the extended type
        sb.AppendLine("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.Append("internal static class ").Append(model.OutputTypeName).AppendLine("WithReasoningJsonOptions");
        sb.AppendLine("{");
        sb.Append("    internal static readonly JsonSerializerOptions Instance = new(JsonSerializerDefaults.Web)");
        sb.AppendLine();
        sb.AppendLine("    {");
        sb.AppendLine("        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,");
        sb.AppendLine("        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
        sb.AppendLine("        TypeInfoResolver = new DefaultJsonTypeInfoResolver(),");
        sb.AppendLine("        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase) }");
        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the ChainOfThought extended output source into the <see cref="SourceProductionContext"/>.
    /// </summary>
    public static void Emit(SourceProductionContext context, ChainOfThoughtModel model)
    {
        var source = GenerateSource(model);
        context.AddSource(
            $"{model.OutputTypeName}.ChainOfThought.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    private static string EscapeStringLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}
