using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits interceptor methods for <c>PredictAsync</c> call sites.
/// Each interceptor wires the type-specific PromptBuilder before delegating
/// to the original <c>PredictAsync</c> implementation for zero-overhead prompt assembly.
/// </summary>
internal static class InterceptorEmitter
{
    /// <summary>
    /// Generates interceptor source for a collection of call sites.
    /// Groups by (InputType, OutputType) to share interceptor logic,
    /// and emits one <c>[InterceptsLocation]</c> attribute per call site.
    /// </summary>
    internal static string GenerateSource(ImmutableArray<InterceptorCallSiteModel> callSites)
    {
        if (callSites.IsDefaultOrEmpty)
            return string.Empty;

        var sb = new StringBuilder(2048);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.AI;");
        sb.AppendLine();

        // Emit file-local InterceptsLocationAttribute declaration
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute(int version, string data) : Attribute;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Group call sites by (InputTypeFQN, OutputTypeFQN) — each group shares an interceptor method
        var groups = callSites
            .GroupBy(cs => (cs.InputTypeFQN, cs.OutputTypeFQN, cs.OutputTypeName, cs.Namespace))
            .ToList();

        sb.AppendLine("namespace LMP.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    [GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.AppendLine("    file static class LmpInterceptors");
        sb.AppendLine("    {");

        int methodIndex = 0;
        foreach (var group in groups)
        {
            if (methodIndex > 0)
                sb.AppendLine();

            var key = group.Key;
            var sites = group.ToList();

            // Emit [InterceptsLocation] for each call site in this group
            foreach (var site in sites)
            {
                sb.Append("        // ").AppendLine(site.DisplayLocation);
                sb.Append("        [InterceptsLocation(")
                  .Append(site.LocationVersion)
                  .Append(", \"")
                  .Append(site.LocationData)
                  .AppendLine("\")]");
            }

            // Emit the interceptor method
            sb.Append("        public static async Task<").Append(key.OutputTypeFQN).Append("> PredictAsync_").Append(methodIndex).AppendLine("(");
            sb.Append("            this global::LMP.Predictor<").Append(key.InputTypeFQN).Append(", ").Append(key.OutputTypeFQN).AppendLine("> self,");
            sb.Append("            ").Append(key.InputTypeFQN).AppendLine(" input,");
            sb.AppendLine("            global::LMP.Trace? trace = null,");
            sb.Append("            Action<").Append(key.OutputTypeFQN).AppendLine(">? validate = null,");
            sb.AppendLine("            int maxRetries = 3,");
            sb.AppendLine("            CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");

            // Wire the PromptBuilder delegate — SetPromptBuilder is no-op if already set
            var promptBuilderFqn = string.IsNullOrEmpty(key.Namespace)
                ? $"global::{key.OutputTypeName}PromptBuilder"
                : $"global::{key.Namespace}.{key.OutputTypeName}PromptBuilder";

            sb.Append("            self.SetPromptBuilder(").Append(promptBuilderFqn).AppendLine(".BuildMessages);");
            sb.AppendLine("            return await self.PredictAsync(input, trace, validate, maxRetries, cancellationToken).ConfigureAwait(false);");
            sb.AppendLine("        }");

            methodIndex++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the interceptor source into the <see cref="SourceProductionContext"/>.
    /// </summary>
    public static void Emit(SourceProductionContext context, ImmutableArray<InterceptorCallSiteModel> callSites)
    {
        var source = GenerateSource(callSites);
        if (string.IsNullOrEmpty(source))
            return;

        context.AddSource(
            "LmpInterceptors.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }
}
