using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits interceptor methods for <c>PredictAsync</c> call sites.
/// Each interceptor inlines the full predict logic — prompt building via the
/// type-specific PromptBuilder, <c>GetResponseAsync&lt;T&gt;</c>, trace recording,
/// and retry-on-assertion — eliminating virtual dispatch overhead.
/// Falls back to the original virtual <c>PredictAsync</c> for derived predictor types.
/// </summary>
internal static class InterceptorEmitter
{
    /// <summary>
    /// Generates interceptor source for a collection of call sites.
    /// Groups by (InputType, OutputType) to share interceptor logic,
    /// and emits one <c>[InterceptsLocation]</c> attribute per call site.
    /// </summary>
    internal static string GenerateSource(ImmutableArray<InterceptorCallSiteModel> callSites)
    {
        if (callSites.IsDefaultOrEmpty)
            return string.Empty;

        var sb = new StringBuilder(4096);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.AI;");
        sb.AppendLine();

        // Emit file-local InterceptsLocationAttribute declaration
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute(int version, string data) : Attribute;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Group call sites by (InputTypeFQN, OutputTypeFQN) — each group shares an interceptor method
        var groups = GroupByTypePair(callSites);

        sb.AppendLine("namespace LMP.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    [GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.AppendLine("    file static class LmpInterceptors");
        sb.AppendLine("    {");

        int methodIndex = 0;
        foreach (var group in groups)
        {
            if (methodIndex > 0)
                sb.AppendLine();

            EmitInterceptorMethod(sb, group.Key, group.Value, methodIndex);
            methodIndex++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the interceptor source into the <see cref="SourceProductionContext"/>.
    /// </summary>
    public static void Emit(SourceProductionContext context, ImmutableArray<InterceptorCallSiteModel> callSites)
    {
        var source = GenerateSource(callSites);
        if (string.IsNullOrEmpty(source))
            return;

        context.AddSource(
            "LmpInterceptors.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    private static List<KeyValuePair<InterceptorTypeKey, List<InterceptorCallSiteModel>>> GroupByTypePair(
        ImmutableArray<InterceptorCallSiteModel> callSites)
    {
        var dict = new Dictionary<InterceptorTypeKey, List<InterceptorCallSiteModel>>();
        foreach (var site in callSites)
        {
            var key = new InterceptorTypeKey(site.InputTypeFQN, site.OutputTypeFQN, site.OutputTypeName, site.Namespace);
            if (!dict.TryGetValue(key, out var list))
            {
                list = new List<InterceptorCallSiteModel>();
                dict[key] = list;
            }
            list.Add(site);
        }
        return dict.ToList();
    }

    private static void EmitInterceptorMethod(
        StringBuilder sb,
        InterceptorTypeKey key,
        List<InterceptorCallSiteModel> sites,
        int methodIndex)
    {
        // Emit [InterceptsLocation] for each call site in this group
        foreach (var site in sites)
        {
            sb.Append("        // ").AppendLine(site.DisplayLocation);
            sb.Append("        [InterceptsLocation(")
              .Append(site.LocationVersion)
              .Append(", \"")
              .Append(site.LocationData)
              .AppendLine("\")]");
        }

        // Emit the interceptor method signature
        sb.Append("        public static async Task<").Append(key.OutputTypeFQN).Append("> PredictAsync_").Append(methodIndex).AppendLine("(");
        sb.Append("            this global::LMP.Predictor<").Append(key.InputTypeFQN).Append(", ").Append(key.OutputTypeFQN).AppendLine("> self,");
        sb.Append("            ").Append(key.InputTypeFQN).AppendLine(" input,");
        sb.AppendLine("            global::LMP.Trace? trace = null,");
        sb.Append("            Action<").Append(key.OutputTypeFQN).AppendLine(">? validate = null,");
        sb.AppendLine("            int maxRetries = 3,");
        sb.AppendLine("            CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");

        // Guard: fall back to virtual dispatch for derived predictor types
        sb.Append("            if (self.GetType() != typeof(global::LMP.Predictor<")
          .Append(key.InputTypeFQN).Append(", ").Append(key.OutputTypeFQN).AppendLine(">))");
        sb.AppendLine("                return await self.PredictAsync(input, trace, validate, maxRetries, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine();

        // Resolve the PromptBuilder FQN
        var promptBuilderFqn = string.IsNullOrEmpty(key.Namespace)
            ? $"global::{key.OutputTypeName}PromptBuilder"
            : $"global::{key.Namespace}.{key.OutputTypeName}PromptBuilder";

        // Inlined PredictAsync logic: retry loop with direct PromptBuilder calls
        sb.AppendLine("            string? lastError = null;");
        sb.AppendLine("            for (int attempt = 0; attempt <= maxRetries; attempt++)");
        sb.AppendLine("            {");

        // Use PromptBuilder's DefaultInstructions if predictor's Instructions are empty
        sb.Append("                var effectiveInstructions = string.IsNullOrEmpty(self.Instructions) ? ")
          .Append(promptBuilderFqn).AppendLine(".DefaultInstructions : self.Instructions;");

        // Build messages via PromptBuilder (no virtual dispatch, no delegate)
        sb.Append("                var messages = ").Append(promptBuilderFqn)
          .AppendLine(".BuildMessages(effectiveInstructions, input, self.Demos, lastError);");
        sb.AppendLine();

        // Direct GetResponseAsync<T> call via the exposed Client property
        sb.Append("                var response = await self.Client.GetResponseAsync<").Append(key.OutputTypeFQN)
          .AppendLine(">(messages, self.Config, cancellationToken: cancellationToken).ConfigureAwait(false);");
        sb.AppendLine();

        sb.AppendLine("                var result = response.Result");
        sb.AppendLine("                    ?? throw new InvalidOperationException($\"Predictor '{self.Name}': structured output returned null.\");");
        sb.AppendLine();

        // Trace recording
        sb.AppendLine("                trace?.Record(self.Name, input!, result, response.Usage);");
        sb.AppendLine();

        // Validation and early return
        sb.AppendLine("                if (validate is null)");
        sb.AppendLine("                    return result;");
        sb.AppendLine();
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine("                    validate(result);");
        sb.AppendLine("                    return result;");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (global::LMP.LmpAssertionException ex)");
        sb.AppendLine("                {");
        sb.AppendLine("                    lastError = ex.Message;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();

        // Max retries exceeded
        sb.AppendLine("            throw new global::LMP.LmpMaxRetriesExceededException(self.Name, maxRetries);");
        sb.AppendLine("        }");
    }

    /// <summary>Key for grouping interceptor call sites by their type pair.</summary>
    private readonly struct InterceptorTypeKey : System.IEquatable<InterceptorTypeKey>
    {
        public readonly string InputTypeFQN;
        public readonly string OutputTypeFQN;
        public readonly string OutputTypeName;
        public readonly string Namespace;

        public InterceptorTypeKey(string inputTypeFQN, string outputTypeFQN, string outputTypeName, string ns)
        {
            InputTypeFQN = inputTypeFQN;
            OutputTypeFQN = outputTypeFQN;
            OutputTypeName = outputTypeName;
            Namespace = ns;
        }

        public bool Equals(InterceptorTypeKey other)
            => InputTypeFQN == other.InputTypeFQN && OutputTypeFQN == other.OutputTypeFQN;

        public override bool Equals(object obj)
            => obj is InterceptorTypeKey other && Equals(other);

        public override int GetHashCode()
        {
            unchecked
            {
                return (InputTypeFQN.GetHashCode() * 397) ^ OutputTypeFQN.GetHashCode();
            }
        }
    }
}
