using System.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits a <c>file partial class {TypeName}JsonContext : JsonSerializerContext</c>
/// that provides AOT-safe, zero-reflection JSON serialization for
/// <c>[LmpSignature]</c> output types.
/// </summary>
internal static class JsonContextEmitter
{
    /// <summary>
    /// Generates the full JsonContext source code for the given output type model.
    /// Returns <c>null</c> if the model is not a valid partial record.
    /// </summary>
    internal static string? GenerateSource(OutputTypeModel model)
    {
        if (!model.IsPartialRecord)
            return null;

        var sb = new StringBuilder(512);

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ");
            sb.Append(model.Namespace);
            sb.AppendLine(";");
            sb.AppendLine();
        }

        // Static helper class with JsonSerializerOptions
        sb.AppendLine("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.Append("file static class ");
        sb.Append(model.TypeName);
        sb.AppendLine("JsonOptions");
        sb.AppendLine("{");
        sb.Append("    internal static readonly JsonSerializerOptions Instance = new(JsonSerializerDefaults.Web)");
        sb.AppendLine();
        sb.AppendLine("    {");
        sb.AppendLine("        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,");
        sb.AppendLine("        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
        sb.AppendLine("        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase) }");
        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the JsonContext source into the <see cref="Microsoft.CodeAnalysis.SourceProductionContext"/>.
    /// Skips emission if the model is not valid.
    /// </summary>
    public static void Emit(Microsoft.CodeAnalysis.SourceProductionContext context, OutputTypeModel model)
    {
        var source = GenerateSource(model);
        if (source is null)
            return;

        context.AddSource(
            $"{model.TypeName}.JsonContext.g.cs",
            Microsoft.CodeAnalysis.Text.SourceText.From(source, Encoding.UTF8));
    }
}
