using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits <c>partial class {ModuleName}</c> with an overridden <c>GetPredictors()</c>
/// method and a <c>CloneCore()</c> method for deep-copying the module with
/// independent predictor state.
/// </summary>
internal static class ModuleEmitter
{
    /// <summary>
    /// Generates the full source code for the <c>GetPredictors()</c> and
    /// <c>CloneCore()</c> overrides.
    /// </summary>
    internal static string GenerateSource(ModuleModel model)
    {
        var sb = new StringBuilder(1024);

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using LMP;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        // Class declaration
        sb.AppendLine("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.Append("partial class ").AppendLine(model.TypeName);
        sb.AppendLine("{");

        EmitGetPredictors(sb, model);
        sb.AppendLine();
        EmitCloneCore(sb, model);

        // Close class
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the GetPredictors and CloneCore source into the <see cref="SourceProductionContext"/>.
    /// </summary>
    public static void Emit(SourceProductionContext context, ModuleModel model)
    {
        var source = GenerateSource(model);
        context.AddSource(
            $"{model.TypeName}.Predictors.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    private static void EmitGetPredictors(StringBuilder sb, ModuleModel model)
    {
        sb.AppendLine("    public override IReadOnlyList<(string Name, IPredictor Predictor)> GetPredictors()");
        sb.AppendLine("        =>");
        sb.AppendLine("        [");

        for (int i = 0; i < model.PredictorFields.Count; i++)
        {
            var field = model.PredictorFields[i];
            var name = StripUnderscorePrefix(field.FieldName);
            sb.Append("            (\"").Append(name).Append("\", ").Append(field.FieldName).AppendLine("),");
        }

        sb.AppendLine("        ];");
    }

    private static void EmitCloneCore(StringBuilder sb, ModuleModel model)
    {
        sb.AppendLine("    protected override LmpModule CloneCore()");
        sb.AppendLine("    {");
        sb.Append("        var clone = (").Append(model.TypeName).AppendLine(")MemberwiseClone();");

        foreach (var field in model.PredictorFields)
        {
            var typeFqn = ResolveFieldTypeFQN(field);

            if (field.CanAssignDirectly)
            {
                // Direct assignment for non-readonly fields/properties
                sb.Append("        clone.").Append(field.FieldName)
                  .Append(" = (").Append(typeFqn).Append(")((global::LMP.IPredictor)")
                  .Append(field.FieldName).AppendLine(").Clone();");
            }
            else
            {
                // UnsafeAccessor for readonly fields or get-only properties
                var accessorName = "__cloneRef_" + SanitizeForIdentifier(field.FieldName);
                sb.Append("        ").Append(accessorName).Append("(clone) = (")
                  .Append(typeFqn).Append(")((global::LMP.IPredictor)")
                  .Append(field.FieldName).AppendLine(").Clone();");
            }
        }

        sb.AppendLine("        return clone;");
        sb.AppendLine("    }");

        // Emit UnsafeAccessor stubs for readonly fields
        foreach (var field in model.PredictorFields)
        {
            if (field.CanAssignDirectly)
                continue;

            var typeFqn = ResolveFieldTypeFQN(field);
            var accessorName = "__cloneRef_" + SanitizeForIdentifier(field.FieldName);
            sb.AppendLine();
            sb.Append("    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = \"")
              .Append(field.UnsafeAccessorFieldName).AppendLine("\")]");
            sb.Append("    private static extern ref ").Append(typeFqn)
              .Append(' ').Append(accessorName).Append('(')
              .Append(model.TypeName).AppendLine(" instance);");
        }
    }

    /// <summary>
    /// Returns the resolved FQN for the predictor field type.
    /// Falls back to <c>global::LMP.Predictor&lt;InputFQN, OutputFQN&gt;</c> when
    /// <see cref="PredictorFieldModel.FieldTypeFQN"/> is empty.
    /// </summary>
    private static string ResolveFieldTypeFQN(PredictorFieldModel field)
    {
        return string.IsNullOrEmpty(field.FieldTypeFQN)
            ? "global::LMP.Predictor<" + field.InputTypeFQN + ", " + field.OutputTypeFQN + ">"
            : field.FieldTypeFQN;
    }

    /// <summary>
    /// Strips leading underscore from field names for the predictor name string.
    /// E.g., <c>_classify</c> becomes <c>classify</c>.
    /// </summary>
    private static string StripUnderscorePrefix(string fieldName)
    {
        return fieldName.StartsWith("_") && fieldName.Length > 1
            ? fieldName.Substring(1)
            : fieldName;
    }

    /// <summary>
    /// Sanitizes a field name for use as part of a C# identifier.
    /// Replaces &lt; and &gt; with underscores for backing field names.
    /// </summary>
    private static string SanitizeForIdentifier(string name)
    {
        return name.Replace('<', '_').Replace('>', '_');
    }
}
