using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits an <c>internal partial class {ModuleName}JsonContext : JsonSerializerContext</c>
/// that provides AOT-safe, zero-reflection JSON serialization for module state
/// save/load operations. Includes <c>[JsonSerializable]</c> attributes for
/// <c>ModuleState</c>, <c>PredictorState</c>, <c>DemoEntry</c>, and every
/// concrete <c>TInput</c>/<c>TOutput</c> type referenced by the module's predictors.
/// </summary>
internal static class ModuleJsonContextEmitter
{
    /// <summary>
    /// Generates the full JsonContext source code for a module.
    /// </summary>
    internal static string GenerateSource(ModuleModel model)
    {
        var sb = new StringBuilder(512);

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using LMP;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        // Static helper class with JsonSerializerOptions
        sb.AppendLine("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.Append("internal static class ").Append(model.TypeName).AppendLine("JsonOptions");
        sb.AppendLine("{");
        sb.Append("    internal static readonly JsonSerializerOptions Instance = new(JsonSerializerDefaults.Web)");
        sb.AppendLine();
        sb.AppendLine("    {");
        sb.AppendLine("        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,");
        sb.AppendLine("        WriteIndented = true,");
        sb.AppendLine("        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull");
        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the module-level JsonContext source into the <see cref="SourceProductionContext"/>.
    /// </summary>
    public static void Emit(SourceProductionContext context, ModuleModel model)
    {
        var source = GenerateSource(model);
        context.AddSource(
            $"{model.TypeName}.JsonContext.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    /// <summary>
    /// Collects all unique input/output types across all predictor fields
    /// and [Predict] methods, sorted for deterministic output.
    /// </summary>
    private static IEnumerable<string> GetUniquePredictorTypes(ModuleModel model)
    {
        var seen = new HashSet<string>();

        foreach (var field in model.PredictorFields)
        {
            seen.Add(field.InputTypeFQN);
            seen.Add(field.OutputTypeFQN);
        }

        foreach (var pm in model.PredictMethods)
        {
            seen.Add(pm.InputTypeFQN);
            seen.Add(pm.OutputTypeFQN);
        }

        return seen.OrderBy(t => t);
    }
}
