using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits <c>partial class {ModuleName}</c> with an overridden <c>GetPredictors()</c>
/// method and a <c>CloneCore()</c> method for deep-copying the module with
/// independent predictor state.
/// </summary>
internal static class ModuleEmitter
{
    /// <summary>
    /// Generates the full source code for the <c>GetPredictors()</c> and
    /// <c>CloneCore()</c> overrides.
    /// </summary>
    internal static string GenerateSource(ModuleModel model)
    {
        var sb = new StringBuilder(1024);

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using LMP;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        // Class declaration
        sb.AppendLine("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.Append("partial class ").AppendLine(model.TypeName);
        sb.AppendLine("{");

        // [AutoOptimize] once-guard field
        if (model.HasAutoOptimize)
        {
            sb.AppendLine("    private bool __optimizedStateApplied;");
            sb.AppendLine();
        }

        // [Predict] backing fields
        if (model.PredictMethods.Count > 0)
        {
            EmitPredictBackingFields(sb, model);
            sb.AppendLine();
            EmitPredictMethodBodies(sb, model);
            sb.AppendLine();
        }

        EmitGetPredictors(sb, model);
        sb.AppendLine();
        EmitCloneCore(sb, model);

        // For [AutoOptimize] modules: emit partial void declaration + call site.
        // If no .g.cs implementation exists, the compiler removes both (C# partial void rules).
        if (model.HasAutoOptimize)
        {
            sb.AppendLine();
            EmitAutoOptimizeHook(sb, model);
        }

        // Close class
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the GetPredictors and CloneCore source into the <see cref="SourceProductionContext"/>.
    /// </summary>
    public static void Emit(SourceProductionContext context, ModuleModel model)
    {
        var source = GenerateSource(model);
        context.AddSource(
            $"{model.TypeName}.Predictors.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    private static void EmitGetPredictors(StringBuilder sb, ModuleModel model)
    {
        sb.AppendLine("    public override IReadOnlyList<(string Name, IPredictor Predictor)> GetPredictors()");
        sb.AppendLine("    {");

        // [AutoOptimize] — apply optimized state once on first call
        if (model.HasAutoOptimize)
        {
            sb.AppendLine("        if (!__optimizedStateApplied)");
            sb.AppendLine("        {");
            sb.AppendLine("            __optimizedStateApplied = true;");
            sb.AppendLine("            ApplyOptimizedState();");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // Ensure [Predict] backing fields are initialized
        foreach (var pm in model.PredictMethods)
        {
            var backingField = PredictBackingFieldName(pm.MethodName);
            sb.Append("        ").Append(backingField)
              .Append(" ??= new global::LMP.Predictor<").Append(pm.InputTypeFQN)
              .Append(", ").Append(pm.OutputTypeFQN)
              .AppendLine(">(Client ?? throw new global::System.InvalidOperationException(\"Set Client before calling GetPredictors().\"));");
        }

        // Wire SerializerOptions from the generated JsonOptions helper
        var jsonOptionsName = model.TypeName + "JsonOptions";
        foreach (var field in model.PredictorFields)
        {
            sb.Append("        ").Append(field.FieldName)
              .Append(".SerializerOptions ??= ").Append(jsonOptionsName).AppendLine(".Instance;");
        }
        foreach (var pm in model.PredictMethods)
        {
            var backingField = PredictBackingFieldName(pm.MethodName);
            sb.Append("        ").Append(backingField)
              .Append(".SerializerOptions ??= ").Append(jsonOptionsName).AppendLine(".Instance;");
        }

        // Initialize Instructions to DefaultInstructions on first call (if caller hasn't set them).
        // This ensures GEPA and other tools see the actual effective instruction, not an empty string.
        foreach (var field in model.PredictorFields)
        {
            var promptBuilderFqn = field.OutputTypeFQN + "PromptBuilder";
            sb.Append("        if (string.IsNullOrEmpty(").Append(field.FieldName).AppendLine(".Instructions))");
            sb.Append("            ").Append(field.FieldName)
              .Append(".Instructions = ").Append(promptBuilderFqn).AppendLine(".DefaultInstructions;");
        }
        foreach (var pm in model.PredictMethods)
        {
            var backingField = PredictBackingFieldName(pm.MethodName);
            var promptBuilderFqn = pm.OutputTypeFQN + "PromptBuilder";
            sb.Append("        if (string.IsNullOrEmpty(").Append(backingField).AppendLine(".Instructions))");
            sb.Append("            ").Append(backingField)
              .Append(".Instructions = ").Append(promptBuilderFqn).AppendLine(".DefaultInstructions;");
        }

        sb.AppendLine("        return");
        sb.AppendLine("        [");

        foreach (var field in model.PredictorFields)
        {
            var name = StripUnderscorePrefix(field.FieldName);
            sb.Append("            (\"").Append(name).Append("\", ").Append(field.FieldName).AppendLine("),");
        }

        foreach (var pm in model.PredictMethods)
        {
            var backingField = PredictBackingFieldName(pm.MethodName);
            sb.Append("            (\"").Append(pm.MethodName).Append("\", ").Append(backingField).AppendLine("),");
        }

        sb.AppendLine("        ];");
        sb.AppendLine("    }");
    }

    private static void EmitPredictBackingFields(StringBuilder sb, ModuleModel model)
    {
        foreach (var pm in model.PredictMethods)
        {
            var backingField = PredictBackingFieldName(pm.MethodName);
            sb.Append("    private global::LMP.Predictor<").Append(pm.InputTypeFQN)
              .Append(", ").Append(pm.OutputTypeFQN).Append(">? ")
              .Append(backingField).AppendLine(";");
        }
    }

    private static void EmitPredictMethodBodies(StringBuilder sb, ModuleModel model)
    {
        foreach (var pm in model.PredictMethods)
        {
            var backingField = PredictBackingFieldName(pm.MethodName);
            sb.Append("    public partial async Task<").Append(pm.OutputTypeFQN).Append("> ")
              .Append(pm.MethodName).Append("(").Append(pm.InputTypeFQN)
              .Append(" ").Append(pm.InputParameterName).AppendLine(")");
            sb.AppendLine("    {");
            sb.Append("        ").Append(backingField)
              .Append(" ??= new global::LMP.Predictor<").Append(pm.InputTypeFQN)
              .Append(", ").Append(pm.OutputTypeFQN)
              .AppendLine(">(Client ?? throw new global::System.InvalidOperationException(\"Set Client before calling [Predict] methods.\"));");
            sb.Append("        return await ").Append(backingField)
              .Append(".PredictAsync(").Append(pm.InputParameterName)
              .AppendLine(", Trace);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    private static void EmitCloneCore(StringBuilder sb, ModuleModel model)
    {
        sb.AppendLine("    protected override LmpModule CloneCore()");
        sb.AppendLine("    {");
        sb.Append("        var clone = (").Append(model.TypeName).AppendLine(")MemberwiseClone();");

        foreach (var field in model.PredictorFields)
        {
            var typeFqn = ResolveFieldTypeFQN(field);

            if (field.CanAssignDirectly)
            {
                // Direct assignment for non-readonly fields/properties
                sb.Append("        clone.").Append(field.FieldName)
                  .Append(" = (").Append(typeFqn).Append(")((global::LMP.IPredictor)")
                  .Append(field.FieldName).AppendLine(").Clone();");
            }
            else
            {
                // UnsafeAccessor for readonly fields or get-only properties
                var accessorName = "__cloneRef_" + SanitizeForIdentifier(field.FieldName);
                sb.Append("        ").Append(accessorName).Append("(clone) = (")
                  .Append(typeFqn).Append(")((global::LMP.IPredictor)")
                  .Append(field.FieldName).AppendLine(").Clone();");
            }
        }

        // Clone [Predict] backing fields
        foreach (var pm in model.PredictMethods)
        {
            var backingField = PredictBackingFieldName(pm.MethodName);
            sb.Append("        if (").Append(backingField).AppendLine(" is not null)");
            sb.Append("            clone.").Append(backingField)
              .Append(" = (global::LMP.Predictor<").Append(pm.InputTypeFQN)
              .Append(", ").Append(pm.OutputTypeFQN).Append(">)((global::LMP.IPredictor)")
              .Append(backingField).AppendLine(").Clone();");
        }

        sb.AppendLine("        return clone;");
        sb.AppendLine("    }");

        // Emit UnsafeAccessor stubs for readonly fields
        foreach (var field in model.PredictorFields)
        {
            if (field.CanAssignDirectly)
                continue;

            var typeFqn = ResolveFieldTypeFQN(field);
            var accessorName = "__cloneRef_" + SanitizeForIdentifier(field.FieldName);
            sb.AppendLine();
            sb.Append("    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = \"")
              .Append(field.UnsafeAccessorFieldName).AppendLine("\")]");
            sb.Append("    private static extern ref ").Append(typeFqn)
              .Append(' ').Append(accessorName).Append('(')
              .Append(model.TypeName).AppendLine(" instance);");
        }
    }

    /// <summary>
    /// Returns the resolved FQN for the predictor field type.
    /// Falls back to <c>global::LMP.Predictor&lt;InputFQN, OutputFQN&gt;</c> when
    /// <see cref="PredictorFieldModel.FieldTypeFQN"/> is empty.
    /// </summary>
    private static string ResolveFieldTypeFQN(PredictorFieldModel field)
    {
        return string.IsNullOrEmpty(field.FieldTypeFQN)
            ? "global::LMP.Predictor<" + field.InputTypeFQN + ", " + field.OutputTypeFQN + ">"
            : field.FieldTypeFQN;
    }

    /// <summary>
    /// Strips leading underscore from field names for the predictor name string.
    /// E.g., <c>_classify</c> becomes <c>classify</c>.
    /// </summary>
    private static string StripUnderscorePrefix(string fieldName)
    {
        return fieldName.StartsWith("_") && fieldName.Length > 1
            ? fieldName.Substring(1)
            : fieldName;
    }

    /// <summary>
    /// Sanitizes a field name for use as part of a C# identifier.
    /// Replaces &lt; and &gt; with underscores for backing field names.
    /// </summary>
    private static string SanitizeForIdentifier(string name)
    {
        return name.Replace('<', '_').Replace('>', '_');
    }

    /// <summary>
    /// Emits the <c>partial void ApplyOptimizedState()</c> declaration and a once-guarded
    /// call in <c>GetPredictors()</c>. If the optimizer hasn't written a <c>.g.cs</c>
    /// implementation, the compiler removes both (C# partial void rules).
    /// </summary>
    private static void EmitAutoOptimizeHook(StringBuilder sb, ModuleModel model)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Applied once when <see cref=\"GetPredictors\"/> is first called.");
        sb.AppendLine("    /// The optimizer CLI writes the implementation in");
        sb.AppendLine("    /// <c>Generated/" + model.TypeName + ".Optimized.g.cs</c>.");
        sb.AppendLine("    /// If no implementation exists, the compiler removes this entirely.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    partial void ApplyOptimizedState();");
    }

    /// <summary>
    /// Generates the backing field name for a [Predict] method.
    /// E.g., <c>ClassifyAsync</c> → <c>__predict_ClassifyAsync</c>.
    /// </summary>
    private static string PredictBackingFieldName(string methodName)
    {
        return "__predict_" + methodName;
    }
}
