using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits <c>partial class {ModuleName}</c> with an overridden <c>GetPredictors()</c>
/// method that returns all <c>Predictor&lt;,&gt;</c> fields for zero-reflection
/// predictor discovery.
/// </summary>
internal static class ModuleEmitter
{
    /// <summary>
    /// Generates the full source code for the <c>GetPredictors()</c> override.
    /// </summary>
    internal static string GenerateSource(ModuleModel model)
    {
        var sb = new StringBuilder(512);

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using LMP;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        // Class declaration
        sb.AppendLine("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.Append("partial class ").AppendLine(model.TypeName);
        sb.AppendLine("{");

        // GetPredictors() method
        sb.AppendLine("    public override IReadOnlyList<(string Name, IPredictor Predictor)> GetPredictors()");
        sb.AppendLine("        =>");
        sb.AppendLine("        [");

        for (int i = 0; i < model.PredictorFields.Count; i++)
        {
            var field = model.PredictorFields[i];
            var name = StripUnderscorePrefix(field.FieldName);
            sb.Append("            (\"").Append(name).Append("\", ").Append(field.FieldName).AppendLine("),");
        }

        sb.AppendLine("        ];");

        // Close class
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the GetPredictors source into the <see cref="SourceProductionContext"/>.
    /// </summary>
    public static void Emit(SourceProductionContext context, ModuleModel model)
    {
        var source = GenerateSource(model);
        context.AddSource(
            $"{model.TypeName}.Predictors.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    /// <summary>
    /// Strips leading underscore from field names for the predictor name string.
    /// E.g., <c>_classify</c> becomes <c>classify</c>.
    /// </summary>
    private static string StripUnderscorePrefix(string fieldName)
    {
        return fieldName.StartsWith("_") && fieldName.Length > 1
            ? fieldName.Substring(1)
            : fieldName;
    }
}
