using System.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits <c>file static class {TypeName}PromptBuilder</c> source code
/// that assembles <c>ChatMessage[]</c> from instructions, field metadata,
/// demos, and the current input.
/// </summary>
internal static class PromptBuilderEmitter
{
    /// <summary>
    /// Generates the full PromptBuilder source code for the given output type model.
    /// Returns <c>null</c> if the model does not have enough information to generate
    /// (e.g., missing <see cref="OutputTypeModel.InputTypeName"/>).
    /// </summary>
    internal static string? GenerateSource(OutputTypeModel model)
    {
        if (model.InputTypeName is null)
            return null;

        var sb = new StringBuilder(2048);

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.Extensions.AI;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ");
            sb.Append(model.Namespace);
            sb.AppendLine(";");
            sb.AppendLine();
        }

        // Class declaration
        sb.AppendLine("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.Append("file static class ");
        sb.Append(model.TypeName);
        sb.AppendLine("PromptBuilder");
        sb.AppendLine("{");

        // Instructions constant
        EmitInstructionsConstant(sb, model.Instructions);
        sb.AppendLine();

        // FieldDescriptions constant
        EmitFieldDescriptions(sb, model);
        sb.AppendLine();

        // DefaultInstructions property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Returns the default instructions from the <c>[LmpSignature]</c> attribute.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string DefaultInstructions => Instructions;");
        sb.AppendLine();

        // BuildMessages method
        EmitBuildMessages(sb, model);
        sb.AppendLine();

        // FormatInput method
        EmitFormatInput(sb, model);
        sb.AppendLine();

        // FormatOutput method
        EmitFormatOutput(sb, model);

        // Close class
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the PromptBuilder source into the <see cref="Microsoft.CodeAnalysis.SourceProductionContext"/>.
    /// Skips emission if the model is not ready (missing input type info).
    /// </summary>
    public static void Emit(Microsoft.CodeAnalysis.SourceProductionContext context, OutputTypeModel model)
    {
        var source = GenerateSource(model);
        if (source is null)
            return;

        context.AddSource(
            $"{model.TypeName}.PromptBuilder.g.cs",
            Microsoft.CodeAnalysis.Text.SourceText.From(source, Encoding.UTF8));
    }

    private static void EmitInstructionsConstant(StringBuilder sb, string instructions)
    {
        sb.AppendLine("    private const string Instructions =");
        sb.Append("        \"");
        sb.Append(EscapeStringLiteral(instructions));
        sb.AppendLine("\";");
    }

    private static void EmitFieldDescriptions(StringBuilder sb, OutputTypeModel model)
    {
        sb.AppendLine("    private const string FieldDescriptions =");
        sb.AppendLine("        \"\"\"");

        // Input fields
        if (model.InputFields.Count > 0)
        {
            sb.AppendLine("        Input Fields:");
            foreach (var field in model.InputFields)
            {
                sb.Append("        - ");
                sb.Append(field.Name);
                sb.Append(" (");
                sb.Append(field.ClrTypeName);
                sb.Append(')');
                if (!string.IsNullOrEmpty(field.Description))
                {
                    sb.Append(": ");
                    sb.Append(field.Description);
                }
                sb.AppendLine();
            }
        }

        // Blank line between input and output if both present
        if (model.InputFields.Count > 0 && model.OutputFields.Count > 0)
        {
            sb.AppendLine();
        }

        // Output fields
        if (model.OutputFields.Count > 0)
        {
            sb.AppendLine("        Output Fields:");
            foreach (var field in model.OutputFields)
            {
                sb.Append("        - ");
                sb.Append(field.Name);
                sb.Append(" (");
                sb.Append(field.ClrTypeName);
                sb.Append(')');
                if (!string.IsNullOrEmpty(field.Description))
                {
                    sb.Append(": ");
                    sb.Append(field.Description);
                }
                sb.AppendLine();
            }
        }

        sb.AppendLine("        \"\"\";");
    }

    private static void EmitBuildMessages(StringBuilder sb, OutputTypeModel model)
    {
        var inputType = model.InputTypeName!;
        var outputType = model.TypeName;

        sb.AppendLine("    public static IList<ChatMessage> BuildMessages(");
        sb.Append("        ");
        sb.Append(inputType);
        sb.AppendLine(" input,");
        sb.Append("        IReadOnlyList<(");
        sb.Append(inputType);
        sb.Append(" Input, ");
        sb.Append(outputType);
        sb.AppendLine(" Output)>? demos = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var messages = new List<ChatMessage>();");
        sb.AppendLine();
        sb.AppendLine("        // System message: instructions + field descriptions");
        sb.AppendLine("        messages.Add(new ChatMessage(ChatRole.System,");
        sb.AppendLine("            Instructions + \"\\n\\n\" + FieldDescriptions));");
        sb.AppendLine();
        sb.AppendLine("        // Few-shot demo pairs");
        sb.AppendLine("        if (demos is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var (demoInput, demoOutput) in demos)");
        sb.AppendLine("            {");
        sb.AppendLine("                messages.Add(new ChatMessage(ChatRole.User, FormatInput(demoInput)));");
        sb.AppendLine("                messages.Add(new ChatMessage(ChatRole.Assistant, FormatOutput(demoOutput)));");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // Current input");
        sb.AppendLine("        messages.Add(new ChatMessage(ChatRole.User, FormatInput(input)));");
        sb.AppendLine();
        sb.AppendLine("        return messages;");
        sb.AppendLine("    }");
    }

    private static void EmitFormatInput(StringBuilder sb, OutputTypeModel model)
    {
        var inputType = model.InputTypeName!;

        sb.Append("    private static string FormatInput(");
        sb.Append(inputType);
        sb.AppendLine(" input)");

        if (model.InputFields.Count == 0)
        {
            sb.AppendLine("        => input?.ToString() ?? \"\";");
            return;
        }

        if (model.InputFields.Count == 1)
        {
            var field = model.InputFields[0];
            sb.Append("        => $\"");
            sb.Append(field.Name);
            sb.Append(": {input.");
            sb.Append(field.Name);
            sb.AppendLine("}\";");
            return;
        }

        // Multi-field: use raw string literal interpolation
        sb.AppendLine("        => $\"\"\"");
        for (int i = 0; i < model.InputFields.Count; i++)
        {
            var field = model.InputFields[i];
            sb.Append("            ");
            sb.Append(field.Name);
            sb.Append(": {input.");
            sb.Append(field.Name);
            sb.Append('}');
            sb.AppendLine();
        }
        sb.AppendLine("            \"\"\";");
    }

    private static void EmitFormatOutput(StringBuilder sb, OutputTypeModel model)
    {
        sb.Append("    private static string FormatOutput(");
        sb.Append(model.TypeName);
        sb.AppendLine(" output)");
        sb.AppendLine("        => System.Text.Json.JsonSerializer.Serialize(output);");
    }

    private static string EscapeStringLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}
