using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits <c>internal static class {TypeName}PromptBuilder</c> source code
/// that assembles <c>ChatMessage[]</c> from instructions, field metadata,
/// demos, and the current input.
/// </summary>
internal static class PromptBuilderEmitter
{
    /// <summary>
    /// Generates the full PromptBuilder source code for the given model.
    /// </summary>
    internal static string GenerateSource(PromptBuilderModel model)
    {
        var sb = new StringBuilder(2048);

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.Extensions.AI;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        // Class declaration
        sb.AppendLine("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.Append("internal static class ").Append(model.OutputTypeName).AppendLine("PromptBuilder");
        sb.AppendLine("{");

        // Instructions constant
        EmitInstructionsConstant(sb, model.Instructions);
        sb.AppendLine();

        // FieldDescriptions constant
        EmitFieldDescriptions(sb, model);
        sb.AppendLine();

        // DefaultInstructions property
        sb.AppendLine("    public static string DefaultInstructions => Instructions;");
        sb.AppendLine();

        // BuildMessages method (simple 2-param)
        EmitBuildMessages(sb, model);
        sb.AppendLine();

        // BuildMessages overload matching Predictor.MessageBuilder delegate
        EmitBuildMessagesForPredictor(sb, model);
        sb.AppendLine();

        // FormatInput method
        EmitFormatInput(sb, model);
        sb.AppendLine();

        // FormatOutput method
        EmitFormatOutput(sb, model);

        // Close class
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the PromptBuilder source into the <see cref="SourceProductionContext"/>.
    /// </summary>
    public static void Emit(SourceProductionContext context, PromptBuilderModel model)
    {
        var source = GenerateSource(model);
        context.AddSource(
            $"{model.OutputTypeName}.PromptBuilder.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    private static void EmitInstructionsConstant(StringBuilder sb, string instructions)
    {
        sb.AppendLine("    private const string Instructions =");
        sb.Append("        \"").Append(EscapeStringLiteral(instructions)).AppendLine("\";");
    }

    private static void EmitFieldDescriptions(StringBuilder sb, PromptBuilderModel model)
    {
        sb.AppendLine("    private const string FieldDescriptions =");
        sb.AppendLine("        \"\"\"");

        if (model.InputFields.Count > 0)
        {
            sb.AppendLine("        Input Fields:");
            foreach (var field in model.InputFields)
            {
                sb.Append("        - ").Append(field.Name)
                  .Append(" (").Append(field.ClrTypeName).Append(')');
                if (!string.IsNullOrEmpty(field.Description))
                    sb.Append(": ").Append(field.Description);
                sb.AppendLine();
            }
        }

        if (model.InputFields.Count > 0 && model.OutputFields.Count > 0)
            sb.AppendLine();

        if (model.OutputFields.Count > 0)
        {
            sb.AppendLine("        Output Fields:");
            foreach (var field in model.OutputFields)
            {
                sb.Append("        - ").Append(field.Name)
                  .Append(" (").Append(field.ClrTypeName).Append(')');
                if (!string.IsNullOrEmpty(field.Description))
                    sb.Append(": ").Append(field.Description);
                if (field.EnumValues is { Count: > 0 } values)
                {
                    sb.Append(" [Valid values: ");
                    for (int i = 0; i < values.Count; i++)
                    {
                        if (i > 0) sb.Append(", ");
                        sb.Append(values[i]);
                    }
                    sb.Append(']');
                }
                sb.AppendLine();
            }
        }

        sb.AppendLine("        \"\"\";");
    }

    private static void EmitBuildMessages(StringBuilder sb, PromptBuilderModel model)
    {
        sb.AppendLine("    public static IList<ChatMessage> BuildMessages(");
        sb.Append("        ").Append(model.InputTypeName).AppendLine(" input,");
        sb.Append("        IReadOnlyList<(").Append(model.InputTypeName)
          .Append(" Input, ").Append(model.OutputTypeName).AppendLine(" Output)>? demos = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        return BuildMessages(Instructions, input, demos, null);");
        sb.AppendLine("    }");
    }

    private static void EmitBuildMessagesForPredictor(StringBuilder sb, PromptBuilderModel model)
    {
        sb.AppendLine("    public static IList<ChatMessage> BuildMessages(");
        sb.AppendLine("        string instructions,");
        sb.Append("        ").Append(model.InputTypeName).AppendLine(" input,");
        sb.Append("        IReadOnlyList<(").Append(model.InputTypeName)
          .Append(" Input, ").Append(model.OutputTypeName).AppendLine(" Output)>? demos,");
        sb.AppendLine("        string? lastError)");
        sb.AppendLine("    {");
        sb.AppendLine("        var messages = new List<ChatMessage>();");
        sb.AppendLine();
        sb.AppendLine("        // System message: custom instructions + field descriptions");
        sb.AppendLine("        messages.Add(new ChatMessage(ChatRole.System,");
        sb.AppendLine("            instructions + \"\\n\\n\" + FieldDescriptions));");
        sb.AppendLine();
        sb.AppendLine("        // Few-shot demo pairs");
        sb.AppendLine("        if (demos is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var (demoInput, demoOutput) in demos)");
        sb.AppendLine("            {");
        sb.AppendLine("                messages.Add(new ChatMessage(ChatRole.User, FormatInput(demoInput)));");
        sb.AppendLine("                messages.Add(new ChatMessage(ChatRole.Assistant, FormatOutput(demoOutput)));");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // Current input with optional retry feedback");
        sb.AppendLine("        var userContent = FormatInput(input);");
        sb.AppendLine("        if (lastError is not null)");
        sb.AppendLine("            userContent += $\"\\n\\nPrevious attempt failed: {lastError}. Try again.\";");
        sb.AppendLine();
        sb.AppendLine("        messages.Add(new ChatMessage(ChatRole.User, userContent));");
        sb.AppendLine();
        sb.AppendLine("        return messages;");
        sb.AppendLine("    }");
    }

    private static void EmitFormatInput(StringBuilder sb, PromptBuilderModel model)
    {
        sb.Append("    private static string FormatInput(").Append(model.InputTypeName).AppendLine(" input)");

        if (model.InputFields.Count == 0)
        {
            sb.AppendLine("        => input?.ToString() ?? \"\";");
            return;
        }

        if (model.InputFields.Count == 1)
        {
            var field = model.InputFields[0];
            sb.Append("        => $\"").Append(field.Name)
              .Append(": {input.").Append(field.Name).AppendLine("}\";");
            return;
        }

        // Multi-field: use raw string literal interpolation
        sb.AppendLine("        => $\"\"\"");
        for (int i = 0; i < model.InputFields.Count; i++)
        {
            var field = model.InputFields[i];
            sb.Append("            ").Append(field.Name)
              .Append(": {input.").Append(field.Name).AppendLine("}");
        }
        sb.AppendLine("            \"\"\";");
    }

    private static void EmitFormatOutput(StringBuilder sb, PromptBuilderModel model)
    {
        sb.AppendLine("    [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL2026:RequiresUnreferencedCode\",");
        sb.AppendLine("        Justification = \"Demo formatting uses JsonSerializer for prompt assembly; callers can provide SerializerOptions for AOT.\")]");
        sb.AppendLine("    [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL3050:RequiresDynamicCode\",");
        sb.AppendLine("        Justification = \"Demo formatting uses JsonSerializer for prompt assembly; callers can provide SerializerOptions for AOT.\")]");
        sb.Append("    private static string FormatOutput(").Append(model.OutputTypeName).AppendLine(" output)");
        sb.AppendLine("        => System.Text.Json.JsonSerializer.Serialize(output);");
    }

    private static string EscapeStringLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}
