using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits <c>partial class {ModuleName}</c> with an overridden <c>GetSkills()</c>
/// method listing all <c>[Skill]</c>-annotated methods as <c>SkillManifest</c> entries.
/// </summary>
internal static class SkillEmitter
{
    /// <summary>
    /// Generates the full source code for the <c>GetSkills()</c> override.
    /// </summary>
    internal static string GenerateSource(SkillModuleModel model)
    {
        var sb = new StringBuilder(512);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using LMP;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.AppendLine("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.Append("partial class ").AppendLine(model.TypeName);
        sb.AppendLine("{");

        sb.AppendLine("    public override global::System.Collections.Generic.IReadOnlyList<global::LMP.SkillManifest> GetSkills()");
        sb.AppendLine("        =>");

        // Emit collection expression for public methods only
        var publicMethods = model.SkillMethods
            .Where(static m => m.IsPublic)
            .ToArray();

        if (publicMethods.Length == 0)
        {
            sb.AppendLine("        [];");
        }
        else
        {
            sb.AppendLine("        [");
            foreach (var skill in publicMethods)
            {
                var skillName = EscapeString(skill.NameOverride ?? skill.MethodName);
                var desc = skill.Description is null ? "null" : $"\"{EscapeString(skill.Description)}\"";
                sb.AppendLine($"            new global::LMP.SkillManifest(\"{skillName}\", {desc}),");
            }
            sb.AppendLine("        ];");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    internal static void Emit(SourceProductionContext spc, SkillModuleModel model)
    {
        // Report LMP030 for non-public [Skill] methods
        foreach (var skill in model.SkillMethods)
        {
            if (!skill.IsPublic)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    LmpDiagnostics.SkillMethodNotPublic,
                    skill.Location.ToLocation(),
                    skill.MethodName));
            }
        }

        // Only emit source if there are any methods (including non-public, since we emit empty list)
        var source = GenerateSource(model);
        spc.AddSource($"{model.TypeName}.Skills.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
