using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LMP.SourceGen;

/// <summary>
/// Emits <c>partial class {ModuleName}</c> with an overridden <c>GetTools()</c>
/// method listing all <c>[Tool]</c>-annotated public instance methods as
/// <c>AIFunction</c> instances created via <c>AIFunctionFactory.Create</c>.
/// </summary>
internal static class ToolEmitter
{
    /// <summary>
    /// Generates the full source code for the <c>GetTools()</c> override.
    /// </summary>
    internal static string GenerateSource(ToolModuleModel model)
    {
        var sb = new StringBuilder(512);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.AppendLine("[GeneratedCode(\"LMP.Generators\", \"1.0.0\")]");
        sb.Append("partial class ").AppendLine(model.TypeName);
        sb.AppendLine("{");

        sb.AppendLine("    public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AIFunction> GetTools()");
        sb.AppendLine("        =>");

        var emittableMethods = model.ToolMethods
            .Where(static m => m.IsPublic && !m.IsStatic)
            .ToArray();

        if (emittableMethods.Length == 0)
        {
            sb.AppendLine("        [];");
        }
        else
        {
            sb.AppendLine("        [");
            foreach (var tool in emittableMethods)
            {
                var toolName = EscapeString(tool.NameOverride ?? tool.MethodName);
                if (tool.Description is null)
                {
                    sb.AppendLine($"            global::Microsoft.Extensions.AI.AIFunctionFactory.Create(this.{tool.MethodName}, name: \"{toolName}\"),");
                }
                else
                {
                    var desc = EscapeString(tool.Description);
                    sb.AppendLine($"            global::Microsoft.Extensions.AI.AIFunctionFactory.Create(this.{tool.MethodName}, name: \"{toolName}\", description: \"{desc}\"),");
                }
            }
            sb.AppendLine("        ];");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    internal static void Emit(SourceProductionContext spc, ToolModuleModel model)
    {
        var seenNames = new HashSet<string>();

        foreach (var tool in model.ToolMethods)
        {
            // LMP021: [Tool] on static method — error, not emitted
            if (tool.IsStatic)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    LmpDiagnostics.ToolMethodStatic,
                    tool.Location.ToLocation(),
                    tool.MethodName));
                continue;
            }

            // Only validate public instance methods for remaining diagnostics
            if (!tool.IsPublic)
                continue;

            // LMP020: [Tool] on non-async method — warning, still emitted
            if (!tool.IsAsync)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    LmpDiagnostics.ToolMethodNotAsync,
                    tool.Location.ToLocation(),
                    tool.MethodName));
            }

            // LMP025: [Tool] method has more than 10 parameters — warning, still emitted
            if (tool.ParameterCount > 10)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    LmpDiagnostics.ToolMethodTooManyParams,
                    tool.Location.ToLocation(),
                    tool.MethodName,
                    tool.ParameterCount));
            }

            // LMP023: duplicate tool name — warning
            var toolName = tool.NameOverride ?? tool.MethodName;
            if (!seenNames.Add(toolName))
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    LmpDiagnostics.DuplicateToolName,
                    tool.Location.ToLocation(),
                    toolName,
                    tool.MethodName));
            }
        }

        var source = GenerateSource(model);
        spc.AddSource($"{model.TypeName}.Tools.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
