using System.Collections;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.AI;

namespace LMP;

/// <summary>
/// Generates <c>Generated/{Module}.Optimized.g.cs</c> files from optimized module state.
/// The generated file contains a <c>partial void ApplyOptimizedState()</c> implementation
/// that sets predictor state using direct C# property assignments and typed object
/// initializers — no JSON, no deserialization, zero runtime overhead.
/// </summary>
/// <remarks>
/// This class uses reflection to inspect module fields, predictor types, and object
/// properties at dev-time (not in production AOT paths). The generated <c>.g.cs</c>
/// output is pure static C# with zero reflection at runtime.
/// </remarks>
#pragma warning disable IL2075, IL2070 // Reflection-based code generation is dev-time only; the output is static C#
public static class CSharpArtifactWriter
{
    /// <summary>
    /// Writes a <c>.g.cs</c> file for the specified module with the optimized state
    /// as pure C# (direct field access, typed demos, string literal instructions).
    /// </summary>
    /// <param name="module">The optimized module to emit.</param>
    /// <param name="outputDir">Directory to write the <c>.g.cs</c> file to.</param>
    /// <param name="score">The best optimization score (for header comment).</param>
    /// <param name="optimizerName">The optimizer strategy name (for header comment).</param>
    /// <param name="trainDataPath">Optional training data file path for staleness hash.</param>
    /// <param name="baseline">Optional pre-optimization baseline score for comparison.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The full path to the generated file.</returns>
    public static async Task<string> WriteAsync(
        LmpModule module,
        string outputDir,
        float score,
        string optimizerName,
        string? trainDataPath = null,
        float? baseline = null,
        CancellationToken cancellationToken = default)
    {
        var moduleType = module.GetType();
        var typeName = moduleType.Name;
        var ns = moduleType.Namespace ?? "";

        // Map predictor Name → field name by reflecting on the module type
        var fieldMap = DiscoverPredictorFields(module);

        // Compute staleness hash
        var trainHash = trainDataPath is not null && File.Exists(trainDataPath)
            ? await ComputeFileHashAsync(trainDataPath, cancellationToken)
            : "none";

        // Count total demos across all predictors for header metadata
        var predictors = module.GetPredictors();
        int totalDemos = 0;
        foreach (var (_, predictor) in predictors)
            totalDemos += predictor.Demos.Count;

        // Generate the C# source
        var sb = new StringBuilder(4096);

        // Header
        sb.AppendLine("// <auto-generated>");
        var baselineStr = baseline.HasValue ? $" | Baseline: {baseline.Value:F4}" : "";
        sb.AppendLine($"// LMP Auto-Optimize | Score: {score:F4}{baselineStr} | Strategy: {optimizerName} | Demos: {totalDemos}");
        sb.AppendLine($"// Dataset: sha256:{trainHash}");
        sb.AppendLine($"// Generated: {DateTime.UtcNow:O}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ").AppendLine(typeName);
        sb.AppendLine("{");
        sb.AppendLine("    partial void ApplyOptimizedState()");
        sb.AppendLine("    {");

        // Emit typed C# for each predictor
        for (int i = 0; i < predictors.Count; i++)
        {
            var (name, predictor) = predictors[i];

            if (!fieldMap.TryGetValue(name, out var fieldName))
                fieldName = "_" + name; // fallback convention

            // Instructions
            if (!string.IsNullOrEmpty(predictor.Instructions))
            {
                EmitInstructions(sb, fieldName, predictor.Instructions);
                sb.AppendLine();
            }

            // Demos
            if (predictor.Demos.Count > 0)
            {
                var predType = predictor.GetType();
                var genArgs = predType.GetGenericArguments();

                if (genArgs.Length == 2)
                {
                    var tInput = genArgs[0];
                    var tOutput = genArgs[1];

                    foreach (var demo in predictor.Demos)
                    {
                        var demoType = demo.GetType();
                        var input = demoType.GetField("Item1")?.GetValue(demo);
                        var output = demoType.GetField("Item2")?.GetValue(demo);

                        if (input is not null && output is not null)
                        {
                            EmitAddDemo(sb, fieldName, input, tInput, output, tOutput, ns);
                            sb.AppendLine();
                        }
                    }
                }
            }

            // Config (only emit non-default values)
            EmitConfig(sb, fieldName, predictor.Config);

            // Blank line between predictors
            if (i < predictors.Count - 1)
                sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        // Write to output directory
        Directory.CreateDirectory(outputDir);
        var outputPath = Path.Combine(outputDir, $"{typeName}.Optimized.g.cs");

        // Atomic write
        var tempPath = outputPath + ".tmp";
        await File.WriteAllTextAsync(tempPath, sb.ToString(), Encoding.UTF8, cancellationToken);
        File.Move(tempPath, outputPath, overwrite: true);

        return outputPath;
    }

    /// <summary>
    /// Writes a <c>Generated/{className}.g.cs</c> file for a <see cref="ChatClientTarget"/>
    /// optimization result as a static <c>IChatClient</c> factory.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The emitted class has a single <c>Build(IChatClient baseClient)</c> method that
    /// returns an <see cref="Microsoft.Extensions.AI.IChatClient"/> with the learned
    /// system prompt and temperature baked in as compile-time string and float literals.
    /// No JSON loading, no deserialization — zero I/O overhead at runtime.
    /// </para>
    /// <para>
    /// <see cref="ChatClientState.SelectedToolNames"/> is intentionally excluded because
    /// tool instances (<see cref="Microsoft.Extensions.AI.AITool"/>) cannot be serialized
    /// as C# literals. Pass the tool catalog explicitly to <see cref="ChatClientOptimizationExtensions.UseOptimized(Microsoft.Extensions.AI.ChatClientBuilder,ChatClientState)"/>
    /// at the call site if tool selection is needed.
    /// </para>
    /// </remarks>
    /// <param name="state">The optimized chat client state to emit.</param>
    /// <param name="className">The name of the generated static class (e.g., <c>OptimizedSupportClient</c>).</param>
    /// <param name="ns">The namespace to declare the class in (e.g., <c>MyApp.Generated</c>).</param>
    /// <param name="outputDir">Directory to write the <c>.g.cs</c> file to.</param>
    /// <param name="score">The best optimization score (for header comment).</param>
    /// <param name="optimizerName">The optimizer strategy name (for header comment).</param>
    /// <param name="baseline">Optional pre-optimization baseline score for comparison.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The full path to the generated file.</returns>
    public static async Task<string> WriteForChatClientTargetAsync(
        ChatClientState state,
        string className,
        string ns,
        string outputDir,
        float score,
        string optimizerName,
        float? baseline = null,
        CancellationToken cancellationToken = default)
    {
        var sb = new StringBuilder(2048);

        // Header
        sb.AppendLine("// <auto-generated>");
        var baselineStr = baseline.HasValue ? $" | Baseline: {baseline.Value:F4}" : "";
        sb.AppendLine($"// LMP Auto-Optimize | Score: {score:F4}{baselineStr} | Strategy: {optimizerName}");
        sb.AppendLine($"// Generated: {DateTime.UtcNow:O}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using LMP;");
        sb.AppendLine("using Microsoft.Extensions.AI;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Builds an <see cref=\"IChatClient\"/> with the optimized system prompt and temperature");
        sb.AppendLine($"    /// baked in as compile-time constants. Score: {score:P1} ({optimizerName}).");
        sb.AppendLine("    /// Do not edit — re-run the optimizer to refresh.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"baseClient\">The underlying chat client to wrap.</param>");
        sb.AppendLine("    /// <param name=\"tools\">");
        sb.AppendLine("    /// Optional tool pool. When non-null, only tools whose names were selected");
        sb.AppendLine("    /// during optimization are activated. Pass <see langword=\"null\"/> to skip tool filtering.");
        sb.AppendLine("    /// </param>");
        sb.AppendLine("    public static IChatClient Build(IChatClient baseClient, IReadOnlyList<AITool>? tools = null)");
        sb.AppendLine("        => new ChatClientBuilder(baseClient)");
        sb.AppendLine("            .UseOptimized(new ChatClientState");
        sb.AppendLine("            {");

        if (state.SystemPrompt is not null)
        {
            if (state.SystemPrompt.Contains('\n') || state.SystemPrompt.Contains('\r'))
            {
                sb.AppendLine("                SystemPrompt = \"\"\"");
                foreach (var line in state.SystemPrompt.Split('\n'))
                    sb.Append("                    ").AppendLine(line.TrimEnd());
                sb.AppendLine("                    \"\"\",");
            }
            else
            {
                sb.AppendLine($"                SystemPrompt = {EscapeString(state.SystemPrompt)},");
            }
        }

        if (state.Temperature is not null)
            sb.AppendLine($"                Temperature = {state.Temperature.Value}f,");

        // SelectedToolNames is intentionally excluded: AITool instances cannot be
        // represented as C# literals. Pass the tool catalog at the call site if needed.

        sb.AppendLine("            }, tools)");
        sb.AppendLine("            .Build();");
        sb.AppendLine("}");

        // Write to output directory
        Directory.CreateDirectory(outputDir);
        var outputPath = Path.Combine(outputDir, $"{className}.g.cs");

        // Atomic write
        var tempPath = outputPath + ".tmp";
        await File.WriteAllTextAsync(tempPath, sb.ToString(), Encoding.UTF8, cancellationToken);
        File.Move(tempPath, outputPath, overwrite: true);

        return outputPath;
    }

    /// <summary>
    /// Checks if an existing generated file is still fresh based on dataset hash.
    /// </summary>
    public static async Task<bool> IsUpToDateAsync(
        string generatedPath,
        string trainPath,
        CancellationToken cancellationToken)
    {
        if (!File.Exists(generatedPath) || !File.Exists(trainPath))
            return false;

        var currentHash = await ComputeFileHashAsync(trainPath, cancellationToken);

        using var reader = new StreamReader(generatedPath);
        for (int i = 0; i < 10; i++)
        {
            var line = await reader.ReadLineAsync(cancellationToken);
            if (line is null)
                break;

            if (line.StartsWith("// Dataset: sha256:"))
            {
                var existingHash = line["// Dataset: sha256:".Length..].Trim();
                return existingHash == currentHash;
            }
        }

        return false;
    }

    /// <summary>
    /// Discovers predictor field names by reflecting on the module type.
    /// Returns a map of predictor Name → field name (e.g., "qa" → "_qa").
    /// </summary>
    private static Dictionary<string, string> DiscoverPredictorFields(LmpModule module)
    {
        var map = new Dictionary<string, string>();
        var moduleType = module.GetType();
        var fields = moduleType.GetFields(
            BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);

        foreach (var field in fields)
        {
            if (!typeof(IPredictor).IsAssignableFrom(field.FieldType))
                continue;

            if (field.GetValue(module) is IPredictor pred && !string.IsNullOrEmpty(pred.Name))
                map[pred.Name] = field.Name;
        }

        return map;
    }

    private static void EmitInstructions(StringBuilder sb, string fieldName, string instructions)
    {
        if (instructions.Contains('\n') || instructions.Contains('\r'))
        {
            sb.AppendLine($"        {fieldName}.Instructions = \"\"\"");
            foreach (var line in instructions.Split('\n'))
                sb.Append("            ").AppendLine(line.TrimEnd());
            sb.AppendLine("            \"\"\";");
        }
        else
        {
            sb.AppendLine($"        {fieldName}.Instructions = {EscapeString(instructions)};");
        }
    }

    private static void EmitAddDemo(
        StringBuilder sb,
        string fieldName,
        object input, Type tInput,
        object output, Type tOutput,
        string moduleNamespace)
    {
        var inputInit = GenerateObjectInitializer(input, tInput, "            ", moduleNamespace);
        var outputInit = GenerateObjectInitializer(output, tOutput, "            ", moduleNamespace);

        sb.AppendLine($"        {fieldName}.AddDemo(");
        sb.AppendLine($"            input: {inputInit},");
        sb.AppendLine($"            output: {outputInit});");
    }

    private static void EmitConfig(StringBuilder sb, string fieldName, ChatOptions config)
    {
        var parts = new List<string>();

        if (config.Temperature is not null)
            parts.Add($"Temperature = {config.Temperature.Value}f");
        if (config.MaxOutputTokens is not null)
            parts.Add($"MaxOutputTokens = {config.MaxOutputTokens.Value}");
        if (config.TopP is not null)
            parts.Add($"TopP = {config.TopP.Value}f");
        if (config.FrequencyPenalty is not null)
            parts.Add($"FrequencyPenalty = {config.FrequencyPenalty.Value}f");
        if (config.PresencePenalty is not null)
            parts.Add($"PresencePenalty = {config.PresencePenalty.Value}f");
        if (config.ModelId is not null)
            parts.Add($"ModelId = {EscapeString(config.ModelId)}");

        if (parts.Count > 0)
        {
            sb.Append($"        {fieldName}.Config = new global::Microsoft.Extensions.AI.ChatOptions {{ ");
            sb.Append(string.Join(", ", parts));
            sb.AppendLine(" };");
        }
    }

    private static string GenerateObjectInitializer(
        object obj, Type type, string indent, string moduleNamespace)
    {
        var typeName = ResolveTypeName(type, moduleNamespace);
        var props = type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.CanRead)
            .ToArray();

        var hasParameterlessCtor = type.GetConstructor(Type.EmptyTypes) is not null;

        if (!hasParameterlessCtor)
            return GenerateCtorCall(obj, type, typeName, props, indent, moduleNamespace);

        var settableProps = props.Where(p => p.CanWrite).ToArray();
        if (settableProps.Length == 0)
            return $"new {typeName}()";

        var assignments = new List<string>();
        foreach (var prop in settableProps)
        {
            var value = prop.GetValue(obj);
            if (value is null)
                continue;

            var literal = GenerateLiteral(value, prop.PropertyType, indent + "    ", moduleNamespace);
            if (literal is not null)
                assignments.Add($"{prop.Name} = {literal}");
        }

        if (assignments.Count == 0)
            return $"new {typeName}()";

        if (assignments.Count == 1)
            return $"new {typeName} {{ {assignments[0]} }}";

        var sb = new StringBuilder();
        sb.AppendLine($"new {typeName}");
        sb.Append(indent).AppendLine("{");
        for (int i = 0; i < assignments.Count; i++)
        {
            sb.Append(indent).Append("    ").Append(assignments[i]);
            if (i < assignments.Count - 1)
                sb.AppendLine(",");
            else
                sb.AppendLine();
        }
        sb.Append(indent).Append('}');
        return sb.ToString();
    }

    private static string GenerateCtorCall(
        object obj, Type type, string typeName,
        PropertyInfo[] props, string indent, string moduleNamespace)
    {
        var ctor = type.GetConstructors()
            .OrderByDescending(c => c.GetParameters().Length)
            .FirstOrDefault();

        if (ctor is null)
            return $"default({typeName})!";

        var parameters = ctor.GetParameters();
        var args = new List<string>();

        foreach (var param in parameters)
        {
            var prop = props.FirstOrDefault(p =>
                string.Equals(p.Name, param.Name, StringComparison.OrdinalIgnoreCase));

            if (prop is null)
            {
                args.Add("default!");
                continue;
            }

            var value = prop.GetValue(obj);
            if (value is null)
            {
                args.Add("default!");
                continue;
            }

            var literal = GenerateLiteral(value, prop.PropertyType, indent + "    ", moduleNamespace);
            args.Add(literal ?? "default!");
        }

        if (args.Count <= 2)
            return $"new {typeName}({string.Join(", ", args)})";

        var sb = new StringBuilder();
        sb.AppendLine($"new {typeName}(");
        for (int i = 0; i < args.Count; i++)
        {
            sb.Append(indent).Append("    ").Append(args[i]);
            if (i < args.Count - 1)
                sb.AppendLine(",");
            else
                sb.Append(')');
        }
        return sb.ToString();
    }

    private static string? GenerateLiteral(
        object value, Type type, string indent, string moduleNamespace)
    {
        var underlying = Nullable.GetUnderlyingType(type);
        if (underlying is not null)
            type = underlying;

        return value switch
        {
            string s => EscapeString(s),
            bool b => b ? "true" : "false",
            int i => i.ToString(),
            long l => $"{l}L",
            float f => $"{f}f",
            double d => d.ToString(),
            decimal m => $"{m}m",
            _ when type.IsEnum => $"{ResolveTypeName(type, moduleNamespace)}.{value}",
            _ when type.IsClass || type.IsValueType =>
                GenerateObjectInitializer(value, type, indent, moduleNamespace),
            _ => null
        };
    }

    private static string ResolveTypeName(Type type, string moduleNamespace)
    {
        if (type.Namespace == moduleNamespace)
            return type.Name;

        return $"global::{type.FullName ?? type.Name}";
    }

    private static string EscapeString(string value)
    {
        if (value.Contains('\\') || value.Count(c => c == '"') > 2)
            return $"@\"{value.Replace("\"", "\"\"")}\"";

        return $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t")}\"";
    }

    private static async Task<string> ComputeFileHashAsync(
        string path, CancellationToken cancellationToken)
    {
        using var stream = File.OpenRead(path);
        var hash = await SHA256.HashDataAsync(stream, cancellationToken);
        return Convert.ToHexStringLower(hash)[..16];
    }
}
