using LMP;

namespace LMP.Tests;

public class CSharpArtifactWriterChatClientTargetTests
{
    [Fact]
    public async Task WriteForChatClientTargetAsync_EmitsClassAndBuildMethod()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"lmp-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var state = new ChatClientState
            {
                SystemPrompt = "You are a helpful assistant.",
                Temperature = 1.33f
            };

            var path = await CSharpArtifactWriter.WriteForChatClientTargetAsync(
                state,
                className: "OptimizedSupportClient",
                ns: "MyApp.Generated",
                outputDir: tempDir,
                score: 0.4710f,
                optimizerName: "BayesianCalibration",
                baseline: 0.4200f);

            Assert.True(File.Exists(path));
            var code = await File.ReadAllTextAsync(path);

            // Header
            Assert.Contains("// <auto-generated>", code);
            Assert.Contains("Score: 0.4710", code);
            Assert.Contains("Baseline: 0.4200", code);
            Assert.Contains("Strategy: BayesianCalibration", code);

            // Namespace + class structure
            Assert.Contains("namespace MyApp.Generated;", code);
            Assert.Contains("public static class OptimizedSupportClient", code);
            Assert.Contains("public static IChatClient Build(IChatClient baseClient, IReadOnlyList<AITool>? tools = null)", code);
            Assert.Contains("new ChatClientBuilder(baseClient)", code);
            Assert.Contains(".UseOptimized(new ChatClientState", code);
            Assert.Contains(".Build();", code);

            // State values
            Assert.Contains("SystemPrompt =", code);
            Assert.Contains("You are a helpful assistant.", code);
            Assert.Contains("Temperature = 1.33f", code);

            // SelectedToolNames must NOT appear
            Assert.DoesNotContain("SelectedToolNames", code);

            // using directives
            Assert.Contains("using LMP;", code);
            Assert.Contains("using Microsoft.Extensions.AI;", code);
        }
        finally
        {
            Directory.Delete(tempDir, recursive: true);
        }
    }

    [Fact]
    public async Task WriteForChatClientTargetAsync_NullFields_Omitted()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"lmp-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var state = new ChatClientState(); // all null

            var path = await CSharpArtifactWriter.WriteForChatClientTargetAsync(
                state,
                className: "OptimizedClient",
                ns: "TestNs",
                outputDir: tempDir,
                score: 0.5f,
                optimizerName: "TestOptimizer");

            var code = await File.ReadAllTextAsync(path);

            Assert.DoesNotContain("SystemPrompt =", code);
            Assert.DoesNotContain("Temperature =", code);
            Assert.DoesNotContain("SelectedToolNames", code);
            Assert.Contains("public static class OptimizedClient", code);
            Assert.Contains("Build(IChatClient baseClient, IReadOnlyList<AITool>? tools = null)", code);
        }
        finally
        {
            Directory.Delete(tempDir, recursive: true);
        }
    }

    [Fact]
    public async Task WriteForChatClientTargetAsync_MultilineSystemPrompt_UsesRawStringLiteral()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"lmp-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var state = new ChatClientState
            {
                SystemPrompt = "Line one.\nLine two.\nLine three."
            };

            var path = await CSharpArtifactWriter.WriteForChatClientTargetAsync(
                state,
                className: "Opt",
                ns: "Ns",
                outputDir: tempDir,
                score: 0.6f,
                optimizerName: "Test");

            var code = await File.ReadAllTextAsync(path);

            // Multiline prompt should use raw string literal (""")
            Assert.Contains("\"\"\"", code);
            Assert.Contains("Line one.", code);
            Assert.Contains("Line two.", code);
        }
        finally
        {
            Directory.Delete(tempDir, recursive: true);
        }
    }

    [Fact]
    public async Task WriteForChatClientTargetAsync_NoBaseline_OmitsBaselineFromHeader()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"lmp-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var state = new ChatClientState { Temperature = 1.0f };

            var path = await CSharpArtifactWriter.WriteForChatClientTargetAsync(
                state,
                className: "Opt",
                ns: "Ns",
                outputDir: tempDir,
                score: 0.55f,
                optimizerName: "Test",
                baseline: null);

            var code = await File.ReadAllTextAsync(path);
            Assert.DoesNotContain("Baseline:", code);
            Assert.Contains("Score: 0.5500", code);
        }
        finally
        {
            Directory.Delete(tempDir, recursive: true);
        }
    }

    [Fact]
    public async Task WriteForChatClientTargetAsync_OutputFileNamedAfterClassName()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"lmp-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var state = new ChatClientState();

            var path = await CSharpArtifactWriter.WriteForChatClientTargetAsync(
                state,
                className: "MyOptimizedClient",
                ns: "Ns",
                outputDir: tempDir,
                score: 0.5f,
                optimizerName: "Test");

            Assert.Equal("MyOptimizedClient.g.cs", Path.GetFileName(path));
        }
        finally
        {
            Directory.Delete(tempDir, recursive: true);
        }
    }
}
